#!/usr/bin/env python3
"""
Generate docs/dataset/erd.md (Mermaid ERD) from the official data dictionary PDF.

Columns, types and constraints are parsed from docs/dataset/LATAM_Bank_Complete_Data_Dictionary.pdf
so the diagram cannot drift from the documentation. Relationships come from the
"Foreign Key Relationships" section of the same PDF.

Usage:
    uv run --with pypdf scripts/generate_erd.py
"""

import re
from collections import OrderedDict
from pathlib import Path

from pypdf import PdfReader

ROOT = Path(__file__).resolve().parent.parent
REPO = ROOT.parent
PDF = REPO / "docs" / "dataset" / "LATAM_Bank_Complete_Data_Dictionary.pdf"
OUT = REPO / "docs" / "dataset" / "erd.md"

HEADER = re.compile(r"^(.+?) \[(DIMENSION|FACT|REFERENCE)\]$")
META = re.compile(r"^Rows: ([\d,]+) \| Source: (.+?) \| Partition: (\w+)$")
FK_LINE = re.compile(r"(\w+)\.(\w+)\s*→\s*(\w+)\.(\w+)\s*$")

GROUPS = {
    "DIMENSION": "Dimension",
    "FACT": "Fact",
    "REFERENCE": "Reference",
}


def parse_dictionary():
    text = "\n".join(p.extract_text() for p in PdfReader(PDF).pages)
    lines = [l.strip() for l in text.splitlines() if l.strip()]

    tables = OrderedDict()
    i = 0
    current = None
    while i < len(lines):
        m = HEADER.match(lines[i])
        if m and i + 1 < len(lines) and META.match(lines[i + 1]):
            meta = META.match(lines[i + 1])
            name = re.sub(r"\s+", "_", m.group(1).strip().lower())
            current = {
                "kind": m.group(2),
                "rows": meta.group(1),
                "source": meta.group(2),
                "partition": meta.group(3),
                "desc": lines[i + 2],
                "cols": [],
            }
            tables[name] = current
            i += 3
            continue
        if lines[i : i + 4] == ["Column", "Type", "Description", "Constraints"] and current:
            i += 4
            # Each column is exactly 4 lines: name, type, description, constraints
            while i + 3 < len(lines) and not (
                HEADER.match(lines[i])
                or lines[i].startswith(("Dimension Tables", "Fact Tables", "Reference Tables"))
            ):
                name, typ, desc, cons = lines[i : i + 4]
                if not re.fullmatch(r"[a-z_0-9]+", name):
                    break
                current["cols"].append((name, typ, desc, cons))
                i += 4
            continue
        i += 1

    # Foreign key section
    fks = []
    start = lines.index("Foreign Key Relationships")
    for l in lines[start:]:
        m = FK_LINE.search(l)
        if m:
            fks.append(m.groups())
    assert len(fks) == 24, f"expected 24 FKs, parsed {len(fks)}"
    return tables, fks


def mermaid_type(t: str) -> str:
    return re.sub(r"\(.*\)", "", t).lower()  # Mermaid types cannot contain parentheses


def build_mermaid(tables, fks):
    out = ["erDiagram"]
    for name, t in tables.items():
        out.append(f"    {name} {{")
        fk_cols = {c for ch, c, _, _ in fks if ch == name}
        for col, typ, desc, cons in t["cols"]:
            keys = []
            if "PK" in cons:
                keys.append("PK")
            if col in fk_cols or "FK" in cons:
                keys.append("FK")
            if "UNIQUE" in cons:
                keys.append("UK")
            key = (" " + ",".join(keys)) if keys else ""
            notes = []
            if "NOT NULL" in cons:
                notes.append("NOT NULL")
            if col == "process_date":
                notes.append("partition key")
            comment = f' "{", ".join(notes)}"' if notes else ""
            out.append(f"        {mermaid_type(typ)} {col}{key}{comment}")
        out.append("    }")
    out.append("")

    cols = {n: {c[0]: c for c in t["cols"]} for n, t in tables.items()}
    for child, col, parent, _ in fks:
        nullable = "NOT NULL" not in cols[child][col][3]
        left = "|o" if nullable else "||"  # parent side: zero-or-one vs exactly-one
        out.append(f'    {parent} {left}--o{{ {child} : "{col}"')
    # Logical (non-FK) link: exchange rates join on currency + date
    out.append('    daily_exchange_rates }o..o{ transactions : "currency + date (logical join)"')
    return "\n".join(out)


def main():
    tables, fks = parse_dictionary()
    assert len(tables) == 13, f"expected 13 tables, parsed {len(tables)}: {list(tables)}"

    md = [
        "# LATAM Bank – Entity Relationship Diagram\n",
        "_Generated by `eda/scripts/generate_erd.py` from "
        "`docs/dataset/LATAM_Bank_Complete_Data_Dictionary.pdf`. Do not edit by hand._\n",
        "Legend: `PK` primary key · `FK` foreign key · `UK` unique. "
        "Solid lines = documented foreign keys (`||` = mandatory, `|o` = nullable FK). "
        "Dotted = logical join without a declared FK.\n",
        "```mermaid",
        build_mermaid(tables, fks),
        "```\n",
        "## Tables\n",
        "| Table | Kind | Documented rows | Source | Partition | Columns | Description |",
        "|---|---|---:|---|---|---:|---|",
    ]
    for n, t in tables.items():
        md.append(
            f"| `{n}` | {GROUPS[t['kind']]} | {t['rows']} | {t['source']} | {t['partition']} | {len(t['cols'])} | {t['desc']} |"
        )

    md.append("\n## Foreign keys\n")
    md.append("| Child column | Parent | Nullable |")
    md.append("|---|---|---|")
    cols = {n: {c[0]: c for c in t["cols"]} for n, t in tables.items()}
    for child, col, parent, pk in fks:
        nullable = "NOT NULL" not in cols[child][col][3]
        md.append(f"| `{child}.{col}` | `{parent}.{pk}` | {'yes' if nullable else 'no'} |")

    md.append("""
## Modelling notes

- **Grain**: facts are one row per event (`transaction_id`, `event_id`, `interaction_id`, …).
  `customers` is the hub: every fact table references it.
- **Contact-center chain**: `call_center_interactions` → `call_transcripts` (1:0..1,
  `has_transcript`), → `satisfaction_surveys` (0..n), ← `complaints.origin_interaction_id`.
- **Not declared as FKs**: `call_center_interactions.mentioned_products` is a comma-separated
  list of `product_id`; `digital_events.utm_campaign` and `campaign_sends` relate loosely to
  marketing; `daily_exchange_rates` joins on (`date`, currency pair) with
  `transactions.process_date` / `currency`.
- **Composite PK**: `daily_exchange_rates (date, source_currency, target_currency)`.
- **Partitioning**: fact tables are partitioned by `process_date` (`year=/month=/day=`).
  `*_date` timestamps can fall on a later day than `process_date` (late arrivals).
- **Known deviations from the dictionary** are tracked in `eda/reports/eda_overview.md`.
""")
    OUT.write_text("\n".join(md))
    print(
        f"Wrote {OUT} ({len(tables)} tables, {len(fks)} FKs, "
        f"{sum(len(t['cols']) for t in tables.values())} columns)"
    )
    for n, t in tables.items():
        print(f"  {n:26s} {len(t['cols'])} cols")


if __name__ == "__main__":
    main()
