"""Create platform/docker/.env with random secrets (never committed). Re-running keeps existing values."""

import base64
import os
import secrets
from pathlib import Path

ENV = Path(__file__).with_name(".env")
KEYS = [
    "PG_CORE_SUPERUSER_PASSWORD",
    "PG_AUDIT_SUPERUSER_PASSWORD",
    "AIRFLOW_DB_PASSWORD",
    "MLFLOW_DB_PASSWORD",
    "PUBLISHER_DB_PASSWORD",
    "APP_READER_DB_PASSWORD",
    "SCORER_DB_PASSWORD",
    "MONITORING_DB_PASSWORD",
    "MARQUEZ_DB_PASSWORD",
    "AUDIT_WRITER_PASSWORD",
    "AUDIT_READER_PASSWORD",
    "MINIO_ROOT_PASSWORD",
    "MINIO_PLATFORM_PASSWORD",
    "MINIO_MLFLOW_PASSWORD",
    "NEO4J_PASSWORD",
    "GRAFANA_ADMIN_PASSWORD",
    "AIRFLOW_JWT_SECRET",
    "AIRFLOW_SECRET_KEY",
    "LATAM_PII_SALT",
    "SCORER_API_KEY",
]


def main() -> None:
    current = {}
    if ENV.exists():
        for line in ENV.read_text().splitlines():
            if "=" in line and not line.startswith("#"):
                k, v = line.split("=", 1)
                current[k] = v
    for k in KEYS:
        current.setdefault(k, secrets.token_urlsafe(24))
    current.setdefault("AIRFLOW_FERNET_KEY", base64.urlsafe_b64encode(os.urandom(32)).decode())
    current.setdefault("MINIO_ROOT_USER", "latam-root")
    current.setdefault("MINIO_PLATFORM_USER", "latam-platform")
    current.setdefault("MINIO_MLFLOW_USER", "latam-mlflow")
    current.setdefault("AIRFLOW_UID", str(os.getuid()))
    ENV.write_text(
        "# Generated by bootstrap_env.py. Local demo secrets; never commit.\n"
        + "\n".join(f"{k}={v}" for k, v in sorted(current.items()))
        + "\n"
    )
    ENV.chmod(0o600)
    print(f"wrote {ENV} ({len(current)} keys)")


if __name__ == "__main__":
    main()
