-- Generated by platform/dbt/scripts/generate_aggregates.py from eda/src/latam_eda/granularity_sql/dim_merchant_category.sql (ADR-017).
-- Edit the source and regenerate.
-- Merchant categories, the slicing dimension of the spend-mix fact. 'no merchant' holds the transactions that have no
-- merchant (withdrawals, transfers, deposits), so that every transaction belongs to exactly one category.
-- grain: category
select main_category as category, count(*) as n_merchants, list(merchant_name order by merchant_name) as merchants
from {{ ref('dim_merchant') }} group by 1
union all
select 'no merchant', 0, []
