-- Generated by platform/dbt/scripts/generate_aggregates.py from eda/src/latam_eda/granularity_sql/fct_customer_month.sql (ADR-017).
-- Edit the source and regenerate.
-- Periodic snapshot, one row per customer and calendar month (UTC month, as int_customer_month_tx), dense: a month with
-- no activity is a row of zeros, which every rolling window and every "inactive" label needs. It is the bank's
-- relationship with the customer month by month, across every process: money (transactions), self-service (digital
-- sessions), assisted service (contacts), dissatisfaction (complaints), marketing (campaign sends), voice (surveys) and
-- holdings (products open in the month). All measures are additive counts or sums; rates are derived at query time as
-- a ratio of sums. band_key points to dim_customer_band (the behaviour mini-dimension).
-- grain: customer_id, month_start
-- reconcile: n_tx = count(*) from {int_transactions_enriched} | month_start = cast(date_trunc('month', transaction_ts_utc) as date)
-- reconcile: outflow_usd = sum(outflow_usd) from {int_customer_month_tx} | month_start = month_start
-- reconcile: contacts = count(*) from {fct_interaction} | month_start = cast(date_trunc('month', interaction_ts_utc) as date)
-- reconcile: sessions = count(customer_id) from {fct_digital_session} | month_start = cast(date_trunc('month', session_start_utc) as date)
-- reconcile: complaints_opened = count(*) from {fct_complaint} | month_start = cast(date_trunc('month', created_ts_utc) as date)
-- reconcile: sends = count(*) from {fct_campaign_send} | month_start = cast(date_trunc('month', send_ts_utc) as date)
-- reconcile: surveys = count(*) from {stg_satisfaction_surveys} | month_start = cast(date_trunc('month', survey_ts_utc) as date)
-- dense: customer_id from {int_customer_profile} x month_start from {int_customer_month_tx}
with tx as (
    select customer_id, cast(date_trunc('month', transaction_ts_utc) as date) as month_start,
           count(*) filter (where transaction_type = 'Purchase')                      as n_purchases,
           count(*) filter (where transaction_type = 'Withdrawal')                    as n_withdrawals,
           count(*) filter (where transaction_type = 'Transfer')                      as n_transfers,
           count(*) filter (where transaction_type = 'Payment')                       as n_payments,
           count(*) filter (where transaction_type = 'Deposit')                       as n_deposits,
           count(*) filter (where channel in ('ATM', 'Branch'))                      as n_tx_physical,
           count(*) filter (where channel = 'POS')                                   as n_tx_merchant,
           count(*) filter (where channel in ('App', 'Web', 'Transfer'))             as n_tx_digital,
           count(*) filter (where transaction_status = 'Declined')                   as n_declined,
           count(*) filter (where is_fraud)                                          as n_flagged_fraud,
           count(*) filter (where is_cross_border)                                   as n_cross_border
    from {{ ref('int_transactions_enriched') }} group by all),
dg as (
    select customer_id, cast(date_trunc('month', session_start_utc) as date) as month_start,
           count(*) as sessions, sum(n_logins) as logins, sum(n_errors) as digital_errors,
           sum(n_purchases) as digital_purchases, count(*) filter (where n_errors > 0) as sessions_with_error
    from {{ ref('fct_digital_session') }} where customer_id is not null group by all),
cc as (
    select customer_id, cast(date_trunc('month', interaction_ts_utc) as date) as month_start,
           count(*) as contacts, count(*) filter (where was_escalated) as escalations,
           count(*) filter (where not was_resolved) as unresolved_contacts,
           count(*) filter (where interaction_type = 'Inbound Call') as inbound_calls,
           sum(duration_seconds) as handle_seconds, sum(wait_time_seconds) as wait_seconds,
           sum(sentiment_score) as sentiment_sum, count(sentiment_score) as sentiment_n
    from {{ ref('fct_interaction') }} group by all),
cp as (
    select customer_id, cast(date_trunc('month', created_ts_utc) as date) as month_start,
           count(*) as complaints_opened, count(*) filter (where sla_breached) as complaints_sla_breached,
           count(*) filter (where priority in ('High', 'Critical')) as complaints_high_priority
    from {{ ref('fct_complaint') }} group by all),
cs as (
    select customer_id, cast(date_trunc('month', send_ts_utc) as date) as month_start,
           count(*) as sends, count(*) filter (where was_delivered) as sends_delivered,
           count(*) filter (where was_opened) as sends_opened, count(*) filter (where was_clicked) as sends_clicked,
           count(*) filter (where had_conversion) as conversions, sum(coalesce(conversion_value, 0)) as conversion_value,
           sum(coalesce(send_cost, 0)) as send_cost
    from {{ ref('fct_campaign_send') }} group by all),
sv as (
    select customer_id, cast(date_trunc('month', survey_ts_utc) as date) as month_start,
           count(*) as surveys, sum(main_score) as survey_score_sum, count(main_score) as survey_score_n,
           count(*) filter (where nps_category = 'Detractor') as detractors,
           count(*) filter (where nps_category = 'Passive') as passives,
           count(*) filter (where nps_category = 'Promoter') as promoters
    from {{ ref('stg_satisfaction_surveys') }} group by all),
hold as (
    select g.customer_id, g.month_start,
           count(p.product_id) as products_held, count(p.product_id) filter (where p.is_credit_product) as credit_products_held
    from {{ ref('int_customer_month_tx') }} g
    join {{ ref('int_products_enriched') }} p
      on p.customer_id = g.customer_id
     and p.opening_date < g.month_start + interval 1 month
     and (p.expiration_date is null or p.expiration_date >= g.month_start)
    group by all),
base as (
    select g.*,
           coalesce(tx.n_purchases, 0) as n_purchases, coalesce(tx.n_withdrawals, 0) as n_withdrawals,
           coalesce(tx.n_transfers, 0) as n_transfers, coalesce(tx.n_payments, 0) as n_payments,
           coalesce(tx.n_deposits, 0) as n_deposits, coalesce(tx.n_tx_physical, 0) as n_tx_physical,
           coalesce(tx.n_tx_merchant, 0) as n_tx_merchant, coalesce(tx.n_tx_digital, 0) as n_tx_digital,
           coalesce(tx.n_declined, 0) as n_declined, coalesce(tx.n_flagged_fraud, 0) as n_flagged_fraud,
           coalesce(tx.n_cross_border, 0) as n_cross_border,
           coalesce(dg.sessions, 0) as sessions, coalesce(dg.logins, 0) as logins,
           coalesce(dg.digital_errors, 0) as digital_errors, coalesce(dg.digital_purchases, 0) as digital_purchases,
           coalesce(dg.sessions_with_error, 0) as sessions_with_error,
           coalesce(cc.contacts, 0) as contacts, coalesce(cc.escalations, 0) as escalations,
           coalesce(cc.unresolved_contacts, 0) as unresolved_contacts, coalesce(cc.inbound_calls, 0) as inbound_calls,
           coalesce(cc.handle_seconds, 0) as handle_seconds, coalesce(cc.wait_seconds, 0) as wait_seconds,
           coalesce(cc.sentiment_sum, 0) as sentiment_sum, coalesce(cc.sentiment_n, 0) as sentiment_n,
           coalesce(cp.complaints_opened, 0) as complaints_opened,
           coalesce(cp.complaints_sla_breached, 0) as complaints_sla_breached,
           coalesce(cp.complaints_high_priority, 0) as complaints_high_priority,
           coalesce(cs.sends, 0) as sends, coalesce(cs.sends_delivered, 0) as sends_delivered,
           coalesce(cs.sends_opened, 0) as sends_opened, coalesce(cs.sends_clicked, 0) as sends_clicked,
           coalesce(cs.conversions, 0) as conversions, coalesce(cs.conversion_value, 0) as conversion_value,
           coalesce(cs.send_cost, 0) as send_cost,
           coalesce(sv.surveys, 0) as surveys, coalesce(sv.survey_score_sum, 0) as survey_score_sum,
           coalesce(sv.survey_score_n, 0) as survey_score_n, coalesce(sv.detractors, 0) as detractors,
           coalesce(sv.passives, 0) as passives, coalesce(sv.promoters, 0) as promoters,
           coalesce(h.products_held, 0) as products_held, coalesce(h.credit_products_held, 0) as credit_products_held
    from {{ ref('int_customer_month_tx') }} g
    left join tx using (customer_id, month_start)
    left join dg using (customer_id, month_start)
    left join cc using (customer_id, month_start)
    left join cp using (customer_id, month_start)
    left join cs using (customer_id, month_start)
    left join sv using (customer_id, month_start)
    left join hold h using (customer_id, month_start)
)
select
    b.*,
    c.country_code,
    (case when b.n_tx = 0 then 0 when b.n_tx <= 2 then 1 when b.n_tx <= 5 then 2 else 3 end) * 100
  + (case when b.outflow_usd = 0 then 0 when b.outflow_usd < 500 then 1 when b.outflow_usd < 2000 then 2 else 3 end) * 10
  + (case when b.sessions = 0 then 0 when b.sessions <= 3 then 1 else 2 end) * 2
  + (case when b.contacts > 0 then 1 else 0 end)                                                    as band_key
from base b
join {{ ref('int_customer_profile') }} c using (customer_id)
