-- Generated by platform/dbt/scripts/generate_aggregates.py from eda/src/latam_eda/granularity_sql/fct_agent_day.sql (ADR-017).
-- Edit the source and regenerate.
-- Periodic snapshot, one row per agent and day worked (sparse: an agent appears on the days they handled contacts),
-- on the contact centre's delivery day (process_date, the 24 hours from 08:00 UTC): agents serve every market from one
-- contact centre, so the working day is the batch day, not a customer's local day. The grain of workforce management and quality coaching: volume, handle and wait time, resolution, escalation,
-- sentiment, survey scores and the complaints assigned. Averages are derived as ratios of the stored sums.
-- grain: agent_id, work_date
-- reconcile: contacts = count(agent_id) from {fct_interaction}
-- reconcile: surveys = count(agent_id) from {stg_satisfaction_surveys}
with cc as (
    select agent_id, process_date as work_date,
           count(*) as contacts, count(*) filter (where interaction_type = 'Inbound Call') as inbound_calls,
           count(*) filter (where was_resolved) as resolved, count(*) filter (where was_escalated) as escalated,
           count(*) filter (where accent_matched) as accent_matched_contacts,
           sum(duration_seconds) as handle_seconds, sum(wait_time_seconds) as wait_seconds,
           sum(sentiment_score) as sentiment_sum, count(sentiment_score) as sentiment_n
    from {{ ref('fct_interaction') }} where agent_id is not null group by all),
sv as (
    select agent_id, process_date as work_date,
           count(*) as surveys, sum(main_score) as survey_score_sum, count(main_score) as survey_score_n,
           count(*) filter (where nps_category = 'Detractor') as detractors
    from {{ ref('stg_satisfaction_surveys') }} where agent_id is not null group by all),
cp as (
    select assigned_agent_id as agent_id, cast(assigned_ts_utc - interval 8 hour as date) as work_date,
           count(*) as complaints_assigned
    from {{ ref('fct_complaint') }} where assigned_agent_id is not null and assigned_ts_utc is not null group by all),
k as (select agent_id, work_date from cc union select agent_id, work_date from sv union select agent_id, work_date from cp)
select k.agent_id, k.work_date, a.agent_type, a.experience_level, a.native_accent, a.work_shift,
       coalesce(cc.contacts, 0) as contacts, coalesce(cc.inbound_calls, 0) as inbound_calls,
       coalesce(cc.resolved, 0) as resolved, coalesce(cc.escalated, 0) as escalated,
       coalesce(cc.accent_matched_contacts, 0) as accent_matched_contacts,
       coalesce(cc.handle_seconds, 0) as handle_seconds, coalesce(cc.wait_seconds, 0) as wait_seconds,
       coalesce(cc.sentiment_sum, 0) as sentiment_sum, coalesce(cc.sentiment_n, 0) as sentiment_n,
       coalesce(sv.surveys, 0) as surveys, coalesce(sv.survey_score_sum, 0) as survey_score_sum,
       coalesce(sv.survey_score_n, 0) as survey_score_n, coalesce(sv.detractors, 0) as detractors,
       coalesce(cp.complaints_assigned, 0) as complaints_assigned
from k
left join {{ ref('dim_agent') }} a using (agent_id)
left join cc using (agent_id, work_date)
left join sv using (agent_id, work_date)
left join cp using (agent_id, work_date)
