"""Generate enforced dbt contracts (column names + data types) for published models from the built relations.

Contracts turn a model's schema into an API: a change that renames, drops or retypes a column fails the build
instead of silently breaking Postgres serving, ML loaders or agent tools. Run from platform/dbt after a build:

    uv run python scripts/generate_contracts.py serving    # writes models/serving/_serving.yml
"""

from __future__ import annotations

import sys
from pathlib import Path

import duckdb
import yaml

DESCRIPTIONS = {
    "serving_customer_360": "Customer 360 published to Postgres (bank_serving.serving.customer_360) for agent and app lookups. Tokens only.",
    "serving_account_inquiry": "Per-product inquiry answers (balance, pending, declines with decoded reasons, last 20 transactions as JSON).",
    "serving_card_support": "Per-card diagnostics and rule-based next best action.",
    "serving_dispute_case": "Per-dispute case view with SLA clocks and probabilistic transaction link with evidence.",
    "serving_credit_eligibility": "Latest eligibility with adverse-action reason codes (illustrative policy).",
    "serving_online_fraud_state": "Per-customer warm-start state for the streaming fraud scorer as of the stream cutoff.",
}
GRAIN = {
    "serving_customer_360": "customer_id",
    "serving_account_inquiry": "product_id",
    "serving_card_support": "product_id",
    "serving_dispute_case": "complaint_id",
    "serving_credit_eligibility": "customer_id",
    "serving_online_fraud_state": "customer_id",
}


def main(schema: str) -> None:
    con = duckdb.connect("../../data/lake/lakehouse.duckdb", read_only=True)
    models = []
    for (table,) in con.sql(
        f"select table_name from information_schema.tables where table_schema = '{schema}' order by 1"
    ).fetchall():
        cols = con.sql(f"describe {schema}.{table}").fetchall()
        columns = []
        for name, dtype, *_ in cols:
            col = {"name": name, "data_type": dtype}
            if name == GRAIN.get(table):
                col["constraints"] = [{"type": "not_null"}]
                col["data_tests"] = ["unique"]
            columns.append(col)
        models.append(
            {
                "name": table,
                "description": DESCRIPTIONS.get(table, ""),
                "config": {
                    "contract": {"enforced": True},
                    "meta": {"grain": GRAIN.get(table), "publish_to": "postgres.bank_serving"},
                },
                "columns": columns,
            }
        )
    out = Path(f"models/{schema}/_{schema}.yml")
    header = "# Generated by scripts/generate_contracts.py from the built relations; edit descriptions here, types via the SQL.\n"
    out.write_text(
        header + yaml.safe_dump({"version": 2, "models": models}, sort_keys=False, width=120)
    )
    print(f"wrote {out} with {len(models)} contracts")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "serving")
