"""Generate the dbt artefacts that type lossless bronze against the reviewed source contracts.

One function turns a contract into SQL predicates; every artefact below uses it, so the cast, the cell
findings and the partition profile can never disagree about what breaks a contract:

* models/silver/typed/typed_<table>[_holdout].sql: lossless bronze typed explicitly ('' and absent fields
  -> NULL; a value that does not cast -> NULL plus a finding in `_dq_issues`). Every record is kept.
* models/silver/quality/dq_partition_profile.sql: per partition and column, the counts the schema-drift
  circuit breaker needs (absent, empty, cast failures, foreign formats, broken keys, new vocabulary, scale).
* models/audit/dq_cell_findings.sql: one row per flagged cell, with lineage back to the bronze record.
* seeds/source_contract_columns.csv: the contracts as a table (header order, baselines) for the drift model.

    cd platform/dbt && uv run python scripts/generate_silver_from_contracts.py           # write
    cd platform/dbt && uv run python scripts/generate_silver_from_contracts.py --check   # CI: fail if stale
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import io
import json
import sys
from pathlib import Path

import yaml

DBT = Path(__file__).resolve().parents[1]
CONTRACTS = DBT.parent / "contracts"
SOURCES = CONTRACTS / "sources"
TYPED_DIR = DBT / "models" / "silver" / "typed"
PROFILE = DBT / "models" / "silver" / "quality" / "dq_partition_profile.sql"
FINDINGS = DBT / "models" / "audit" / "dq_cell_findings.sql"
SEED = DBT / "seeds" / "source_contract_columns.csv"

# dbt source -> tables typed into silver. Holdout: only the slices silver reads (stream replay parity).
ZONES = {"bronze_raw": None, "holdout_raw": ["transactions", "digital_events"]}
ZONE_NAME = {"bronze_raw": "bronze", "holdout_raw": "holdout"}
ISSUE_CODES = {
    "G": "record breaks the CSV grammar (parse status not ok)",
    "N": "required field empty or absent",
    "T": "value does not cast to the contract type",
    "F": "value in a format the contract does not accept",
    "K": "identifier breaks the key pattern",
    "V1": "value outside the contract vocabulary",
    "V2": "variant spelling of a vocabulary value",
    "P": "null rendered into free text (nan, None, ...)",
    "S": "unrendered template slot in free text",
}
NUMERIC = {"DOUBLE", "BIGINT", "INTEGER"}
DO_NOT_EDIT = "Generated by scripts/generate_silver_from_contracts.py: do not edit, change the contract and regenerate."


# ------------------------------------------------------------------------------------------ contracts
def load_contracts() -> dict[str, dict]:
    out = {}
    for p in sorted(SOURCES.glob("*.yml")):
        c = yaml.safe_load(p.read_text())
        c["contract_version"] = version(c)
        out[c["table"]] = c
    return out


def version(contract: dict) -> str:
    body = {k: v for k, v in contract.items() if k != "contract_version"}
    return hashlib.sha256(json.dumps(body, sort_keys=True).encode()).hexdigest()[:12]


def value_classes() -> dict:
    return yaml.safe_load((CONTRACTS / "value_classes.yml").read_text())


# ------------------------------------------------------------------------------------------------ SQL
def q(col: str) -> str:
    return '"' + col.replace('"', '""') + '"'


def lit(s: str) -> str:
    out = "'" + str(s).replace("'", "''") + "'"
    if any(t in out for t in ("{{", "{%", "{#")):
        raise ValueError(f"literal would be read as Jinja: {out}")
    return out


def re2(rx: str) -> str:
    """A leading (?i) flag scoped to its own alternative, so classes can be OR-ed together."""
    return f"(?i:{rx[4:]})" if rx.startswith("(?i)") else f"(?:{rx})"


def raw(col: str, alias: str = "r") -> str:
    return f"{alias}.{q(col)}"


def typed(col: str, spec: dict) -> str:
    if spec["type"] == "VARCHAR":
        return f"nullif({raw(col)}, '')"
    return f"try_cast(nullif({raw(col)}, '') AS {spec['type']})"


def checks(col: str, spec: dict, vc: dict) -> list[tuple[str, str]]:
    """(issue code, SQL condition over the raw text `r.<col>`) for every check the contract asks for."""
    v, out = raw(col), []
    if spec.get("required"):
        out.append(("N", f"coalesce({v}, '') = ''"))
    if spec["type"] != "VARCHAR":
        out.append(("T", f"{v} <> '' AND try_cast({v} AS {spec['type']}) IS NULL"))
    if spec.get("formats"):
        rx = "|".join(re2(vc["classes"][f]) for f in spec["formats"])
        cond = f"{v} <> '' AND NOT regexp_full_match({v}, {lit(rx)})"
        if spec["type"] != "VARCHAR":  # a value that does not cast is already T
            cond += f" AND try_cast({v} AS {spec['type']}) IS NOT NULL"
        out.append(("F", cond))
    if spec.get("key_pattern"):
        kp = spec["key_pattern"].removeprefix("^").removesuffix("$")
        out.append(("K", f"{v} <> '' AND NOT regexp_full_match({v}, {lit(kp)})"))
    if "vocabulary" in spec:
        known = list(spec["vocabulary"]) + list(spec.get("variants", {}))
        out.append(("V1", f"{v} <> '' AND {v} NOT IN ({', '.join(lit(x) for x in known)})"))
    if spec.get("variants"):
        out.append(("V2", f"{v} IN ({', '.join(lit(x) for x in spec['variants'])})"))
    for scan in spec.get("scan", []):
        code = {"null_word": "P", "slot": "S"}[scan]
        out.append((code, f"regexp_matches({v}, {lit(vc['scans'][scan])})"))
    return out


def issues_expr(contract: dict, vc: dict, indent: str) -> str:
    arms = ["CASE WHEN r._parse_status <> 'ok' THEN '*:G' END"]
    for col, spec in contract["columns"].items():
        arms += [
            f"CASE WHEN {cond} THEN {lit(col + ':' + code)} END"
            for code, cond in checks(col, spec, vc)
        ]
    body = f",\n{indent}    ".join(arms)
    return f"list_filter([\n{indent}    {body}\n{indent}], x -> x IS NOT NULL)"


def entity(contract: dict) -> str:
    keys = contract["entity_key"]
    if len(keys) == 1:
        return raw(keys[0])
    return "concat_ws('|', " + ", ".join(raw(k) for k in keys) + ")"


def masked(col: str, spec: dict, alias: str) -> str:
    """The flagged raw value as evidence; personal data and free text only as a shape (A=letter, 9=digit)."""
    v = raw(col, alias)
    if spec.get("pii"):
        return f"'shape:' || left(regexp_replace(regexp_replace({v}, '\\pL', 'A', 'g'), '\\pN', '9', 'g'), 64)"
    return f"left({v}, 256)"


def tables(zone: str, contracts: dict) -> list[str]:
    return [t for t in ZONES[zone] if t in contracts] if ZONES[zone] else sorted(contracts)


def model_name(zone: str, table: str) -> str:
    return f"typed_{table}" + ("_holdout" if zone == "holdout_raw" else "")


# ------------------------------------------------------------------------------------------ artefacts
def typed_model(zone: str, c: dict, vc: dict) -> str:
    cols = ",\n".join(f"    {typed(col, spec)} AS {q(col)}" for col, spec in c["columns"].items())
    return f"""-- {c["table"]} from {"lossless bronze" if zone == "bronze_raw" else "the lossless holdout zone"}, typed against platform/contracts/sources/{c["table"]}.yml
-- (contract {c["contract_version"]}). {DO_NOT_EDIT}
-- '' and absent fields become NULL; a value that does not cast becomes NULL and is listed in _dq_issues
-- as '<column>:<code>' (see audit.dq_cell_findings). Every bronze record is kept, flagged or not.
select
{cols},
    cast(r._partition_date AS date) AS _partition_date,
    r._source_file,
    r._record_no,
    r._record_sha256,
    r._parse_status,
    '{c["contract_version"]}' AS _contract_version,
    {issues_expr(c, vc, "    ")} AS _dq_issues
from {{{{ source('{zone}', '{c["table"]}') }}}} r
"""


def typed_yml(contracts: dict) -> str:
    models = []
    for zone in ZONES:
        for t in tables(zone, contracts):
            c = contracts[t]
            models.append(
                {
                    "name": model_name(zone, t),
                    "description": (
                        f"{t} ({ZONE_NAME[zone]} zone) typed from lossless bronze against source contract "
                        f"{c['contract_version']}. One row per bronze record; `_dq_issues` lists the cells "
                        "that break the contract. Generated: see scripts/generate_silver_from_contracts.py."
                    ),
                    "columns": [
                        {
                            "name": "_record_no",
                            "description": "Record number in the source file (1 = first data record).",
                        },
                        {
                            "name": "_source_file",
                            "description": "Landing path of the file the record came from.",
                        },
                        {
                            "name": "_dq_issues",
                            "description": "Contract breaches as '<column>:<code>' (codes in audit.dq_cell_findings).",
                        },
                    ],
                }
            )
    doc = {"version": 2, "models": models}
    return f"# {DO_NOT_EDIT}\n" + yaml.safe_dump(doc, sort_keys=False, width=120)


def count_if(conds: dict[str, str], code: str) -> str:
    return f"count(*) FILTER (WHERE {conds[code]})" if code in conds else "0::BIGINT"


def profile_model(contracts: dict, vc: dict) -> str:
    parts = []
    for zone in ZONES:
        for t in tables(zone, contracts):
            c = contracts[t]
            metrics = []
            for col, spec in c["columns"].items():
                conds = dict(checks(col, spec, vc))
                n = {code: count_if(conds, code) for code in ("T", "F", "K", "V1", "V2")}
                placeholder = " + ".join(count_if(conds, k) for k in ("P", "S") if k in conds)
                placeholder = placeholder or "0::BIGINT"
                if spec["type"] in NUMERIC:
                    x = typed(col, spec)
                    nonzero = f"count({x}) FILTER (WHERE {x} <> 0)"
                    scale = f"log10(median(abs({x})) FILTER (WHERE {x} <> 0))"
                else:
                    nonzero, scale = "0::BIGINT", "NULL::DOUBLE"
                metrics.append(
                    f"        struct_pack(\n"
                    f"            n_absent := count(*) FILTER (WHERE {raw(col)} IS NULL),\n"
                    f"            n_empty := count(*) FILTER (WHERE {raw(col)} = ''),\n"
                    f"            n_cast := {n['T']},\n"
                    f"            n_format := {n['F']},\n"
                    f"            n_key := {n['K']},\n"
                    f"            n_unknown := {n['V1']},\n"
                    f"            n_variant := {n['V2']},\n"
                    f"            n_placeholder := {placeholder},\n"
                    f"            n_nonzero := {nonzero},\n"
                    f"            log10_median := {scale}\n"
                    f"        ) AS {q(col)}"
                )
            cols = ", ".join(q(col) for col in c["columns"])
            struct_cols = ",\n".join(metrics)
            parts.append(
                f"""select '{ZONE_NAME[zone]}' AS zone, '{t}' AS table_name, '{c["contract_version"]}' AS contract_version,
       partition_date, n_rows, n_grammar, column_name, unnest(m)
from (
    select
        cast(r._partition_date AS date) AS partition_date,
        count(*) AS n_rows,
        count(*) FILTER (WHERE r._parse_status <> 'ok') AS n_grammar,
{struct_cols}
    from {{{{ source('{zone}', '{t}') }}}} r
    group by 1
) unpivot (m FOR column_name IN ({cols}))"""
            )
    body = "\nunion all\n".join(parts)
    return f"""-- Per bronze partition and contract column: the counts the schema-drift circuit breaker reads
-- (dq_schema_drift). Computed from the raw text, with the same predicates as the typed models.
-- {DO_NOT_EDIT}
{body}
"""


def findings_model(contracts: dict, vc: dict) -> str:
    parts = []
    for zone in ZONES:
        for t in tables(zone, contracts):
            c = contracts[t]
            value_arms = "\n".join(
                f"            WHEN {lit(col)} THEN {masked(col, spec, 'f')}"
                for col, spec in c["columns"].items()
            )
            parts.append(
                f"""select
    '{ZONE_NAME[zone]}' AS zone,
    '{t}' AS table_name,
    partition_date, source_file, record_no, record_sha256, entity_id,
    split_part(issue, ':', 1) AS column_name,
    split_part(issue, ':', 2) AS issue_code,
    CASE split_part(issue, ':', 1)
            WHEN '*' THEN 'shape:' || left(regexp_replace(regexp_replace(raw_record, '\\pL', 'A', 'g'), '\\pN', '9', 'g'), 256)
{value_arms}
    END AS raw_value,
    '{c["contract_version"]}' AS contract_version
from (
    select
        r.*,
        cast(r._partition_date AS date) AS partition_date,
        r._source_file AS source_file,
        r._record_no AS record_no,
        r._record_sha256 AS record_sha256,
        cast(r._raw_record AS varchar) AS raw_record,
        {entity(c)} AS entity_id,
        unnest({issues_expr(c, vc, "        ")}) AS issue
    from {{{{ source('{zone}', '{t}') }}}} r
) f"""
            )
    body = "\nunion all\n".join(parts)
    return f"""-- One row per cell that breaks its source contract, with lineage to the bronze record (source file,
-- record number, record hash). Nothing is dropped from silver because of a finding: this table is the
-- work list for review and correction. Personal data and free text appear only as a shape.
-- Codes: {"; ".join(f"{k} = {v}" for k, v in ISSUE_CODES.items())}.
-- {DO_NOT_EDIT}
{body}
"""


def seed_csv(contracts: dict) -> str:
    buf = io.StringIO()
    w = csv.writer(buf, lineterminator="\n")
    w.writerow(["table_name", "column_name", "ordinal", "data_type", "required", "empty_share",
                "enumerated", "keyed", "pii_type", "scale_log10_median", "scale_mad", "contract_version"])  # fmt: skip
    for t, c in contracts.items():
        for i, (col, spec) in enumerate(c["columns"].items(), start=1):
            s = spec.get("scale") or {}
            w.writerow([t, col, i, spec["type"], str(spec.get("required", False)).lower(),
                        spec.get("empty_share", 0), str("vocabulary" in spec).lower(),
                        str("key_pattern" in spec).lower(), spec.get("pii", ""),
                        s.get("log10_median", ""), s.get("mad", ""), c["contract_version"]])  # fmt: skip
    return buf.getvalue()


def render_all() -> dict[Path, str]:
    contracts, vc = load_contracts(), value_classes()
    out: dict[Path, str] = {}
    for zone in ZONES:
        for t in tables(zone, contracts):
            out[TYPED_DIR / f"{model_name(zone, t)}.sql"] = typed_model(zone, contracts[t], vc)
    out[TYPED_DIR / "_typed.yml"] = typed_yml(contracts)
    out[PROFILE] = profile_model(contracts, vc)
    out[FINDINGS] = findings_model(contracts, vc)
    out[SEED] = seed_csv(contracts)
    return out


def stale(rendered: dict[Path, str]) -> list[str]:
    """Generated files that differ from the contracts, plus typed models no contract produces."""
    diff = [
        str(p.relative_to(DBT)) for p, s in rendered.items() if not p.exists() or p.read_text() != s
    ]
    extra = [str(p.relative_to(DBT)) for p in TYPED_DIR.glob("typed_*.sql") if p not in rendered]
    return diff + extra


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--check", action="store_true", help="fail if generated files are out of date")
    args = ap.parse_args()
    rendered = render_all()
    if args.check:
        bad = stale(rendered)
        if bad:
            sys.exit("out of date with platform/contracts (regenerate): " + ", ".join(bad))
        print(f"{len(rendered)} generated files up to date")
        return
    for p, s in rendered.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(s)
    for p in TYPED_DIR.glob("typed_*.sql"):
        if p not in rendered:
            p.unlink()
    print(f"wrote {len(rendered)} files")


if __name__ == "__main__":
    main()
