"""Generate the gold/aggregates dbt layer from the EDA's header-contracted SQL (ADR-017).

The aggregate grains were designed and checked in the granularity notebooks (eda/src/latam_eda/granularity*_sql). This
script keeps them the single source and writes, for every model:

* models/gold/aggregates/<family>/<name>.sql: the same SQL, ``{name}`` references turned into ``ref('name')``;
* tests/aggregates/<family>/<name>__*.sql: the header contracts as singular data tests, failing rows on violation:
    - ``-- grain: k1, k2``                     the grain columns are unique together;
    - ``-- reconcile: m = agg from {fact} | k = expr``   the measure sums exactly to its atomic fact (per key, or in total);
    - ``-- dense: c1 from {a} x c2 from {b}``  a row for every member of the cross product.

and the two seeds the models read (country calendar and declared clock).

Run from eda/ (it imports latam_eda for the seeds):  PYTHONPATH=src uv run python ../platform/dbt/scripts/generate_aggregates.py
"""

from __future__ import annotations

import re
import shutil
from dataclasses import dataclass, field
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[3]
EDA = REPO / "eda" / "src" / "latam_eda"
DBT = REPO / "platform" / "dbt"
FAMILIES = {
    "day": "granularity_sql",
    "cell": "granularity_time_sql",
    "hour": "granularity_hour_sql",
}
SERIES = {
    "day": "series I, eda/notebooks/granularity",
    "cell": "series II, eda/notebooks/granularity_time",
    "hour": "series III, eda/notebooks/granularity_hour",
}
MODELS = DBT / "models" / "gold" / "aggregates"
TESTS = DBT / "tests" / "aggregates"
SEEDS = DBT / "seeds"
REF = re.compile(r"\{(\w+)\}")
# any_value() is banned by the determinism guard; every use in these models reads a value that is constant within the
# group (a campaign's attributes, a one-row bounds CTE), so min() returns the same value deterministically.
REWRITES = ((re.compile(r"\bany_value\s*\(", re.I), "min("),)
NOTE = "-- Generated by platform/dbt/scripts/generate_aggregates.py from eda/src/latam_eda/{src}/{name}.sql (ADR-017).\n-- Edit the source and regenerate.\n"


@dataclass
class Model:
    name: str
    family: str
    src_dir: str
    sql: str
    grain: list[str] = field(default_factory=list)
    reconcile: list[tuple[str, str, str]] = field(default_factory=list)
    dense: str | None = None
    prose: list[str] = field(default_factory=list)


def parse(path: Path, family: str) -> Model:
    m = Model(path.stem, family, path.parent.name, path.read_text())
    for line in m.sql.splitlines():
        s = line.strip()
        if not s.startswith("--"):
            continue
        s = s[2:].strip()
        if not (m.grain or m.reconcile or m.dense) and not s.startswith(
            ("grain:", "reconcile:", "dense:")
        ):
            m.prose.append(s)
        if s.startswith("grain:"):
            m.grain = [c.strip() for c in s.removeprefix("grain:").split(",") if c.strip()]
        elif s.startswith("reconcile:"):
            rule, _, keymap = s.removeprefix("reconcile:").partition("|")
            measure, _, atomic = rule.partition("=")
            m.reconcile.append((measure.strip(), atomic.strip(), keymap.strip()))
        elif s.startswith("dense:"):
            m.dense = s.removeprefix("dense:").strip()
    return m


def ref(text: str) -> str:
    return REF.sub(lambda g: "{{ ref('" + g.group(1) + "') }}", text)


def body(m: Model) -> str:
    out = []
    for line in m.sql.splitlines():
        if line.lstrip().startswith("--"):
            out.append(line)
            continue
        line = ref(line)
        for pat, rep in REWRITES:
            line = pat.sub(rep, line)
        out.append(line)
    return NOTE.format(src=m.src_dir, name=m.name) + "\n".join(out).rstrip() + "\n"


def split_top(text: str, sep: str = ",") -> list[str]:
    """Split on `sep` outside parentheses and quotes (a key mapping may hold function calls)."""
    out, depth, quote, cur = [], 0, None, []
    for ch in text:
        if quote:
            cur.append(ch)
            if ch == quote:
                quote = None
            continue
        if ch in "'\"":
            quote = ch
        elif ch == "(":
            depth += 1
        elif ch == ")":
            depth -= 1
        if ch == sep and depth == 0:
            out.append("".join(cur))
            cur = []
        else:
            cur.append(ch)
    if "".join(cur).strip():
        out.append("".join(cur))
    return out


def grain_test(m: Model) -> str:
    keys = ", ".join(m.grain)
    return (
        f"-- {m.name}: one row per ({keys}).\n"
        f"select count(*) as n_rows, count(distinct ({keys})) as n_keys\n"
        f"from {{{{ ref('{m.name}') }}}}\n"
        f"having count(*) <> count(distinct ({keys}))\n"
    )


def reconcile_test(m: Model, measure: str, atomic: str, keymap: str) -> str:
    agg, _, src = atomic.partition(" from ")
    src = ref(src.strip())
    pairs = [p.split("=", 1) for p in split_top(keymap) if "=" in p]
    keys = [k.strip() for k, _ in pairs]
    tol = "1e-6 * greatest(1, abs(coalesce(r.v, 0)))"
    if not keys:
        return (
            f"-- {m.name}: sum({measure}) equals {agg} of its atomic source.\n"
            f"with l as (select sum({measure}) as v from {{{{ ref('{m.name}') }}}}),\n"
            f"     r as (select {agg} as v from {src})\n"
            f"select l.v as aggregate_value, r.v as atomic_value from l, r\n"
            f"where abs(coalesce(l.v, 0) - coalesce(r.v, 0)) > {tol}\n"
        )
    exprs = [e.strip() for _, e in pairs]
    sel = ", ".join(f"{e} as {k}" for k, e in zip(keys, exprs, strict=True))
    on = " and ".join(f"l.{k} is not distinct from r.{k}" for k in keys)
    cols = ", ".join(f"coalesce(l.{k}, r.{k}) as {k}" for k in keys)
    return (
        f"-- {m.name}: {measure} per ({', '.join(keys)}) equals {agg} of its atomic source.\n"
        f"with l as (select {', '.join(keys)}, sum({measure}) as v from {{{{ ref('{m.name}') }}}} group by all),\n"
        f"     r as (select {sel}, {agg} as v from {src} group by all)\n"
        f"select {cols}, l.v as aggregate_value, r.v as atomic_value\n"
        f"from l full outer join r on {on}\n"
        f"where coalesce(l.v, 0) <> coalesce(r.v, 0) and abs(coalesce(l.v, 0) - coalesce(r.v, 0)) > {tol}\n"
    )


def dense_test(m: Model) -> str:
    parts = [p.strip() for p in m.dense.split(" x ")]
    sels, cols = [], []
    for p in parts:
        col, _, src = p.partition(" from ")
        cols.append(col.strip())
        sels.append(f"(select distinct {col.strip()} from {ref(src.strip())})")
    on = " and ".join(f"f.{c} = g.{c}" for c in cols)
    return (
        f"-- {m.name}: a row for every {' x '.join(cols)}.\n"
        f"select g.* from (select * from {' cross join '.join(sels)}) g\n"
        f"where not exists (select 1 from {{{{ ref('{m.name}') }}}} f where {on})\n"
    )


class _Block(yaml.SafeDumper):
    """Multi-line descriptions as literal blocks, so the YAML reads like the docs it holds."""


_Block.add_representer(
    str,
    lambda d, v: d.represent_scalar("tag:yaml.org,2002:str", v, style="|" if "\n" in v else None),
)


def plain(text: str) -> str:
    """`{model}` references read as model names in the documentation."""
    return REF.sub(lambda g: g.group(1), text)


def doc_yaml(family: str, models: list[Model]) -> str:
    """dbt properties for one family: the header's prose as the description, its contracts, and the grain columns."""
    out = []
    for m in models:
        contracts = [f"- grain: `{', '.join(m.grain)}` unique together" if m.grain else None]
        contracts += [
            f"- reconcile: `{meas}` = {plain(atomic)}"
            + (f" (per {plain(km)})" if km else " (in total)")
            for meas, atomic, km in m.reconcile
        ]
        if m.dense:
            contracts.append(f"- dense: {plain(m.dense)}")
        description = (
            plain(" ".join(m.prose))
            + "\n\n**Contracts** (each one a dbt test that fails the build):\n"
            + "\n".join(c for c in contracts if c)
            + f"\n\nSource: `eda/src/latam_eda/{m.src_dir}/{m.name}.sql` ({SERIES[family]}); generated by "
            "`platform/dbt/scripts/generate_aggregates.py` (ADR-017)."
        )
        out.append(
            {
                "name": m.name,
                "description": description,
                "meta": {
                    "family": family,
                    "adr": "ADR-017",
                    "source_sql": f"eda/src/latam_eda/{m.src_dir}/{m.name}.sql",
                },
                "columns": [
                    {
                        "name": c,
                        "description": f"Grain key of {m.name}: unique together with the other grain columns.",
                    }
                    for c in m.grain
                ],
            }
        )
    note = "# Generated by platform/dbt/scripts/generate_aggregates.py from the EDA SQL headers (ADR-017). Do not edit.\n"
    return note + yaml.dump(
        {"version": 2, "models": out}, Dumper=_Block, sort_keys=False, allow_unicode=True, width=120
    )


def seeds() -> None:
    from latam_eda import country, granularity

    cal = granularity.country_calendar()
    cal.to_csv(SEEDS / "seed_country_calendar.csv", index=False)
    (SEEDS / "seed_clock.csv").write_text(f"utc_offset_hours\n{country.BUSINESS_UTC_OFFSET}\n")


def main() -> None:
    for d in (MODELS, TESTS):
        if d.exists():
            shutil.rmtree(d)
    n_models = n_tests = 0
    for family, src in FAMILIES.items():
        (MODELS / family).mkdir(parents=True)
        (TESTS / family).mkdir(parents=True)
        family_models = []
        for path in sorted((EDA / src).glob("*.sql")):
            m = parse(path, family)
            family_models.append(m)
            (MODELS / family / f"{m.name}.sql").write_text(body(m))
            n_models += 1
            tests = {}
            if m.grain:
                tests[f"{m.name}__grain"] = grain_test(m)
            for i, (measure, atomic, keymap) in enumerate(m.reconcile, 1):
                tests[f"{m.name}__reconcile_{i}"] = reconcile_test(m, measure, atomic, keymap)
            if m.dense:
                tests[f"{m.name}__dense"] = dense_test(m)
            for name, sql in tests.items():
                (TESTS / family / f"{name}.sql").write_text(sql)
            n_tests += len(tests)
        (MODELS / family / f"_{family}.yml").write_text(doc_yaml(family, family_models))
    seeds()
    print(
        f"wrote {n_models} models and {n_tests} contract tests; seeds seed_country_calendar, seed_clock"
    )


if __name__ == "__main__":
    main()
