"""Generate enforced dbt contracts (column names + data types) for published models from the built relations.

Contracts turn a model's schema into an API: a change that renames, drops or retypes a column fails the build
instead of silently breaking Postgres serving, ML loaders or agent tools. Run from platform/dbt after a build:

    uv run python scripts/generate_contracts.py serving    # writes models/serving/_serving.yml

Column descriptions come from scripts/<schema>_columns.yml (a `common` map plus one map per model), so they
survive regeneration.
"""

from __future__ import annotations

import sys
from pathlib import Path

import duckdb
import yaml

SCRIPTS = Path(__file__).resolve().parent


class _Block(yaml.SafeDumper):
    """Write multi-line descriptions as literal blocks."""


_Block.add_representer(
    str,
    lambda dumper, value: dumper.represent_scalar(
        "tag:yaml.org,2002:str", value, style="|" if "\n" in value else None
    ),
)

DESCRIPTIONS = {
    "serving_customer_360": "Customer 360 published to Postgres (bank_serving.serving.customer_360) for agent and app lookups. Tokens only.",
    "serving_account_inquiry": "Per-product inquiry answers (balance, pending, declines with decoded reasons; history in serving_recent_transactions).",
    "serving_card_support": "Per-card diagnostics and rule-based next best action.",
    "serving_dispute_case": "Per-dispute case view with SLA clocks and probabilistic transaction link with evidence.",
    "serving_credit_eligibility": "Latest eligibility with adverse-action reason codes (illustrative policy).",
    "serving_online_fraud_state": "Per-customer warm-start state for the streaming fraud scorer as of the stream cutoff.",
    "serving_recent_transactions": "Last 20 transactions per product for inquiry answers (rank 1 = latest).",
}
GRAIN = {
    "serving_customer_360": "customer_id",
    "serving_account_inquiry": "product_id",
    "serving_card_support": "product_id",
    "serving_dispute_case": "complaint_id",
    "serving_credit_eligibility": "customer_id",
    "serving_online_fraud_state": "customer_id",
    "serving_recent_transactions": ["product_id", "recency_rank"],
}


def column_docs(schema: str) -> dict:
    path = SCRIPTS / f"{schema}_columns.yml"
    return yaml.safe_load(path.read_text()) if path.exists() else {}


def main(schema: str) -> None:
    docs = column_docs(schema)
    con = duckdb.connect("../../data/lake/lakehouse.duckdb", read_only=True)
    models = []
    for (table,) in con.sql(
        f"select table_name from information_schema.tables where table_schema = '{schema}' order by 1"
    ).fetchall():
        cols = con.sql(f"describe {schema}.{table}").fetchall()
        columns = []
        for name, dtype, *_ in cols:
            col = {"name": name, "data_type": dtype}
            text = (docs.get(table) or {}).get(name) or (docs.get("common") or {}).get(name)
            if text:
                col["description"] = text.strip()
            grain = GRAIN.get(table)
            if name == grain:
                col["constraints"] = [{"type": "not_null"}]
                col["data_tests"] = ["unique"]
            elif isinstance(grain, list) and name == grain[0]:
                col["constraints"] = [{"type": "not_null"}]
            columns.append(col)
        models.append(
            {
                "name": table,
                "description": DESCRIPTIONS.get(table, ""),
                "config": {
                    "contract": {"enforced": True},
                    "meta": {"grain": GRAIN.get(table), "publish_to": "postgres.bank_serving"},
                },
                "columns": columns,
            }
        )
    out = Path(f"models/{schema}/_{schema}.yml")
    header = (
        "# Generated by scripts/generate_contracts.py from the built relations. Model descriptions live in the\n"
        f"# script, column descriptions in scripts/{schema}_columns.yml, types in the SQL. Do not edit.\n"
    )
    out.write_text(
        header
        + yaml.dump(
            {"version": 2, "models": models},
            Dumper=_Block,
            sort_keys=False,
            width=120,
            allow_unicode=True,
        )
    )
    print(f"wrote {out} with {len(models)} contracts")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else "serving")
