"""Committed report artefacts: tables, report index, dashboards and summary docs."""

import re

import pandas as pd
import pytest

import export_dashboard_data
from conftest import EDA, NOTEBOOKS, REPO, TABLES

REPORTS = EDA / "reports"
CSVS = sorted(TABLES.glob("*.csv"))


@pytest.mark.parametrize("path", CSVS, ids=lambda p: p.stem)
def test_table_parses_and_is_not_empty(path):
    df = pd.read_csv(path)
    assert len(df) > 0
    assert len(df.columns) > 1
    assert not df.columns.duplicated().any()


@pytest.fixture(scope="module")
def set_difference():
    return pd.read_csv(TABLES / "set_difference_summary.csv").set_index("table")


def test_set_difference_adds_up(set_difference):
    df = set_difference
    assert (df.shared + df.only_main == df.main_keys).all()
    assert (df.shared + df.only_backup == df.backup_keys).all()
    pct = 100 * df.shared / df.main_keys
    assert ((pct - df.pct_main_shared).abs() < 1e-9).all()


def test_set_difference_status_matches_counts(set_difference):
    df = set_difference
    absent = df.backup_keys == 0
    assert (df.in_backup[absent] == "NO").all()
    assert (df.status[absent] == "absent from backup").all()
    identical = (df.only_main == 0) & (df.only_backup == 0) & ~absent
    assert (df.status[identical] == "identical key set").all()


def test_backup_summary_quotes_the_measured_overlap(set_difference):
    """docs/dataset/backup_comparison.md must not drift from notebook 02's numbers."""
    doc = (REPO / "docs" / "dataset" / "backup_comparison.md").read_text()
    paragraph = doc[doc.index("Primary-key overlap with main") :].split("\n\n")[0]
    quoted = dict(re.findall(r"(\w+) ([\d.]+) %", paragraph))
    aliases = {
        "customers": "customers",
        "transactions": "transactions",
        "interactions": "call_center_interactions",
        "sends": "campaign_sends",
        "events": "digital_events",
        "products": "products",
        "agents": "service_agents",
    }
    for word, table in aliases.items():
        measured = set_difference.loc[table, "pct_main_shared"]
        digits = len(quoted[word].partition(".")[2])
        assert round(measured, digits) == pytest.approx(float(quoted[word])), word


def links(html):
    return re.findall(r'(?:href|src)="([^"#]+)"', html)


def test_report_index_links_resolve():
    for target in links((REPORTS / "index.html").read_text()):
        if target.startswith("notebooks/"):
            # HTML exports are generated; the notebook source must exist
            stem = target.removeprefix("notebooks/").removesuffix(".html")
            assert (NOTEBOOKS / f"{stem}.py").exists(), target
        else:
            assert (REPORTS / target).exists(), target


DASHBOARDS = sorted((REPORTS / "dashboards").glob("*.html"))


@pytest.mark.parametrize("page", DASHBOARDS, ids=lambda p: p.stem)
def test_dashboard_assets_resolve(page):
    for target in links(page.read_text()):
        if target.startswith("https://"):
            assert target.startswith("https://cdnjs.cloudflare.com/"), target
        elif target.startswith("data/"):
            continue  # generated by export_dashboard_data.py, checked below
        else:
            assert (page.parent / target).exists(), target


def test_dashboards_load_exactly_what_the_export_writes():
    loaded = {
        m for page in DASHBOARDS for m in re.findall(r'src="data/(\w+)\.js"', page.read_text())
    }
    source = (EDA / "scripts" / "export_dashboard_data.py").read_text()
    exported = set(re.findall(r'dump\(\s*out,\s*"(\w+)"', source))
    assert loaded == exported == {"overlap", "timeshift", "anomalies"}
    assert export_dashboard_data.OUT == REPORTS / "dashboards" / "data"


def test_overview_report_figures_exist():
    md = (REPORTS / "eda_overview.md").read_text()
    figures = re.findall(r"!\[[^\]]*\]\(([^)]+)\)", md)
    assert len(figures) == 3
    for fig in figures:
        assert (REPORTS / fig).exists(), fig


def test_overview_report_covers_every_table():
    md = (REPORTS / "eda_overview.md").read_text()
    for table in ("transactions", "customers", "complaints", "daily_exchange_rates"):
        assert f"| {table} " in md
