select
    complaint_id,
    creation_date                                  as created_ts_utc,
    process_date,
    customer_id,
    case_type,
    category,
    subcategory,
    reception_channel,
    affected_product_id,
    related_branch_id,
    origin_interaction_id,
    description,
    claimed_amount,
    currency                                       as claimed_currency,
    priority,
    status,
    status in ('Resolved', 'Closed', 'Rejected')   as is_closed,
    assigned_agent_id,
    assignment_date                                as assigned_ts_utc,
    first_response_date                            as first_response_ts_utc,
    resolution_date                                as resolved_ts_utc,
    closing_date                                   as closed_ts_utc,
    sla_breached,
    cast(resolution_days as integer)               as resolution_days,
    resolution,
    compensation_granted,
    cast(resolution_satisfaction as integer)       as resolution_satisfaction,
    is_repeat_complainer
from {{ ref('typed_complaints') }} src
where {{ not_held('src', 'complaints') }}
