/* ================================================================ views: grain → group → named screen */
const GROUPS=[["overview","Overview"],["data","Data"],["findings","Findings"],["pipeline","Pipeline"],["walk","Walkthrough"],["decide","Decide"]];
const PAGES={}, VIEWS={event:[],country:[],daily:[],hourly:[]};
/* VW(grain, group, id, short title, options)
   options: mod (one atlas module, header taken from it), subs, intro, blocks, sub (headline), lede, eyebrow,
            nrs (new renderers to run), kind (models|kpis|decisions|build|overview), s (status dot), src (notebook source) */
function VW(g,group,id,title,o={}){
  const r=g+"-"+id, m=o.mod?MODS[o.mod]:null;
  const v=Object.assign({grain:g,group,id,title},o);
  if(m&&!o.blocks) v.blocks=[M(o.mod,{subs:o.subs,intro:o.intro})];
  if(m){ if(v.sub===undefined) v.sub=m.title; if(v.lede===undefined) v.lede=m.lede; if(v.eyebrow===undefined) v.eyebrow=m.eyebrow; }
  v.mods=[...new Set((v.blocks||[]).filter(b=>b.mod).map(b=>b.mod).concat(o.mods||[]))];
  PAGES[r]=v; VIEWS[g].push(r);
}
const KPIS=h=>({html:'<div class="kpis">'+h+'</div>'});
const K=(c,b,s)=>'<div class="kpi '+c+'"><b>'+b+'</b><span>'+s+'</span></div>';
const GF=g=>({html:'<section class="blk"><h3>This grain in one card</h3><div class="gfacts" data-g="'+g+'"></div></section>'});

/* ---------------------------------------------------------------- EVENT */
VW("event","overview","overview","The event grain at a glance",{kind:"overview",eyebrow:"Event grain · overview",sub:"The source as delivered: thirteen tables, one question at a time",
 lede:"Before any re-graining, the analysis read the data at the grain it arrives in: one transaction, one click, one call, one send. Each step answered a question the previous one raised, and each answer changed what the platform had to do.",
 mods:["overview"],nrs:["grainfacts"],src:"eda/notebooks 01–11 · medallion 01 · model_risk 01–02 · pipeline 01–12",blocks:[
 KPIS(K("","150,000","customers in Mexico, Colombia and Argentina")+K("","23.5 M","source records in daily CSV files, 3 years")+K("ok","44.3 M","records (main + backup) proven byte-exact in lossless bronze")+K("crit","AUC 0.504","best honest fraud model: no skill, because the label leaks")+K("ok","108 / 108","gold relations identical across two rebuilds")+K("warn","3 rules","breach their SLO by design of the data (R21, R25, R26)")),
 S("The story in eleven steps","Click a step to open the view where it is told.",'<div class="flow" id="storyFlow"></div>'),
 GF("event"),
 S("What the event grain decided for every later grain","",
  '<div class="cards"><div class="card"><h4>The data is complete and traceable</h4><p class="small">Every one of 44.3 M records is kept byte for byte with its hash; contracts type it without dropping a row; corrections are overlays a second person approves; two rebuilds give the same bytes.</p></div>'+
  '<div class="card"><h4>Labels are not behaviour</h4><p class="small"><code>is_fraud</code> is computed from <code>fraud_score</code>, transcripts are templates, conversions are not tied to the promoted product. Every later grain treats a high score as a leak until proven otherwise.</p></div>'+
  '<div class="card"><h4>Joins can be valid and wrong</h4><p class="small">Complaints name another customer\'s product in 66.4 % of cases; 19 % of transactions lose their dimension keys in the star. Test the business invariants of a join, not only its shape.</p></div>'+
  '<div class="card"><h4>Activity is thin</h4><p class="small">0.81 transactions per customer per month. Per-customer baselines are noise; population features and rate models are the honest choice, at every grain.</p></div></div>'),
 S("Next grain","",'<p class="kicker">Three countries live in one table, with three currencies and three regulators. Is the bank one population or three?</p><p><button class="btn primary" type="button" data-route="country-overview">Open the country grain →</button></p>')]});
VW("event","data","bank","The bank in the data",{mod:"bank",src:"eda/notebooks 01 · medallion 01"});
VW("event","data","arch","Medallion and Kimball",{mod:"arch",src:"platform docs · pipeline 01"});
VW("event","data","eda","EDA: the trust profile",{mod:"eda",s:"warn",src:"medallion 01 · model_risk 01"});
VW("event","findings","fraud","The fraud label trap",{mod:"fraud",s:"crit",src:"eda/notebooks 09 · pipeline 09"});
VW("event","findings","backup","The backup that wasn't",{mod:"backup",s:"crit",src:"eda/notebooks 02–06"});
VW("event","findings","anomaly","Anomaly detection",{mod:"anomaly",s:"ok",src:"eda/notebooks 07–11"});
VW("event","pipeline","forensics","Raw schema forensics",{mod:"forensics",s:"ok",src:"model_risk 01"});
VW("event","pipeline","bronze","Lossless bronze",{mod:"bronze",s:"ok",src:"pipeline 02"});
VW("event","pipeline","silver","Contracts and the circuit breaker",{mod:"silver",s:"ok",src:"pipeline 02–03"});
VW("event","pipeline","fix","Four-eyes correction",{mod:"fix",s:"ok",src:"model_risk 02"});
VW("event","pipeline","repro","Reproducible gold",{mod:"repro",s:"ok",src:"pipeline 06, 12"});
VW("event","pipeline","rules","The integrity rules",{mod:"rules",s:"warn",src:"pipeline 12"});
VW("event","walk","replay","Replaying the pipeline",{mod:"replay",src:"pipeline 01"});
VW("event","walk","silverwalk","Silver, step by step",{mod:"silverwalk",src:"pipeline 02–05"});
VW("event","walk","goldwalk","Gold: history, keys, the star",{mod:"goldwalk",s:"crit",src:"pipeline 06"});
VW("event","walk","martswalk","Marts: what the rules decide",{mod:"martswalk",s:"warn",src:"pipeline 07–08"});
VW("event","walk","mlwalk","Features, graph, privacy",{mod:"mlwalk",s:"warn",src:"pipeline 09–11"});
VW("event","walk","fixlist","What to fix, in order",{mod:"fixlist",src:"pipeline 12"});
VW("event","decide","models","What models can learn",{kind:"models",s:"crit",mod:"models",nrs:["event-models"],src:"eda/notebooks 09 · pipeline 09 · country 14",blocks:[
 S("The event-grain model register at a glance","",'<div class="vrows" id="evVerdict"></div>'),
 S("Fraud across every attempt","ROC AUC of the fraud models in the order they were built: the leak, the leak removed, the warehouse's point-in-time model out of time, then each country.",FIG("evAucLadder","Dashed: a coin toss.")),
 M("models"),
 S("Validate a detector, not a label","",'<p>The one learned component that ships at the event grain is the unsupervised anomaly ensemble, judged on planted anomalies of known type. Its CI test: a model change that drops recall on any planted type fails the build. Dormant reactivation, missed by every strong detector, gets a dedicated rule.</p><p><button class="btn" type="button" data-route="event-anomaly">Anomaly detection →</button></p>')]});
VW("event","decide","apps","Applications to build",{kind:"build",mod:"apps",src:"pipeline 07–08 · strategy chapter 12"});
VW("event","decide","kpis","Data-trust KPIs",{kind:"kpis",s:"warn",nrs:["event-kpis"],eyebrow:"Event grain · KPIs",sub:"At the event grain the KPIs are controls",
 lede:"Is every record kept, typed, reconciled and inside its rule's tolerance? Each KPI has a definition, a current value and a target.",src:"pipeline 12 · model_risk 01",blocks:[
 KPIS(K("ok","0","unexplained lines in 44,300,180 records")+K("","1,116,831","cell findings in the live lake (3 rules fire)")+K("ok","0","partitions held by the circuit breaker in 3 years")+K("ok","108 / 108","relations identical across rebuilds")+K("ok","107 / 0","data tests run / failed")+K("crit","3 / 26","integrity rules breaching their SLO")),
 S("Integrity rules as SLO gauges","Each bar is a rule's violation rate on the delivered data; the tick is its SLO maximum. Red: the rate breaches a maximum of 0 %.",
  '<div class="ctrl"><div class="seg" role="group" aria-label="Severity" id="ekSev"><button type="button" data-v="" aria-pressed="true">all</button><button type="button" data-v="A" aria-pressed="false">A</button><button type="button" data-v="B" aria-pressed="false">B</button><button type="button" data-v="C" aria-pressed="false">C</button></div><div class="seg" role="group" aria-label="Order" id="ekOrd"><button type="button" data-v="rate" aria-pressed="true">by rate</button><button type="button" data-v="id" aria-pressed="false">by rule</button></div></div>'+FIG("ekGauge","")),
 S("The event-grain KPI register","Business and compliance KPIs computed on events or the marts built from them.",TBL("ekReg",["KPI","definition","#current","target","owner","status"])),
 {html:P("concept",["Concept","Severity A, B, C and the SLO"],'<p><b>A</b>: the row is wrong in a way that changes money, eligibility or a regulatory report. <b>B</b>: incomplete or inconsistent but usable with care. <b>C</b>: a known convention of the source, tracked so a change in its rate is noticed. A baseline of 18.7 % with a maximum of 20 % tolerates the known defect and catches any worsening.</p>')+P("why",["Tips and tricks","Reading a control KPI"],'<ul><li>A KPI at 0 % is good news only if a planted positive makes it fire.</li><li>Read every ratio\'s denominator: a rule over an empty population reports 0 %.</li><li>Zero-tolerance policies stay shared across countries; baselines can be national.</li></ul>')}]});
VW("event","decide","decisions","Decisions",{kind:"decisions",eyebrow:"Event grain · decide",sub:"Thirteen calls the event-grain evidence puts on the table",lede:"Pick an option and add a note. Choices are shared and kept.",blocks:[S("","",DECL("event"))]});

/* ---------------------------------------------------------------- COUNTRY */
VW("country","overview","overview","Three markets, one bank",{kind:"overview",eyebrow:"Country grain · overview",sub:"One code base, three banks: the platform rebuilt market by market",
 lede:"Mexico, Colombia and Argentina share one table, but not one currency, calendar, regulator or consent law. The whole platform ran three more times, each on one country's data alone, then a fourth time with the quarantined backup as the source.",
 nrs:["country-story","grainfacts"],src:"country_{mx,co,ar,all} 01–14 · country_compare 01 · backup_* 01–14 · dataset_compare 01",blocks:[
 S("Three markets","Each card is that country's own run, computed on its data alone.",'<div class="cards" id="csCards"></div>'),
 S("What changes by country, and what does not","",'<div class="two"><div><h4>National: configuration</h4><ul><li><b>Currency and scale</b>: Mexican accounts in dollars, Colombian and Argentine 90 % in pesos (typical amounts 0.09×, 307× and 27× the blend).</li><li><b>Regulation</b>: AML cash lines, complaint deadlines (CONDUSEF, SFC, BCRA), consent law.</li><li><b>Calendar</b>: 11, about 17 and about 20 holidays; fortnightly or monthly paydays.</li><li><b>Rule rates</b>: R17 is a Mexican rule, R18 exists only where pesos do.</li></ul></div><div><h4>Common: the bank\'s behaviour</h4><ul><li><b>Activity</b>: 0.79–0.80 transactions per customer-month everywhere.</li><li><b>The clock</b>: the delivery day (timestamp −6 h) in every market.</li><li><b>Defects</b>: the same generator artefacts at the same rates.</li><li><b>Learnability</b>: identical verdicts on all seven targets.</li></ul></div></div><p class="kicker">Geography changes a baseline, not a policy, and not the behaviour.</p>'),
 GF("country"),
 S("The fourth run: the backup as the source","",'<p>The backup folder, a different dataset, ran through the same template as if delivered as main. It confirms every conclusion it can test, stops 20 months early, lacks two tables, and shows which controls notice.</p><p><button class="btn" type="button" data-route="country-backupmain">If the backup were the source →</button> <button class="btn" type="button" data-route="country-survive">Which conclusions survive →</button></p>'),
 S("Next grain","",'<p class="kicker">Every country behaves the same at the event grain. Does a coarser unit reveal what single events cannot?</p><p><button class="btn primary" type="button" data-route="daily-overview">Open the daily grain →</button></p>')]});
VW("country","data","markets","Markets in the data",{nrs:["country-data"],eyebrow:"Country grain · data",sub:"Customers, transactions and the national context",lede:"How many customers and transactions each market holds, its daily rhythm, and the context every configuration must encode.",src:"country_* 01, 04",blocks:[
 {html:'<div class="kpis" id="cdtKpis"></div>'},
 S("Daily transactions per country","Transactions per business day (timestamp −6 h), by the customer's country. Hover for the day.",
  '<div class="ctrl"><div class="seg" role="group" aria-label="Smoothing" id="dsSmooth"><button type="button" data-v="ma" aria-pressed="true">7-day mean</button><button type="button" data-v="raw" aria-pressed="false">daily</button></div><div class="seg" role="group" aria-label="Countries" id="dsCty"></div></div>'+FIG("dsChart","",' id="dsCap"')),
 S("National context","What each market's configuration must encode. Regulatory figures are for compliance to confirm.",TBL("cdCtx",["topic","Mexico","Colombia","Argentina"]))]});
VW("country","data","cut","How each country was cut",{mod:"countrycut",subs:[0],intro:false,sub:"Customers are the anchor of every join",lede:"Every customer-owned table follows its customer, so each country's joins stay complete inside it.",src:"country_* 01"});
VW("country","findings","contract","The blended contract",{mod:"countrycut",subs:[1],s:"crit",sub:"The contract describes a population that does not exist",lede:"Amounts are recorded in each account's currency, so a bank-wide baseline matches no country and would hold every day of every market.",src:"country_* 03 · country_compare 01"});
VW("country","findings","calendar","The national calendar",{mod:"countrycut",subs:[2],intro:false,sub:"Each country's own calendar, and data that ignores them all",lede:"Weekends move volume by about 39 % in every market; holidays, paydays, month ends and bonus months do nothing measurable.",src:"country_* 04"});
VW("country","findings","rules","National rule rates",{mod:"countrycut",subs:[3],intro:false,s:"warn",sub:"National rates, and a proof that one field is random",lede:"Some rule rates are national by construction; R25 inside each country equals 66.4 % times the country's share of products.",src:"country_* 12"});
VW("country","findings","backupmain","If the backup were the source",{mod:"backupmain",subs:[0,3,4],s:"crit",src:"backup_{all,mx,co,ar} 01–14"});
VW("country","pipeline","config","Configuration, not code",{s:"ok",nrs:["country-pipeline"],eyebrow:"Country grain · pipeline",sub:"One compiled dbt project, three lakes, country-keyed seeds",lede:"Gates per country so one market's failed delivery never blocks another's, and the control the backup run showed was missing.",src:"country_* 03, 12",blocks:[
 S("One code base, three configurations","",'<pre class="mermaid" id="mmCountry">flowchart LR\n  B[("lossless bronze<br/>whole bank")] --> CUT["cut by the customer\'s country<br/>(anonymous events by IP country)"]\n  CUT --> MX[("lake MX")] & CO[("lake CO")] & AR[("lake AR")]\n  SQL["one compiled dbt project<br/>(same SQL text)"] --> MX & CO & AR\n  SEED["country-keyed seeds<br/>contracts · SLOs · AML lines<br/>deadlines · calendars · consent"] --> MX & CO & AR\n  MX --> GM["gate MX"]\n  CO --> GC["gate CO"]\n  AR --> GA["gate AR"]</pre>'),
 S("What is keyed by country","",TBL("cpSeeds",["seed","why","owner"])),
 {html:P("caution",["Caution","A blended baseline holds everything"],'<p>Checked against the bank-wide contract, every transaction day of every country looks like a unit change, and the breaker would hold 1,097 of 1,097 days in each. Re-estimated on each country\'s first 180 days, it holds none. A drift reference must be estimated on a reference window, never on the whole history it judges.</p>',true)+P("why",["Tips and tricks","Analysing one country at a time"],'<ul><li>Cut at bronze and rebuild, rather than filtering a mart: the cut exposes cross-border references a filter hides.</li><li>Generate the country series from one template so the method cannot drift; let the data, not the code, differ.</li><li>Write every finding as a computed sentence, so the same cell states each country\'s facts.</li></ul>')}]});
VW("country","pipeline","controls","What the controls saw",{mod:"backupmain",subs:[1,2],intro:false,s:"warn",sub:"Running the backup as the source: which controls notice",lede:"The same template and compiled SQL on the quarantined folder. Every difference is a property of the data; every silence is a property of the platform.",src:"backup_* 03, 12 · dataset_compare 01"});
VW("country","walk","deep","Country deep dive",{mod:"countrydeep",src:"country_{mx,co,ar} 01–14"});
VW("country","walk","template","The fourteen-stage template",{eyebrow:"Country grain · walkthrough",sub:"The same fourteen notebooks for every market",lede:"Generated from one template, so what differs between countries is the data, never the method.",src:"country_template 01–14",blocks:[
 S("","",NBL([["01","Scope and lake","Cut the lossless bronze by the customer's country; anonymous digital events by IP country."],["02","Bronze to typed silver","The same contracts and parity checks, on one market."],["03","The contract, the circuit breaker and schema evolution","Baselines re-estimated on the country's first 180 days: 0 days held."],["04","Staging, local time and the country calendar","Holidays, paydays and bonus months per country; effects on the delivery-day clock."],["05","Currency, conversion, imputation and the monthly grid","Peso amounts, imputed USD within ±2 %, incomes converted."],["06","Snapshots and the gold core","SCD2 history and the star, per market."],["07","Service marts","Customer 360, inquiries, cards, disputes, CX."]])),
 S("","",NBL([["08","Risk and growth marts","Credit, collections, AML lines in local units, campaigns."],["09","Point-in-time features plus the country calendar","Leak-free features with calendar terms."],["10","Graph and knowledge exports","Per-country graph and GraphRAG exports."],["11","Privacy inputs and serving tables","DP inputs and contracted serving tables."],["12","Integrity rules, country SLOs and the gates","Rule rates per country; SLOs re-based where the rate is national."],["13","Anomalies and change points","Abnormal days, change points, forest vs AML agreement."],["14","Candidate models, out of time","Seven targets with intervals and a one-feature benchmark."]]))]});
VW("country","decide","models","What each country can learn",{kind:"models",mod:"countrymodels",s:"warn",src:"country_* 14"});
VW("country","decide","survive","Which conclusions survive",{mod:"backupmodels",s:"ok",src:"dataset_compare 01"});
VW("country","decide","kpis","Country scorecard",{kind:"kpis",nrs:["country-kpis"],eyebrow:"Country grain · KPIs",sub:"The same measures for each market, side by side",lede:"A national difference shows as a configuration question; a common one as a property of the bank.",src:"country_* 01–14",blocks:[
 S("Scorecard","",TBL("ckTbl",["measure","#Mexico","#Colombia","#Argentina","reading"])),
 S("One rule, three countries","Pick a rule: its rate in each country against the bank-wide baseline.",'<div class="ctrl"><label class="f">rule<select id="ckRule"></select></label></div>'+FIG("ckRuleChart","",' id="ckRuleCap"')),
 {html:P("why",["Tips and tricks","Reading a country against the others"],'<ul><li>Watch what does <em>not</em> change: behaviour, defects and learnability are the bank\'s.</li><li>A different rule rate is a configuration question unless the rule is a zero-tolerance policy.</li><li>Small countries have wider intervals: compare intervals, not point estimates.</li></ul>')}]});
VW("country","decide","decisions","Decisions",{kind:"decisions",eyebrow:"Country grain · decide",sub:"How the platform handles three countries",lede:"Configuration, completeness, the role of the backup and the first model.",blocks:[S("","",DECL("country"))]});

/* ---------------------------------------------------------------- DAILY */
VW("daily","overview","overview","Re-graining up",{kind:"overview",eyebrow:"Daily grain · overview",sub:"The customer-month, the market-day and the campaign cell",
 lede:"A bank decides on a customer this month, a market today, a branch's cash tomorrow, a complaint case, a campaign cell. The star was rebuilt at those grains and each was asked which decision lives there, what is predictable and what to build.",
 nrs:["daily-story","grainfacts"],src:"granularity 01–09 · granularity_time 01–05",blocks:[
 KPIS(K("ok","43 / 43","grain, reconciliation and density checks on 17 aggregates")+K("warn","9 / 60","targets and tests significant after FDR and material (10 survive it)")+K("","c · r<sup>k</sup>","the exposure law behind every customer-grain signal")+K("ok","+22 %","conversions at the same contacts by channel mix [18, 26]")+K("crit","−6 h / −8 h","the clock the days run on, not legal local time")),
 S("The question, notebook by notebook","",'<div class="flow" id="dyFlow"></div>'),
 GF("daily"),
 S("Four answers","",'<div class="cards"><div class="card"><h4>No new behaviour</h4><p class="small">Every process is drawn independently. Aggregating sums independent noise: 49 of 60 targets show no evidence, every early warning has relative risk ≈ 1, no Granger lead survives.</p></div><div class="card"><h4>The exposure law</h4><p class="small">The one customer signal (dormancy, lapse) is arithmetic: k products, dormant with probability c·rᵏ. A retention model must beat that law first.</p></div><div class="card"><h4>Money needs deterministic services</h4><p class="small">Cash per branch (a newsvendor planner), contact capacity (forecast → Erlang), case SLAs (survival with open cases).</p></div><div class="card"><h4>One lever, with a caveat</h4><p class="small">Channel mix converts about 22 % more in a replay. Voice and WhatsApp record no opens, so their zero is a tracking gap; no holdout exists, so the gain is correlational.</p></div></div>'),
 S("Next grain","",'<p class="kicker">The clock that fixed the day also opened the hour. Does the hour carry anything, and if not, what would the data have to collect?</p><p><button class="btn primary" type="button" data-route="hourly-overview">Open the hourly grain →</button></p>')]});
VW("daily","data","star","The aggregate star",{mod:"granularity",subs:[0],s:"ok",src:"granularity 01"});
VW("daily","data","series","The daily series",{nrs:["daily-data"],eyebrow:"Daily grain · data",sub:"The raw material of every day-grain model",lede:"The weekly rhythm (weekends about 39 % lower) is the only calendar effect the generator put in.",src:"granularity 04",blocks:[
 S("Daily volume","",'<div class="ctrl"><div class="seg" role="group" aria-label="Series" id="ddSeries"><button type="button" data-v="tx" aria-pressed="true">transactions by country</button><button type="button" data-v="ct" aria-pressed="false">contacts, bank-wide</button></div><div class="seg" role="group" aria-label="Smoothing" id="ddSmooth"><button type="button" data-v="ma" aria-pressed="true">7-day mean</button><button type="button" data-v="raw" aria-pressed="false">daily</button></div></div>'+FIG("ddChart","",' id="ddCap"')),
 S("The week","Average per business day of the week, transactions, whole bank.",FIG("ddWeek","")),
 {html:P("why",["Tips and tricks","Before modelling a day series"],'<ul><li>Exclude the two partial edge months (June 2023, May 2026) from trends and seasonality.</li><li>Date every process by its delivery day, never by UTC or legal local time.</li><li>A co-movement across days is a hypothesis about units: test it within units after removing the weekday.</li></ul>')}]});
VW("daily","data","clock","Which clock a day runs on",{mod:"clockcells",subs:[0,1],s:"crit",sub:"In which time were the data's days drawn?",lede:"Shift every timestamp and find the clock on which hour and weekday are independent: the delivery day, −6 h or −8 h, the same in every market.",src:"granularity_time 01"});
VW("daily","findings","exposure","Exposure, not behaviour",{mod:"granularity",subs:[2,3],intro:false,s:"warn",sub:"Where the one customer-grain signal comes from",lede:"Dormancy follows the number of products held, and aggregate co-movement is not customer behaviour.",src:"granularity 02–04"});
VW("daily","findings","campaigns","Campaigns and cash",{mod:"granularitybuild",subs:[0,1],s:"ok",src:"granularity 05, 08"});
VW("daily","findings","retention","Retention and survival",{nrs:["daily-findings"],mods:["granularitybuild"],eyebrow:"Daily grain · findings",sub:"Dormancy is a revolving door; open cases are the slow ones",lede:"Monthly states as a Markov chain, and survival curves that keep the customers and cases that have not finished yet.",src:"granularity 02–03, 06",blocks:[
 M("granularitybuild",{subs:[2],intro:false}),
 S("Lapse by country and segment","",TBL("dfSurvC",["group","value","#customers","#lapsed","#median months","#S(12)","#log-rank p"])),
 S("Complaint resolution","",TBL("dfSurvK",["group","value","#cases","#resolved","#P(≤ 30 d)","#naive mean"])),
 {html:P("caution",["Caution","Open cases are the slow ones"],'<p>Only about 23 % of complaint cases are resolved; the Kaplan–Meier median is never reached. Averaging the resolved cases gives about 15.5 days and describes nothing. Report the survival curve and P(resolved within the deadline), per market clock.</p>',true)}]});
VW("daily","findings","earlywarn","Early warnings and agent KPIs",{s:"crit",nrs:["daily-findings"],eyebrow:"Daily grain · findings",sub:"Cross-process links, leads and agent rankings: all noise",lede:"For each pair, the chance of B next month when A happened against when it did not; leads between daily series; and whether agent KPIs agree with themselves.",src:"granularity 02, 04, 06",blocks:[
 S("Cross-process early warnings","A relative risk of 1 is no link; every interval contains it.",FIG("dfLifts","")),
 S("The early-warning table","",TBL("dfLiftTbl",["signal","#months with A","#P(B | A)","#P(B | not A)","#relative risk","business use"])),
 S("Agent KPI reliability","",TBL("dfAgent",["KPI","#agents","#split-half r","#Spearman–Brown","#ICC"])),
 S("Granger leads between processes","",TBL("dfGranger",["market","cause → effect","#lag (days)","#p","FDR 5 %"])),
 {html:P("concept",["Concept","Split-half reliability"],'<p>A KPI that ranks agents must agree with itself between odd and even months. The Spearman–Brown formula scales that correlation to the full period. Near 0 means the ranking is noise: coaching on it rewards luck, and agent KPIs are employee personal data.</p>')+P("why",["Tips and tricks","Testing a link the cheap way"],'<ul><li>Compare P(B | A) with P(B | not A) on the same months before building a journey model.</li><li>A Granger lead is a lead, not a cause; control the false-discovery rate across every pair.</li></ul>')}]});
VW("daily","findings","cell","The campaign cell",{mod:"clockcells",subs:[3],intro:false,s:"warn",sub:"What a conversion measures",lede:"Channel × product × objective × segment × market × month: the unit at which marketing spends.",src:"granularity_time 04"});
VW("daily","pipeline","promote","What to promote",{mod:"granularitybuild",subs:[5],intro:false,s:"ok",sub:"Six aggregates serve a named decision; two wait; one never earns a table",lede:"Each promoted aggregate gets a grain contract and the three test families.",src:"granularity 09"});
VW("daily","pipeline","clocks","The declared clocks",{nrs:["daily-pipeline"],s:"ok",eyebrow:"Daily grain · pipeline",sub:"ADR-014 in the platform",lede:"Each process's day is its timestamp shifted by a declared offset, the same in Mexico, Colombia and Argentina.",src:"granularity_time 01 · ADR-014",blocks:[
 S("What changes, process by process","",TBL("dpClock",["process","declared offset","what changes in the platform","control"])),
 {html:P("concept",["Concept","Three test families for every aggregate"],'<ul><li><b>Unique grain</b>: one row per declared key.</li><li><b>Exact reconciliation</b>: every additive measure sums back to its atomic fact (DECIMAL arithmetic).</li><li><b>Dense completeness</b>: every unit has a row for every period, zeros included.</li></ul><p>All 43 pass on the series I aggregates; 44 of 44 on the hour star.</p>',true)}]});
VW("daily","walk","series1","Series I notebooks",{eyebrow:"Daily grain · walkthrough",sub:"granularity 01–09: the star re-grained to the units a bank decides on",lede:"Each notebook's question and its result.",src:"eda/notebooks/granularity",blocks:[
 S("Notebooks 01–05","",NBL([["01","Grain design and the aggregate star","17 aggregate models over gold; dense where time matters, additive measures only, a 96-band behaviour mini-dimension.","43 of 43 grain, reconciliation and density checks pass."],
  ["02","Customer × month","Engagement, retention and cost to serve.","Next-month dormancy AUC 0.68 (weak); 90-day 0.73. Dormancy follows c·rᵏ; a dormant month returns to activity more often than it stays dormant."],
  ["03","The customer over a lifetime","Value concentration and when attrition starts.","About 69 % lapse at least once; median 11–12 months to the first 90-day lapse in every country."],
  ["04","Market × day and channel × day","Capacity, liquidity and monitoring.","Calendar regression beats seasonal naive on transactions and outflows (MASE 0.67–0.80); errors and contacts co-move across days, not within units."],
  ["05","Branch × day: cash logistics","How much cash to load per branch per day.","Branch forecasts beat seasonal naive (median MASE 0.77); summing branch medians misses the market total by 6.9×; a newsvendor buffer lowers cost."]])),
 S("Notebooks 06–09","",NBL([["06","The contact centre: agent × day and the case","Staffing, coaching and SLA compliance.","Every agent KPI has reliability ≈ 0. About 23 % of cases are resolved; the survival median is not reached."],
  ["07","Product × month","Portfolio, vintages and early credit signs.","No evidence for product dormancy or delinquency: days past due exists only as today's snapshot."],
  ["08","Category × month and campaign × day","Spend mix, campaign economics, contact fatigue.","The category mix never shifts (PSI ≤ 0.0005); campaigns differ and are rankable before launch; no fatigue."],
  ["09","Synthesis","Which grain earns a model, an agent or a KPI.","60 targets and tests; 10 survive FDR, 9 of them material; an 18-KPI catalogue; 9 stakeholder opportunities; six aggregates to promote."]]))]});
VW("daily","walk","series2","Series II notebooks",{eyebrow:"Daily grain · walkthrough",sub:"granularity_time 01–05: the clock and the campaign decision cell",lede:"Each notebook's question and its result.",src:"eda/notebooks/granularity_time",blocks:[
 S("","",NBL([["01","The clock","In which time were the data's days drawn?","Delivery day: −6 h (transactions, digital, sends), −8 h (contacts, complaints), the same in every market; χ²/dof ≈ 1 there against ≈ 19 at legal local time."],
  ["02","The hour grain","Is the hour worth a fact table?","Hours split each day uniformly (dispersion 0.98–1.02); the best hourly forecast is the daily one divided by 24: a monitor, not a table."],
  ["03","Sequences and bursts","Does any event lead another within the hour?","No: symmetric windows of 1–72 h give after ÷ before ≈ 1 for every pair."]])),
 S("","",NBL([["04","The campaign decision cell","What does a conversion measure?","1,248 cells; conversion per open ≈ 2 % on every tracked channel; Voice and WhatsApp record no opens; within a channel no cell differs after shrinkage."],
  ["05","Allocation and synthesis","Reallocate contacts at a fixed number of sends.","+22 % conversions [18, 26] by channel mix against +0.2 % for a random reallocation; a 10 % uplift needs about 231 k customers per arm."]]))]});
VW("daily","walk","signal","The signal table",{mod:"granularity",subs:[1],intro:false,sub:"Every target and test, under false-discovery control",lede:"Sixty rows across the grains, p-values adjusted by Benjamini–Hochberg. A result is actionable only when it survives and is material.",src:"granularity 09"});
VW("daily","decide","models","What the day can learn",{kind:"models",s:"warn",nrs:["daily-models"],eyebrow:"Daily grain · decide",sub:"Forecasts that beat seasonal naive, nothing about individual behaviour",lede:"Sixty targets by grain, and out-of-time forecast skill per market and series.",src:"granularity 02–09",blocks:[
 S("Sixty targets by grain","Coloured by verdict.",FIG("dmGrain","")),
 S("Forecast skill per market and series","MASE on the out-of-time test year; the dashed line is MASE 1. Compare each model with the grey seasonal-naive bar of its series; green marks the best model when a Diebold–Mariano test says it beats seasonal naive (p < 0.05).",
  '<div class="ctrl"><div class="seg" role="group" aria-label="Market" id="fcMkt"><button type="button" data-v="MX" aria-pressed="true">Mexico</button><button type="button" data-v="CO" aria-pressed="false">Colombia</button><button type="button" data-v="AR" aria-pressed="false">Argentina</button></div></div>'+FIG("fcChart","",' id="fcCap"')),
 {html:P("caution",["Caution","Interval coverage"],'<p>The calendar regression\'s nominal 80 % intervals cover 65–90 % of test days depending on the series. Before a forecast feeds staffing or cash, calibrate its intervals on recent weeks, or the buffer it implies is wrong.</p>',true)+P("formodels",["For models","What to build at the day grain"],'<ul><li>Market-day forecasts with calendar terms for operations and cash, monitored by MASE against seasonal naive.</li><li>A transparent lapse-risk ranking (the exposure law first).</li><li>Campaign ranking before launch from launch attributes.</li><li>Nothing per customer-day: the sequence is not there.</li></ul>')}]});
VW("daily","decide","allocation","Allocation and the cell explorer",{s:"ok",nrs:["daily-models"],mods:["clockcells"],eyebrow:"Daily grain · decide",sub:"The one model with money attached",lede:"Empirical-Bayes cell rates replayed on the held-out year at the same number of contacts, and every cell to explore.",src:"granularity_time 04–05",blocks:[
 M("clockcells",{subs:[4],intro:false}),
 S("Campaign cell explorer","Raw cell rates spread widely; empirical-Bayes rates are pulled into a narrow band around their channel's rate, because cells barely differ within a channel.",
  '<div class="ctrl"><label class="f">channel<select id="ceCh"></select></label><label class="f">objective<select id="ceObj"></select></label><label class="f">market<select id="ceMkt"></select></label><label class="f">min sends<input type="number" id="ceMin" value="200" min="0" step="50"></label></div>'+FIG("ceScatter","",' id="ceCap"')),
 S("Largest cells","",TBL("ceTbl",["channel","product","objective","segment","mkt","#sends","#conv.","#raw rate","#EB rate","#value per send (USD)"]))]});
VW("daily","decide","build","What each grain should build",{kind:"build",mod:"granularitybuild",subs:[3],intro:false,sub:"Opportunities by stakeholder",lede:"Per decision owner: the solution, the agent that explains it, and whether to build now.",src:"granularity 09"});
VW("daily","decide","kpis","KPI catalogue",{kind:"kpis",mod:"granularitybuild",subs:[4],intro:false,s:"ok",sub:"Eighteen KPIs, each a ratio of sums on its grain",lede:"With an owner, its current value and the rule that raises an alert.",src:"granularity 09"});
VW("daily","decide","decisions","Decisions",{kind:"decisions",eyebrow:"Daily grain · decide",sub:"Aggregates, channels, contact allocation and monitors",lede:"Pick an option and add a note.",blocks:[S("","",DECL("daily"))]});

/* ---------------------------------------------------------------- HOURLY */
VW("hourly","overview","overview","The bank at the hour",{kind:"overview",mod:"hourbank",subs:[],eyebrow:"Hourly grain · overview",nrs:["hourly-story","grainfacts"],src:"granularity_hour 01–09",
 blocks:[M("hourbank",{subs:[]}),
 S("The direction","",'<p class="kicker">Replicate the whole process even where the synthetic generator leaves no signal. A documented set of non-trainable models is a result: each red gate names its root cause, the owner who must collect the missing data, and the test that proves a new feed delivers it.</p><p>The hour is where staffing, branch hours, send times and intraday fraud velocity live in a real bank. The same star, the same gates and one re-run command turn green as soon as real feeds arrive.</p>'),
 S("Nine notebooks","",'<div class="flow" id="hyFlow"></div>'),
 GF("hourly"),
 S("What the hour adds on this data","",'<div class="cards"><div class="card"><h4>No behavioural signal</h4><p class="small">No customer has a preferred hour, no channel has a rhythm, events inside a session come in random order, send-to-open delays are uniform over seven days.</p></div><div class="card"><h4>Validity controls</h4><p class="small">Only the hour can check opening hours, shifts and clocks, and all three fail.</p></div><div class="card"><h4>Operational clocks</h4><p class="small">Complaint assignment takes 3–22 h and first response 17–58 h (p10–p90); deadlines run in business hours.</p></div><div class="card"><h4>Streaming monitors</h4><p class="small">Hourly counts per market and channel with negative-binomial limits: a monitor, not a warehouse table.</p></div></div>')]});
VW("hourly","data","star","The hour star",{s:"ok",nrs:["hourly-data"],mods:["hourbank"],eyebrow:"Hourly grain · data",sub:"Five dimensions the hour needs and eight facts at the grain each process supports",lede:"44 of 44 grain, reconciliation and density checks, and a sparsity test that says which entity × hour grains are viable.",src:"granularity_hour 01",blocks:[
 S("Dimensions and facts","",TBL("hdStar",["model","Kimball type","grain","decision it serves","#checks"])),
 M("hourbank",{subs:[0],intro:false})]});
VW("hourly","data","clock","Clocks and flat hours",{s:"crit",nrs:["hourly-data"],eyebrow:"Hourly grain · data",sub:"Each process on its own clock, and nothing inside the day",lede:"On the delivery clock the weekend is a clean block of whole days; inside a day every hour carries the same volume.",src:"granularity_time 01–02 · granularity_hour 01",blocks:[
 S("Hour × weekday, on the right clock and the wrong one","On raw UTC the weekend boundary cuts through the hours, so six hours of every Saturday look like Friday.",
  '<div class="ctrl"><div class="seg" role="group" aria-label="Process" id="hwProc"><button type="button" data-v="transactions" aria-pressed="true">transactions (−6 h)</button><button type="button" data-v="call_center_interactions" aria-pressed="false">contacts (−8 h)</button></div><div class="seg" role="group" aria-label="Clock" id="hwClock"><button type="button" data-v="biz" aria-pressed="true">delivery clock</button><button type="button" data-v="raw" aria-pressed="false">raw UTC</button></div></div>'+FIG("hwHeat","",' id="hwCap"')),
 S("Every process, hour by hour","Events per hour of the delivery clock as an index of the process's own hourly mean (1.00 = flat).",FIG("hpChart","")),
 {html:P("concept",["Concept","How a clock is measured from the data alone"],'<p>If a process was generated with a weekly rhythm on some clock, its hour × weekday table is independent only on that clock. Shift every timestamp by −12…+12 hours and the χ² of independence per degree of freedom falls to about 1 at the generator\'s clock; there, every row\'s shifted date equals its <code>process_date</code>.</p>',true)+P("formodels",["For models","No time-of-day features"],'<p>Hour-of-day, daypart and "night transaction" features carry nothing here. Keep them in the design for real data; never judge them on this source.</p>')}]});
VW("hourly","findings","teller","Teller hours",{s:"crit",nrs:["hourly-findings"],eyebrow:"Hourly grain · findings · notebook 04",sub:"Activity that ignores the branch schedule",lede:"Teller (Branch-channel) transactions per hour of the delivery clock, Monday to Friday, against the share of branches open at that hour.",src:"granularity_hour 04",blocks:[
 S("Teller transactions and open branches","Bars: teller transactions per hour (left axis). Line: share of the 350 branches open (right axis).",FIG("hfTeller","")),
 S("The tests","",TBL("hfTellerTbl",["test","#observed","#p","reading"])),
 {html:P("caution",["Caution","Two readings of the schedule"],'<p>If branches open only Monday to Friday, 67.2 % of teller transactions fall outside opening hours against 70.8 % expected if hours were ignored; that small gap comes from the lower weekend volume. If branches open every day with their posted hours, 59.3 % fall outside against 59.2 % expected: no effect at all.</p>',true)+P("formodels",["For the next stages","A control, not a model"],'<p>In a real bank a teller transaction while the branch is closed is a fraud or data-quality alert. Promote it as a severity-B rule with today\'s baseline, and collect opening days and holiday closures per branch.</p>')}]});
VW("hourly","findings","shift","Agent shifts",{s:"crit",nrs:["hourly-findings"],eyebrow:"Hourly grain · findings · notebook 05",sub:"A shift label unrelated to the work",lede:"Contacts per hour of the delivery clock (−8 h) as a share of each shift's total. Shaded: the hours of the declared shift.",src:"granularity_hour 05",blocks:[
 S("Contacts by hour, per declared shift","",'<div class="ctrl"><div class="seg" role="group" aria-label="Shift" id="hsShift"></div></div>'+FIG("hfShift","",' id="hfShiftCap"')),
 S("The tests","",TBL("hfShiftTbl",["test","#inside the shift","#p","reading"])),
 {html:P("concept",["Concept","Erlang C and why it needs rosters"],'<p>Erlang C turns arrivals per interval and handle time into the agents needed for a service level. Comparing it with the agents actually rostered needs rosters and agent state logs (available, on break, in call). Here an agent is "active" only when a contact arrives, so active agents follow demand mechanically.</p>')+P("why",["Tips and tricks","Shift adherence"],'<p>Adherence = contacts inside the rostered hours / contacts. Today it is 33 %, exactly the shift\'s share of the day. The target with real rosters is ≥ 95 %.</p>')}]});
VW("hourly","findings","case","The case clock",{s:"crit",nrs:["hourly-findings"],eyebrow:"Hourly grain · findings · notebook 06",sub:"A breach flag that ignores the deadline",lede:"Complaint milestones in hours, and the bank's SLA flag against the regulatory business-day clock.",src:"granularity_hour 06",blocks:[
 S("SLA flag by days to resolution","A flag that followed any deadline would jump at it; this one is flat at about 20 %.",FIG("hfSla","")),
 S("Hours to assignment and first response","p10, quartiles and p90.",FIG("hfMile","")),
 S("The tests","",TBL("hfCaseTbl",["test","#statistic","#p","reading"])),
 {html:P("concept",["Concept","Cohen's κ"],'<p>Agreement between two classifications beyond chance: 1 is perfect, 0 is what chance gives. The flag against the recomputed regulatory breach scores about 0 in Mexico, Colombia and Argentina, so the flag cannot be reported to a regulator.</p>',true)+P("formodels",["For the next stages","Recompute the breach"],'<p>Promote <code>fct_case_clock</code>: business hours per country calendar, a deadline seed per country and case type, and the breach recomputed from the clock. The KPI is deterministic and reportable without any model.</p>')}]});
VW("hourly","findings","rhythm","No rhythm anywhere",{s:"crit",nrs:["hourly-findings"],eyebrow:"Hourly grain · findings · notebooks 02, 03, 07",sub:"Sessions, sends, customers and channels",lede:"Uniform send-to-open delays, random event order inside sessions, no preferred hours, and 24 flat market × channel series.",src:"granularity_hour 02, 03, 07",blocks:[
 S("Send-to-open delay","6-hour bins over the first seven days: uniform. No send hour can be better than another.",FIG("hfDelay","")),
 S("Behavioural tests","",TBL("hfBehav",["scenario","test","#statistic","#p","reading"])),
 S("Market × channel hours","χ² against flat. None rejects.",TBL("hfChan",["series","#χ²","#p","#effect","reading"])),
 {html:P("why",["Tips and tricks","Testing for a rhythm"],'<ul><li>Test each series against flat with a χ² on its hour counts, then control the false-discovery rate across series.</li><li>With millions of events, report the effect size: a significant 0.4 % shift is not a rhythm.</li><li>Send-time optimisation needs randomised send times, not observational ones.</li></ul>')}]});
VW("hourly","findings","sequences","Sequences and bursts",{mod:"clockcells",subs:[2],intro:false,sub:"Does any event lead another?",lede:"Symmetric windows of 1 to 72 hours, the same customer on both sides.",src:"granularity_time 03"});
VW("hourly","pipeline","promote","What to promote",{mod:"hourbank",subs:[3],intro:false,s:"ok",sub:"Each hour-star model and its platform decision",lede:"Clocks and schedules to the warehouse, volumes to streaming, every hour model out of production until its gate turns green.",src:"granularity_hour 09"});
VW("hourly","pipeline","monitors","Hourly monitors",{s:"ok",nrs:["hourly-pipeline"],eyebrow:"Hourly grain · pipeline",sub:"Poisson or negative binomial",lede:"An hourly count varies around the day's level, and the level itself varies (about 11 % beyond Poisson here). Limits that ignore the second raise alarms on normal hours.",src:"granularity_time 02",blocks:[
 S("False-alarm rate of an hourly monitor","Set the expected events per hour and the day-level variation; compare Poisson limits with negative-binomial ones under the same truth.",
  '<div class="calc" id="calcNb"><div class="row"><label class="f">expected events per hour<input type="number" id="nbMu" value="56" min="1" max="5000"></label><label class="f">day-level variation (CV, %)<input type="number" id="nbCv" value="11" min="0" max="60" step="1"></label><label class="f">target alarm rate (%)<input type="number" id="nbA" value="0.1" min="0.001" max="10" step="0.01"></label></div><div class="out" id="nbOut"></div></div>'),
 {html:P("concept",["Concept","Why the negative binomial"],'<p>If each hour is Poisson with a mean that varies from day to day (a gamma-distributed level), the count is negative binomial with variance μ + (CV·μ)². At small μ both limits agree; at large μ the level variation dominates and Poisson limits become far too narrow. 56 events is the average market-hour; a market × channel hour averages about 9.</p>',true)}]});
VW("hourly","pipeline","loop","The re-evaluation loop",{s:"ok",eyebrow:"Hourly grain · pipeline",sub:"Readiness as a pipeline step",lede:"A new feed lands, its acceptance test runs, the scorecard re-runs, and a green gate opens the model path.",src:"scripts/readiness_check.py · strategy chapter 13",blocks:[
 S("","",'<pre class="mermaid" id="mmLoop">flowchart LR\n  R["data requirement<br/>(owner, acceptance test)"] --> F["new feed lands in bronze<br/>under its contract"]\n  F --> A["acceptance test on<br/>the first weeks"]\n  A --> S["readiness_check.py<br/>--dataset main --scope ALL"]\n  S -->|green| G["ADR-012 model path:<br/>build, validate, monitor"]\n  S -->|amber or red| R</pre>'),
 S("The command","",'<p><code>uv run scripts/readiness_check.py --dataset main --scope ALL</code> reproduces the notebook\'s scorecard byte for byte on the same data and writes <code>data/derived/readiness/</code>. The share of green gates is a data-office KPI.</p>')]});
VW("hourly","walk","notebooks","Nine notebooks",{eyebrow:"Hourly grain · walkthrough",sub:"granularity_hour 01–09",lede:"Each notebook re-grains one family of facts to the hour, tests whether the hour carries anything, and trains its candidate models whatever the answer.",src:"eda/notebooks/granularity_hour",blocks:[
 S("Notebooks 01–05","",NBL([["01","Grain design and the hour star","13 models (5 dimensions, 8 facts) on the delivery clocks.","44 of 44 checks; market × hour viable (99.99 % occupied), branch × hour 13.9 %, agent × hour 2.1 %, customer × hour 0.11 %."],
  ["02","The customer at the hour","Preferred hours, daypart profiles, dormancy from the profile.","1.05 % of 64,531 customers reject flat hours at 1 % (chance: 1 %). Both models red."],
  ["03","Market and channel at the hour","Hour-of-day mix, dispersion, hourly forecasts.","All 24 series flat. The Poisson GLM (MASE 0.748) loses to the weekday mean / 24 (0.737). Red."],
  ["04","The branch hour","Activity against the branch schedule; ATM cash.","59.3 % of teller transactions outside opening hours vs 59.2 % expected. Red (one data defect)."],
  ["05","The agent hour and the queue","Shift adherence, occupancy, Erlang C.","Shift labels unrelated to the hours worked. Handle time amber; arrivals red."]])),
 S("Notebooks 06–09","",NBL([["06","The case clock","Milestones in hours and business hours; the SLA flag.","SLA flag κ ≈ 0 in all three countries; priority does not speed the first response (log-rank p 0.30). Both models red."],
  ["07","The session and the send response","Session funnel, error impact, send-to-open delays.","Inner events in random order; delays uniform over 7 days. Purchase model amber, send-hour model red."],
  ["08","Data readiness and the collection audit","Every model's gate, root cause and requirement.","0 green, 2 amber, 9 red: 8 generator independence, 1 data defect."],
  ["09","Synthesis","Signal table, KPIs, promotion.","52 tests; 9 survive Benjamini–Hochberg; 1 is material, and it is mechanical."]]))]});
VW("hourly","walk","signal","The signal table",{nrs:["hourly-walk"],eyebrow:"Hourly grain · walkthrough · notebook 09",sub:"52 tests under one false-discovery budget",lede:"A row is a signal only when it survives the false-discovery control and is material.",src:"granularity_hour 09",blocks:[
 S("","",'<div class="ctrl"><div class="seg" role="group" aria-label="Filter" id="hsFilter"><button type="button" data-v="reject" aria-pressed="true">survive FDR</button><button type="button" data-v="all" aria-pressed="false">all 52</button></div></div>'+TBL("hsTbl",["scenario","test","#p","#q","material","reading"])),
 {html:P("concept",["Concept","Benjamini–Hochberg"],'<p>Rank the p-values; the k-th smallest survives if p ≤ k/m · q. It controls the expected share of false discoveries among the survivors, the right error rate when dozens of tests run at once.</p>',true)}]});
VW("hourly","decide","models","What the hour can learn",{kind:"models",s:"crit",nrs:["hourly-models"],mods:["hourbank"],eyebrow:"Hourly grain · decide",sub:"Eleven models, executed and gated",lede:"Each model trained out of time against a transparent benchmark, its gain bootstrapped, one rule turning the interval into green, amber or red.",src:"granularity_hour 08",blocks:[
 S("Gain against materiality","Each model's out-of-time gain divided by its materiality threshold, with the bootstrap 95 % interval. Green needs the whole interval above 0 and the point at or past 1.",FIG("hmGate","")),
 M("hourbank",{subs:[1],intro:false})]});
VW("hourly","decide","gate","Try the readiness gate",{nrs:["hourly-models"],eyebrow:"Hourly grain · decide",sub:"The verdict rule, interactive",lede:"Load any model or type your own evaluation. A red gate with an undetectable material effect is insufficient volume.",src:"granularity.readiness_verdict",blocks:[
 S("Readiness verdict","",'<div class="calc" id="calcGate"><div class="row"><label class="f">load a model<select id="gtLoad"></select></label></div><div class="row" style="margin-top:.6rem"><label class="f">gain<input type="number" id="gtD" step="0.0001"></label><label class="f">95 % low<input type="number" id="gtLo" step="0.0001"></label><label class="f">95 % high<input type="number" id="gtHi" step="0.0001"></label><label class="f">material<input type="number" id="gtM" step="0.001"></label><label class="f">folds agree<select id="gtF"><option value="1">yes</option><option value="0">no</option></select></label></div><div class="out" id="gtOut"></div></div>'),
 {html:P("concept",["Concept","MDE: the minimum detectable effect"],'<p>With a bootstrap standard error SE, a two-sided 5 % test with 80 % power detects effects of about 2.8 · SE. When 2.8 · SE exceeds the materiality threshold, even a material gain would be invisible: the verdict is insufficient volume, and the fix is more data, not a better model.</p>',true)}]});
VW("hourly","decide","audit","The data-collection audit",{kind:"build",mod:"hourbank",subs:[2],intro:false,s:"warn",sub:"An owner and an acceptance test for every red gate",lede:"Per model: who owns the missing data, what must be collected, and the test that proves a new feed delivers it.",src:"strategy chapter 13"});
VW("hourly","decide","kpis","Hour KPIs",{kind:"kpis",nrs:["hourly-kpis"],eyebrow:"Hourly grain · decide",sub:"Deterministic, owned, mostly waiting for data",lede:"Eleven KPIs that need no model. Four can run today; the rest need rosters, agent state logs or a business-hours calendar.",src:"granularity_hour 09",blocks:[S("","",TBL("hkTbl",["KPI","definition","grain","owner","target","kind"]))]});
VW("hourly","decide","decisions","Decisions",{kind:"decisions",eyebrow:"Hourly grain · decide",sub:"Hour models, hour controls and monitor limits",lede:"Pick an option and add a note.",blocks:[S("","",DECL("hourly"))]});

/* ---------------------------------------------------------------- globals */
PAGES.mission={global:true,title:"Mission control",eyebrow:"Mission control · Factored AI & Data Hackathon 2026 · synthetic LATAM retail bank",
 sub:"Four grains, one bank: what the data can carry at each resolution",
 lede:"The same 23.5 million source records read four ways: as delivered, cut by market, rolled up to the day and the campaign cell, and re-grained to the hour. Each grain has the same six groups of views, from its overview to its decisions.",
 mods:["overview"],nrs:["mission"],blocks:[
 {html:'<div class="kpis" id="msKpis"></div>'},
 S("The atlas map","Every view of every grain. The dot is the view's verdict: green works on this data, amber partial, red blocked.",'<div class="gm" id="gmGrid"></div>'),
 S("What a model can learn at each grain","Click a bar to open that grain's models view.",'<div class="vrows" id="msVerdicts"></div>'),
 S("The story across grains","",'<ol class="tline" id="msTimeline"></ol>'),
 S("The verdict: what the current data supports","",'<div class="tbl"><table class="matrix" id="verdictTbl"><thead><tr><th>capability</th><th>status now</th><th>why</th><th>what unblocks it</th></tr></thead><tbody></tbody></table></div>'),
 S("Your decisions","Choices are shared with everyone who opens this atlas.",'<div id="decSummary" class="banner">Loading the decision board…</div><p><button class="btn primary" type="button" data-route="board">Open the decision board →</button></p>'),
 {html:P("why",["Why it matters","The one-sentence strategy"],'<p><strong>Build the platform, controls and contracts that make learning possible, and ship only the use cases that are deterministic over trusted marts.</strong> Re-graining confirmed it from every angle: the event grain found leaking labels and missing keys, the country grain national configuration but one behaviour, the daily grain forecastable aggregates and one campaign lever, the hourly grain an owned list of data requirements.</p>',true)+
  P("why",["Tips and tricks","Driving the atlas"],'<ul><li>The grain tabs keep the view you are on: open <b>What models can learn</b>, then switch grain.</li><li><kbd>1</kbd>–<kbd>4</kbd> switch grain, <kbd>[</kbd> <kbd>]</kbd> previous and next view, <kbd>,</kbd> <kbd>.</kbd> the same view in another grain.</li><li><kbd>⌘K</kbd> or <kbd>/</kbd> searches views, sections, terms, decisions and notebooks.</li><li><b>Notes</b> on the right of each view filter by kind: concept, for models, tips, caution.</li></ul>',true)}]};
PAGES.board={global:true,title:"Decision board",eyebrow:"All grains · your call",sub:"Every open decision across the four grains",lede:"Each with its evidence, the options and a recommendation. Choices and notes are shared with everyone who opens this atlas, and Claude can read them in a later session.",
 blocks:[{html:'<section class="blk"><div id="decMode" class="banner">Connecting…</div><div class="ctrl"><div class="seg" role="group" aria-label="Grain filter" id="bdFilter"><button type="button" data-v="all" aria-pressed="true">all grains</button><button type="button" data-v="event" aria-pressed="false">event</button><button type="button" data-v="country" aria-pressed="false">country</button><button type="button" data-v="daily" aria-pressed="false">daily</button><button type="button" data-v="hourly" aria-pressed="false">hourly</button><button type="button" data-v="open" aria-pressed="false">still open</button></div></div><div class="declist" data-declist="board"></div></section>'}]};
PAGES.notebooks={global:true,title:"Notebook index",eyebrow:"All grains · eda/notebooks",sub:"Every notebook series of the exploratory phase",lede:"What each series asked, and the view of this atlas where its results are told.",nrs:["notebooks"],blocks:[{html:'<div id="nbIndex"></div>'}]};
PAGES.glossary={global:true,title:"Glossary",eyebrow:"All grains · reference",sub:"Every term in plain words",lede:"",mods:["gloss"],blocks:[S("","",'<label class="f" style="max-width:360px">filter<input type="search" id="glFilter" placeholder="e.g. AUC, SCD2, Erlang, MDE"></label><dl class="gloss" id="glList"></dl>')]};
