-- daily_exchange_rates from lossless bronze, typed against platform/contracts/sources/daily_exchange_rates.yml
-- (contract bc6a5070f4a4). Generated by scripts/generate_silver_from_contracts.py: do not edit, change the contract and regenerate.
-- '' and absent fields become NULL; a value that does not cast becomes NULL and is listed in _dq_issues
-- as '<column>:<code>' (see audit.dq_cell_findings). Every bronze record is kept, flagged or not.
-- Approved corrections (dq_corrections_active, four-eyes) are overlaid on the text before typing; _dq_issues
-- stays computed on the original text (what the source sent) and _corrected_columns lists what the overlay changed.
with c as (
    select source_file, record_no,
           map_from_entries(list(struct_pack(k := column_name, v := new_value) ORDER BY column_name)) AS m
    from {{ ref('dq_corrections_active') }}
    where zone = 'bronze' and table_name = 'daily_exchange_rates'
    group by all
),
o as (
    select r.*, list_filter([
        CASE WHEN r._parse_status <> 'ok' THEN '*:G' END,
        CASE WHEN coalesce(r."date", '') = '' THEN 'date:N' END,
        CASE WHEN r."date" <> '' AND try_cast(r."date" AS DATE) IS NULL THEN 'date:T' END,
        CASE WHEN r."date" <> '' AND NOT regexp_full_match(r."date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2})') AND try_cast(r."date" AS DATE) IS NOT NULL THEN 'date:F' END,
        CASE WHEN coalesce(r."source_currency", '') = '' THEN 'source_currency:N' END,
        CASE WHEN r."source_currency" <> '' AND r."source_currency" NOT IN ('ARS', 'COP', 'MXN', 'USD') THEN 'source_currency:V1' END,
        CASE WHEN coalesce(r."target_currency", '') = '' THEN 'target_currency:N' END,
        CASE WHEN r."target_currency" <> '' AND r."target_currency" NOT IN ('ARS', 'COP', 'MXN', 'USD') THEN 'target_currency:V1' END,
        CASE WHEN coalesce(r."exchange_rate", '') = '' THEN 'exchange_rate:N' END,
        CASE WHEN r."exchange_rate" <> '' AND try_cast(r."exchange_rate" AS DOUBLE) IS NULL THEN 'exchange_rate:T' END,
        CASE WHEN r."exchange_rate" <> '' AND NOT regexp_full_match(r."exchange_rate", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."exchange_rate" AS DOUBLE) IS NOT NULL THEN 'exchange_rate:F' END,
        CASE WHEN coalesce(r."buy_rate", '') = '' THEN 'buy_rate:N' END,
        CASE WHEN r."buy_rate" <> '' AND try_cast(r."buy_rate" AS DOUBLE) IS NULL THEN 'buy_rate:T' END,
        CASE WHEN r."buy_rate" <> '' AND NOT regexp_full_match(r."buy_rate", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."buy_rate" AS DOUBLE) IS NOT NULL THEN 'buy_rate:F' END,
        CASE WHEN coalesce(r."sell_rate", '') = '' THEN 'sell_rate:N' END,
        CASE WHEN r."sell_rate" <> '' AND try_cast(r."sell_rate" AS DOUBLE) IS NULL THEN 'sell_rate:T' END,
        CASE WHEN r."sell_rate" <> '' AND NOT regexp_full_match(r."sell_rate", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."sell_rate" AS DOUBLE) IS NOT NULL THEN 'sell_rate:F' END,
        CASE WHEN coalesce(r."source", '') = '' THEN 'source:N' END,
        CASE WHEN r."source" <> '' AND r."source" NOT IN ('Bloomberg', 'Central Bank', 'Internal', 'Reuters') THEN 'source:V1' END
    ], x -> x IS NOT NULL) AS _dq_issues
    from {{ source('bronze_raw', 'daily_exchange_rates') }} r
),
r as (
    select
        o.* REPLACE (
        CASE WHEN map_contains(c.m, 'date') THEN c.m['date'] ELSE o."date" END AS "date",
        CASE WHEN map_contains(c.m, 'source_currency') THEN c.m['source_currency'] ELSE o."source_currency" END AS "source_currency",
        CASE WHEN map_contains(c.m, 'target_currency') THEN c.m['target_currency'] ELSE o."target_currency" END AS "target_currency",
        CASE WHEN map_contains(c.m, 'exchange_rate') THEN c.m['exchange_rate'] ELSE o."exchange_rate" END AS "exchange_rate",
        CASE WHEN map_contains(c.m, 'buy_rate') THEN c.m['buy_rate'] ELSE o."buy_rate" END AS "buy_rate",
        CASE WHEN map_contains(c.m, 'sell_rate') THEN c.m['sell_rate'] ELSE o."sell_rate" END AS "sell_rate",
        CASE WHEN map_contains(c.m, 'source') THEN c.m['source'] ELSE o."source" END AS "source"
        ),
        coalesce(list_sort(map_keys(c.m)), []::VARCHAR[]) AS _corrected_columns
    from o
    left join c on c.source_file = o._source_file and c.record_no = o._record_no
)
select
    try_cast(nullif(r."date", '') AS DATE) AS "date",
    nullif(r."source_currency", '') AS "source_currency",
    nullif(r."target_currency", '') AS "target_currency",
    try_cast(nullif(r."exchange_rate", '') AS DOUBLE) AS "exchange_rate",
    try_cast(nullif(r."buy_rate", '') AS DOUBLE) AS "buy_rate",
    try_cast(nullif(r."sell_rate", '') AS DOUBLE) AS "sell_rate",
    nullif(r."source", '') AS "source",
    cast(r._partition_date AS date) AS _partition_date,
    r._source_file,
    r._record_no,
    r._record_sha256,
    r._parse_status,
    'bc6a5070f4a4' AS _contract_version,
    r._dq_issues,
    r._corrected_columns
from r
