-- satisfaction_surveys from lossless bronze, typed against platform/contracts/sources/satisfaction_surveys.yml
-- (contract 14e8189452d9). Generated by scripts/generate_silver_from_contracts.py: do not edit, change the contract and regenerate.
-- '' and absent fields become NULL; a value that does not cast becomes NULL and is listed in _dq_issues
-- as '<column>:<code>' (see audit.dq_cell_findings). Every bronze record is kept, flagged or not.
-- Approved corrections (dq_corrections_active, four-eyes) are overlaid on the text before typing; _dq_issues
-- stays computed on the original text (what the source sent) and _corrected_columns lists what the overlay changed.
with c as (
    select source_file, record_no,
           map_from_entries(list(struct_pack(k := column_name, v := new_value) ORDER BY column_name)) AS m
    from {{ ref('dq_corrections_active') }}
    where zone = 'bronze' and table_name = 'satisfaction_surveys'
    group by all
),
o as (
    select r.*, list_filter([
        CASE WHEN r._parse_status <> 'ok' THEN '*:G' END,
        CASE WHEN coalesce(r."survey_id", '') = '' THEN 'survey_id:N' END,
        CASE WHEN r."survey_id" <> '' AND NOT regexp_full_match(r."survey_id", 'SRV-[0-9A-Z]{20}') THEN 'survey_id:K' END,
        CASE WHEN coalesce(r."survey_date", '') = '' THEN 'survey_date:N' END,
        CASE WHEN r."survey_date" <> '' AND try_cast(r."survey_date" AS TIMESTAMP) IS NULL THEN 'survey_date:T' END,
        CASE WHEN r."survey_date" <> '' AND NOT regexp_full_match(r."survey_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]+)?)?)') AND try_cast(r."survey_date" AS TIMESTAMP) IS NOT NULL THEN 'survey_date:F' END,
        CASE WHEN coalesce(r."process_date", '') = '' THEN 'process_date:N' END,
        CASE WHEN r."process_date" <> '' AND try_cast(r."process_date" AS DATE) IS NULL THEN 'process_date:T' END,
        CASE WHEN r."process_date" <> '' AND NOT regexp_full_match(r."process_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2})') AND try_cast(r."process_date" AS DATE) IS NOT NULL THEN 'process_date:F' END,
        CASE WHEN coalesce(r."interaction_id", '') = '' THEN 'interaction_id:N' END,
        CASE WHEN r."interaction_id" <> '' AND NOT regexp_full_match(r."interaction_id", 'INT-[0-9A-Z]{16}') THEN 'interaction_id:K' END,
        CASE WHEN coalesce(r."customer_id", '') = '' THEN 'customer_id:N' END,
        CASE WHEN r."customer_id" <> '' AND NOT regexp_full_match(r."customer_id", 'CLI-[0-9A-Z]{12}') THEN 'customer_id:K' END,
        CASE WHEN coalesce(r."agent_id", '') = '' THEN 'agent_id:N' END,
        CASE WHEN r."agent_id" <> '' AND NOT regexp_full_match(r."agent_id", 'AGT-[0-9A-Z]{10}') THEN 'agent_id:K' END,
        CASE WHEN coalesce(r."survey_type", '') = '' THEN 'survey_type:N' END,
        CASE WHEN r."survey_type" <> '' AND r."survey_type" NOT IN ('CES', 'CSAT', 'NPS') THEN 'survey_type:V1' END,
        CASE WHEN coalesce(r."send_channel", '') = '' THEN 'send_channel:N' END,
        CASE WHEN r."send_channel" <> '' AND r."send_channel" NOT IN ('App', 'Email', 'IVR', 'SMS', 'Web') THEN 'send_channel:V1' END,
        CASE WHEN coalesce(r."main_score", '') = '' THEN 'main_score:N' END,
        CASE WHEN r."main_score" <> '' AND try_cast(r."main_score" AS BIGINT) IS NULL THEN 'main_score:T' END,
        CASE WHEN r."main_score" <> '' AND NOT regexp_full_match(r."main_score", '(?:[+-]?[0-9]+)') AND try_cast(r."main_score" AS BIGINT) IS NOT NULL THEN 'main_score:F' END,
        CASE WHEN r."nps_category" <> '' AND r."nps_category" NOT IN ('Detractor', 'Passive') THEN 'nps_category:V1' END,
        CASE WHEN r."question_1_text" <> '' AND r."question_1_text" NOT IN ('¿Cómo calificaría la atención brindada?', '¿El agente resolvió su consulta satisfactoriamente?', '¿Qué tan satisfecho está con el servicio recibido?') THEN 'question_1_text:V1' END,
        CASE WHEN r."question_1_response" <> '' AND try_cast(r."question_1_response" AS DOUBLE) IS NULL THEN 'question_1_response:T' END,
        CASE WHEN r."question_1_response" <> '' AND NOT regexp_full_match(r."question_1_response", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."question_1_response" AS DOUBLE) IS NOT NULL THEN 'question_1_response:F' END,
        CASE WHEN r."question_2_text" <> '' AND r."question_2_text" NOT IN ('¿El tiempo de espera fue aceptable?') THEN 'question_2_text:V1' END,
        CASE WHEN r."question_2_response" <> '' AND try_cast(r."question_2_response" AS DOUBLE) IS NULL THEN 'question_2_response:T' END,
        CASE WHEN r."question_2_response" <> '' AND NOT regexp_full_match(r."question_2_response", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."question_2_response" AS DOUBLE) IS NOT NULL THEN 'question_2_response:F' END,
        CASE WHEN r."question_3_text" <> '' AND r."question_3_text" NOT IN ('¿Volvería a contactarnos por este canal?') THEN 'question_3_text:V1' END,
        CASE WHEN r."question_3_response" <> '' AND try_cast(r."question_3_response" AS DOUBLE) IS NULL THEN 'question_3_response:T' END,
        CASE WHEN r."question_3_response" <> '' AND NOT regexp_full_match(r."question_3_response", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."question_3_response" AS DOUBLE) IS NOT NULL THEN 'question_3_response:F' END,
        CASE WHEN regexp_matches(r."open_comments", '(^|[^A-Za-z])(nan|NaN|None|null|NULL|undefined)([^A-Za-z]|$)') THEN 'open_comments:P' END,
        CASE WHEN regexp_matches(r."open_comments", '\{[a-z_]+\}') THEN 'open_comments:S' END,
        CASE WHEN r."comment_sentiment" <> '' AND r."comment_sentiment" NOT IN ('Negative', 'Neutral', 'Positive') THEN 'comment_sentiment:V1' END,
        CASE WHEN coalesce(r."response_time_hours", '') = '' THEN 'response_time_hours:N' END,
        CASE WHEN r."response_time_hours" <> '' AND try_cast(r."response_time_hours" AS DOUBLE) IS NULL THEN 'response_time_hours:T' END,
        CASE WHEN r."response_time_hours" <> '' AND NOT regexp_full_match(r."response_time_hours", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."response_time_hours" AS DOUBLE) IS NOT NULL THEN 'response_time_hours:F' END,
        CASE WHEN r."campaign_response_rate" <> '' AND try_cast(r."campaign_response_rate" AS DOUBLE) IS NULL THEN 'campaign_response_rate:T' END,
        CASE WHEN r."campaign_response_rate" <> '' AND NOT regexp_full_match(r."campaign_response_rate", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."campaign_response_rate" AS DOUBLE) IS NOT NULL THEN 'campaign_response_rate:F' END
    ], x -> x IS NOT NULL) AS _dq_issues
    from {{ source('bronze_raw', 'satisfaction_surveys') }} r
),
r as (
    select
        o.* REPLACE (
        CASE WHEN map_contains(c.m, 'survey_id') THEN c.m['survey_id'] ELSE o."survey_id" END AS "survey_id",
        CASE WHEN map_contains(c.m, 'survey_date') THEN c.m['survey_date'] ELSE o."survey_date" END AS "survey_date",
        CASE WHEN map_contains(c.m, 'process_date') THEN c.m['process_date'] ELSE o."process_date" END AS "process_date",
        CASE WHEN map_contains(c.m, 'interaction_id') THEN c.m['interaction_id'] ELSE o."interaction_id" END AS "interaction_id",
        CASE WHEN map_contains(c.m, 'customer_id') THEN c.m['customer_id'] ELSE o."customer_id" END AS "customer_id",
        CASE WHEN map_contains(c.m, 'agent_id') THEN c.m['agent_id'] ELSE o."agent_id" END AS "agent_id",
        CASE WHEN map_contains(c.m, 'survey_type') THEN c.m['survey_type'] ELSE o."survey_type" END AS "survey_type",
        CASE WHEN map_contains(c.m, 'send_channel') THEN c.m['send_channel'] ELSE o."send_channel" END AS "send_channel",
        CASE WHEN map_contains(c.m, 'main_score') THEN c.m['main_score'] ELSE o."main_score" END AS "main_score",
        CASE WHEN map_contains(c.m, 'nps_category') THEN c.m['nps_category'] ELSE o."nps_category" END AS "nps_category",
        CASE WHEN map_contains(c.m, 'question_1_text') THEN c.m['question_1_text'] ELSE o."question_1_text" END AS "question_1_text",
        CASE WHEN map_contains(c.m, 'question_1_response') THEN c.m['question_1_response'] ELSE o."question_1_response" END AS "question_1_response",
        CASE WHEN map_contains(c.m, 'question_2_text') THEN c.m['question_2_text'] ELSE o."question_2_text" END AS "question_2_text",
        CASE WHEN map_contains(c.m, 'question_2_response') THEN c.m['question_2_response'] ELSE o."question_2_response" END AS "question_2_response",
        CASE WHEN map_contains(c.m, 'question_3_text') THEN c.m['question_3_text'] ELSE o."question_3_text" END AS "question_3_text",
        CASE WHEN map_contains(c.m, 'question_3_response') THEN c.m['question_3_response'] ELSE o."question_3_response" END AS "question_3_response",
        CASE WHEN map_contains(c.m, 'open_comments') THEN c.m['open_comments'] ELSE o."open_comments" END AS "open_comments",
        CASE WHEN map_contains(c.m, 'comment_sentiment') THEN c.m['comment_sentiment'] ELSE o."comment_sentiment" END AS "comment_sentiment",
        CASE WHEN map_contains(c.m, 'response_time_hours') THEN c.m['response_time_hours'] ELSE o."response_time_hours" END AS "response_time_hours",
        CASE WHEN map_contains(c.m, 'campaign_response_rate') THEN c.m['campaign_response_rate'] ELSE o."campaign_response_rate" END AS "campaign_response_rate"
        ),
        coalesce(list_sort(map_keys(c.m)), []::VARCHAR[]) AS _corrected_columns
    from o
    left join c on c.source_file = o._source_file and c.record_no = o._record_no
)
select
    nullif(r."survey_id", '') AS "survey_id",
    try_cast(nullif(r."survey_date", '') AS TIMESTAMP) AS "survey_date",
    try_cast(nullif(r."process_date", '') AS DATE) AS "process_date",
    nullif(r."interaction_id", '') AS "interaction_id",
    nullif(r."customer_id", '') AS "customer_id",
    nullif(r."agent_id", '') AS "agent_id",
    nullif(r."survey_type", '') AS "survey_type",
    nullif(r."send_channel", '') AS "send_channel",
    try_cast(nullif(r."main_score", '') AS BIGINT) AS "main_score",
    nullif(r."nps_category", '') AS "nps_category",
    nullif(r."question_1_text", '') AS "question_1_text",
    try_cast(nullif(r."question_1_response", '') AS DOUBLE) AS "question_1_response",
    nullif(r."question_2_text", '') AS "question_2_text",
    try_cast(nullif(r."question_2_response", '') AS DOUBLE) AS "question_2_response",
    nullif(r."question_3_text", '') AS "question_3_text",
    try_cast(nullif(r."question_3_response", '') AS DOUBLE) AS "question_3_response",
    nullif(r."open_comments", '') AS "open_comments",
    nullif(r."comment_sentiment", '') AS "comment_sentiment",
    try_cast(nullif(r."response_time_hours", '') AS DOUBLE) AS "response_time_hours",
    try_cast(nullif(r."campaign_response_rate", '') AS DOUBLE) AS "campaign_response_rate",
    cast(r._partition_date AS date) AS _partition_date,
    r._source_file,
    r._record_no,
    r._record_sha256,
    r._parse_status,
    '14e8189452d9' AS _contract_version,
    r._dq_issues,
    r._corrected_columns
from r
