-- call_transcripts from lossless bronze, typed against platform/contracts/sources/call_transcripts.yml
-- (contract 92fbb4e20e6e). Generated by scripts/generate_silver_from_contracts.py: do not edit, change the contract and regenerate.
-- '' and absent fields become NULL; a value that does not cast becomes NULL and is listed in _dq_issues
-- as '<column>:<code>' (see audit.dq_cell_findings). Every bronze record is kept, flagged or not.
-- Approved corrections (dq_corrections_active, four-eyes) are overlaid on the text before typing; _dq_issues
-- stays computed on the original text (what the source sent) and _corrected_columns lists what the overlay changed.
with c as (
    select source_file, record_no,
           map_from_entries(list(struct_pack(k := column_name, v := new_value) ORDER BY column_name)) AS m
    from {{ ref('dq_corrections_active') }}
    where zone = 'bronze' and table_name = 'call_transcripts'
    group by all
),
o as (
    select r.*, list_filter([
        CASE WHEN r._parse_status <> 'ok' THEN '*:G' END,
        CASE WHEN coalesce(r."transcript_id", '') = '' THEN 'transcript_id:N' END,
        CASE WHEN r."transcript_id" <> '' AND NOT regexp_full_match(r."transcript_id", 'TRS-[0-9A-Z]{20}') THEN 'transcript_id:K' END,
        CASE WHEN coalesce(r."interaction_id", '') = '' THEN 'interaction_id:N' END,
        CASE WHEN r."interaction_id" <> '' AND NOT regexp_full_match(r."interaction_id", 'INT-[0-9A-Z]{16}') THEN 'interaction_id:K' END,
        CASE WHEN coalesce(r."process_date", '') = '' THEN 'process_date:N' END,
        CASE WHEN r."process_date" <> '' AND try_cast(r."process_date" AS DATE) IS NULL THEN 'process_date:T' END,
        CASE WHEN r."process_date" <> '' AND NOT regexp_full_match(r."process_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2})') AND try_cast(r."process_date" AS DATE) IS NOT NULL THEN 'process_date:F' END,
        CASE WHEN coalesce(r."customer_id", '') = '' THEN 'customer_id:N' END,
        CASE WHEN r."customer_id" <> '' AND NOT regexp_full_match(r."customer_id", 'CLI-[0-9A-Z]{12}') THEN 'customer_id:K' END,
        CASE WHEN coalesce(r."agent_id", '') = '' THEN 'agent_id:N' END,
        CASE WHEN r."agent_id" <> '' AND NOT regexp_full_match(r."agent_id", 'AGT-[0-9A-Z]{10}') THEN 'agent_id:K' END,
        CASE WHEN coalesce(r."full_text", '') = '' THEN 'full_text:N' END,
        CASE WHEN regexp_matches(r."full_text", '(^|[^A-Za-z])(nan|NaN|None|null|NULL|undefined)([^A-Za-z]|$)') THEN 'full_text:P' END,
        CASE WHEN coalesce(r."customer_text", '') = '' THEN 'customer_text:N' END,
        CASE WHEN regexp_matches(r."customer_text", '(^|[^A-Za-z])(nan|NaN|None|null|NULL|undefined)([^A-Za-z]|$)') THEN 'customer_text:P' END,
        CASE WHEN regexp_matches(r."customer_text", '\{[a-z_]+\}') THEN 'customer_text:S' END,
        CASE WHEN coalesce(r."agent_text", '') = '' THEN 'agent_text:N' END,
        CASE WHEN regexp_matches(r."agent_text", '(^|[^A-Za-z])(nan|NaN|None|null|NULL|undefined)([^A-Za-z]|$)') THEN 'agent_text:P' END,
        CASE WHEN coalesce(r."detected_language", '') = '' THEN 'detected_language:N' END,
        CASE WHEN r."detected_language" <> '' AND r."detected_language" NOT IN ('es') THEN 'detected_language:V1' END,
        CASE WHEN r."detected_accent" <> '' AND r."detected_accent" NOT IN ('argentine', 'colombian', 'mexican') THEN 'detected_accent:V1' END,
        CASE WHEN r."accent_confidence" <> '' AND try_cast(r."accent_confidence" AS DOUBLE) IS NULL THEN 'accent_confidence:T' END,
        CASE WHEN r."accent_confidence" <> '' AND NOT regexp_full_match(r."accent_confidence", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."accent_confidence" AS DOUBLE) IS NOT NULL THEN 'accent_confidence:F' END,
        CASE WHEN r."mentioned_entities" <> '' AND NOT regexp_full_match(r."mentioned_entities", '(?:\s*[\{\[].*[\}\]]\s*)') THEN 'mentioned_entities:F' END,
        CASE WHEN r."detected_intents" <> '' AND r."detected_intents" NOT IN ('consulta_general') THEN 'detected_intents:V1' END,
        CASE WHEN coalesce(r."main_topics", '') = '' THEN 'main_topics:N' END,
        CASE WHEN r."main_topics" <> '' AND r."main_topics" NOT IN ('Comercial', 'Producto', 'Queja', 'Retención', 'Transaccional', 'Técnico') THEN 'main_topics:V1' END,
        CASE WHEN coalesce(r."transcription_model", '') = '' THEN 'transcription_model:N' END,
        CASE WHEN r."transcription_model" <> '' AND r."transcription_model" NOT IN ('AWS Transcribe', 'Azure Speech', 'Google STT', 'Whisper v3') THEN 'transcription_model:V1' END,
        CASE WHEN r."audio_quality" <> '' AND r."audio_quality" NOT IN ('High', 'Low', 'Medium') THEN 'audio_quality:V1' END,
        CASE WHEN r."duration_seconds" <> '' AND try_cast(r."duration_seconds" AS DOUBLE) IS NULL THEN 'duration_seconds:T' END,
        CASE WHEN r."duration_seconds" <> '' AND NOT regexp_full_match(r."duration_seconds", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."duration_seconds" AS DOUBLE) IS NOT NULL THEN 'duration_seconds:F' END
    ], x -> x IS NOT NULL) AS _dq_issues
    from {{ source('bronze_raw', 'call_transcripts') }} r
),
r as (
    select
        o.* REPLACE (
        CASE WHEN map_contains(c.m, 'transcript_id') THEN c.m['transcript_id'] ELSE o."transcript_id" END AS "transcript_id",
        CASE WHEN map_contains(c.m, 'interaction_id') THEN c.m['interaction_id'] ELSE o."interaction_id" END AS "interaction_id",
        CASE WHEN map_contains(c.m, 'process_date') THEN c.m['process_date'] ELSE o."process_date" END AS "process_date",
        CASE WHEN map_contains(c.m, 'customer_id') THEN c.m['customer_id'] ELSE o."customer_id" END AS "customer_id",
        CASE WHEN map_contains(c.m, 'agent_id') THEN c.m['agent_id'] ELSE o."agent_id" END AS "agent_id",
        CASE WHEN map_contains(c.m, 'full_text') THEN c.m['full_text'] ELSE o."full_text" END AS "full_text",
        CASE WHEN map_contains(c.m, 'customer_text') THEN c.m['customer_text'] ELSE o."customer_text" END AS "customer_text",
        CASE WHEN map_contains(c.m, 'agent_text') THEN c.m['agent_text'] ELSE o."agent_text" END AS "agent_text",
        CASE WHEN map_contains(c.m, 'detected_language') THEN c.m['detected_language'] ELSE o."detected_language" END AS "detected_language",
        CASE WHEN map_contains(c.m, 'detected_accent') THEN c.m['detected_accent'] ELSE o."detected_accent" END AS "detected_accent",
        CASE WHEN map_contains(c.m, 'accent_confidence') THEN c.m['accent_confidence'] ELSE o."accent_confidence" END AS "accent_confidence",
        CASE WHEN map_contains(c.m, 'detected_keywords') THEN c.m['detected_keywords'] ELSE o."detected_keywords" END AS "detected_keywords",
        CASE WHEN map_contains(c.m, 'mentioned_entities') THEN c.m['mentioned_entities'] ELSE o."mentioned_entities" END AS "mentioned_entities",
        CASE WHEN map_contains(c.m, 'detected_intents') THEN c.m['detected_intents'] ELSE o."detected_intents" END AS "detected_intents",
        CASE WHEN map_contains(c.m, 'main_topics') THEN c.m['main_topics'] ELSE o."main_topics" END AS "main_topics",
        CASE WHEN map_contains(c.m, 'transcription_model') THEN c.m['transcription_model'] ELSE o."transcription_model" END AS "transcription_model",
        CASE WHEN map_contains(c.m, 'audio_quality') THEN c.m['audio_quality'] ELSE o."audio_quality" END AS "audio_quality",
        CASE WHEN map_contains(c.m, 'duration_seconds') THEN c.m['duration_seconds'] ELSE o."duration_seconds" END AS "duration_seconds"
        ),
        coalesce(list_sort(map_keys(c.m)), []::VARCHAR[]) AS _corrected_columns
    from o
    left join c on c.source_file = o._source_file and c.record_no = o._record_no
)
select
    nullif(r."transcript_id", '') AS "transcript_id",
    nullif(r."interaction_id", '') AS "interaction_id",
    try_cast(nullif(r."process_date", '') AS DATE) AS "process_date",
    nullif(r."customer_id", '') AS "customer_id",
    nullif(r."agent_id", '') AS "agent_id",
    nullif(r."full_text", '') AS "full_text",
    nullif(r."customer_text", '') AS "customer_text",
    nullif(r."agent_text", '') AS "agent_text",
    nullif(r."detected_language", '') AS "detected_language",
    nullif(r."detected_accent", '') AS "detected_accent",
    try_cast(nullif(r."accent_confidence", '') AS DOUBLE) AS "accent_confidence",
    nullif(r."detected_keywords", '') AS "detected_keywords",
    nullif(r."mentioned_entities", '') AS "mentioned_entities",
    nullif(r."detected_intents", '') AS "detected_intents",
    nullif(r."main_topics", '') AS "main_topics",
    nullif(r."transcription_model", '') AS "transcription_model",
    nullif(r."audio_quality", '') AS "audio_quality",
    try_cast(nullif(r."duration_seconds", '') AS DOUBLE) AS "duration_seconds",
    cast(r._partition_date AS date) AS _partition_date,
    r._source_file,
    r._record_no,
    r._record_sha256,
    r._parse_status,
    '92fbb4e20e6e' AS _contract_version,
    r._dq_issues,
    r._corrected_columns
from r
