-- campaign_sends from lossless bronze, typed against platform/contracts/sources/campaign_sends.yml
-- (contract 03905e3487fa). Generated by scripts/generate_silver_from_contracts.py: do not edit, change the contract and regenerate.
-- '' and absent fields become NULL; a value that does not cast becomes NULL and is listed in _dq_issues
-- as '<column>:<code>' (see audit.dq_cell_findings). Every bronze record is kept, flagged or not.
-- Approved corrections (dq_corrections_active, four-eyes) are overlaid on the text before typing; _dq_issues
-- stays computed on the original text (what the source sent) and _corrected_columns lists what the overlay changed.
with c as (
    select source_file, record_no,
           map_from_entries(list(struct_pack(k := column_name, v := new_value) ORDER BY column_name)) AS m
    from {{ ref('dq_corrections_active') }}
    where zone = 'bronze' and table_name = 'campaign_sends'
    group by all
),
o as (
    select r.*, list_filter([
        CASE WHEN r._parse_status <> 'ok' THEN '*:G' END,
        CASE WHEN coalesce(r."send_id", '') = '' THEN 'send_id:N' END,
        CASE WHEN r."send_id" <> '' AND NOT regexp_full_match(r."send_id", 'SND-[0-9A-Z]{20}') THEN 'send_id:K' END,
        CASE WHEN coalesce(r."send_date", '') = '' THEN 'send_date:N' END,
        CASE WHEN r."send_date" <> '' AND try_cast(r."send_date" AS TIMESTAMP) IS NULL THEN 'send_date:T' END,
        CASE WHEN r."send_date" <> '' AND NOT regexp_full_match(r."send_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]+)?)?)') AND try_cast(r."send_date" AS TIMESTAMP) IS NOT NULL THEN 'send_date:F' END,
        CASE WHEN coalesce(r."process_date", '') = '' THEN 'process_date:N' END,
        CASE WHEN r."process_date" <> '' AND try_cast(r."process_date" AS DATE) IS NULL THEN 'process_date:T' END,
        CASE WHEN r."process_date" <> '' AND NOT regexp_full_match(r."process_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2})') AND try_cast(r."process_date" AS DATE) IS NOT NULL THEN 'process_date:F' END,
        CASE WHEN coalesce(r."campaign_id", '') = '' THEN 'campaign_id:N' END,
        CASE WHEN r."campaign_id" <> '' AND NOT regexp_full_match(r."campaign_id", 'CMP-[0-9A-Z]{12}') THEN 'campaign_id:K' END,
        CASE WHEN coalesce(r."customer_id", '') = '' THEN 'customer_id:N' END,
        CASE WHEN r."customer_id" <> '' AND NOT regexp_full_match(r."customer_id", 'CLI-[0-9A-Z]{12}') THEN 'customer_id:K' END,
        CASE WHEN coalesce(r."send_channel", '') = '' THEN 'send_channel:N' END,
        CASE WHEN r."send_channel" <> '' AND r."send_channel" NOT IN ('Email', 'Push', 'SMS', 'Voice', 'WhatsApp') THEN 'send_channel:V1' END,
        CASE WHEN regexp_matches(r."subject", '(^|[^A-Za-z])(nan|NaN|None|null|NULL|undefined)([^A-Za-z]|$)') THEN 'subject:P' END,
        CASE WHEN regexp_matches(r."subject", '\{[a-z_]+\}') THEN 'subject:S' END,
        CASE WHEN coalesce(r."send_status", '') = '' THEN 'send_status:N' END,
        CASE WHEN r."send_status" <> '' AND r."send_status" NOT IN ('Blocked', 'Bounced', 'Failed', 'Sent') THEN 'send_status:V1' END,
        CASE WHEN coalesce(r."was_delivered", '') = '' THEN 'was_delivered:N' END,
        CASE WHEN r."was_delivered" <> '' AND try_cast(r."was_delivered" AS BOOLEAN) IS NULL THEN 'was_delivered:T' END,
        CASE WHEN r."was_delivered" <> '' AND NOT regexp_full_match(r."was_delivered", '(?i:(true|false))') AND try_cast(r."was_delivered" AS BOOLEAN) IS NOT NULL THEN 'was_delivered:F' END,
        CASE WHEN r."was_opened" <> '' AND try_cast(r."was_opened" AS BOOLEAN) IS NULL THEN 'was_opened:T' END,
        CASE WHEN r."was_opened" <> '' AND NOT regexp_full_match(r."was_opened", '(?i:(true|false))') AND try_cast(r."was_opened" AS BOOLEAN) IS NOT NULL THEN 'was_opened:F' END,
        CASE WHEN r."open_date" <> '' AND try_cast(r."open_date" AS TIMESTAMP) IS NULL THEN 'open_date:T' END,
        CASE WHEN r."open_date" <> '' AND NOT regexp_full_match(r."open_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]+)?)?)') AND try_cast(r."open_date" AS TIMESTAMP) IS NOT NULL THEN 'open_date:F' END,
        CASE WHEN coalesce(r."was_clicked", '') = '' THEN 'was_clicked:N' END,
        CASE WHEN r."was_clicked" <> '' AND try_cast(r."was_clicked" AS BOOLEAN) IS NULL THEN 'was_clicked:T' END,
        CASE WHEN r."was_clicked" <> '' AND NOT regexp_full_match(r."was_clicked", '(?i:(true|false))') AND try_cast(r."was_clicked" AS BOOLEAN) IS NOT NULL THEN 'was_clicked:F' END,
        CASE WHEN r."click_date" <> '' AND try_cast(r."click_date" AS TIMESTAMP) IS NULL THEN 'click_date:T' END,
        CASE WHEN r."click_date" <> '' AND NOT regexp_full_match(r."click_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]+)?)?)') AND try_cast(r."click_date" AS TIMESTAMP) IS NOT NULL THEN 'click_date:F' END,
        CASE WHEN r."click_count" <> '' AND try_cast(r."click_count" AS DOUBLE) IS NULL THEN 'click_count:T' END,
        CASE WHEN r."click_count" <> '' AND NOT regexp_full_match(r."click_count", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."click_count" AS DOUBLE) IS NOT NULL THEN 'click_count:F' END,
        CASE WHEN coalesce(r."had_conversion", '') = '' THEN 'had_conversion:N' END,
        CASE WHEN r."had_conversion" <> '' AND try_cast(r."had_conversion" AS BOOLEAN) IS NULL THEN 'had_conversion:T' END,
        CASE WHEN r."had_conversion" <> '' AND NOT regexp_full_match(r."had_conversion", '(?i:(true|false))') AND try_cast(r."had_conversion" AS BOOLEAN) IS NOT NULL THEN 'had_conversion:F' END,
        CASE WHEN r."conversion_date" <> '' AND try_cast(r."conversion_date" AS TIMESTAMP) IS NULL THEN 'conversion_date:T' END,
        CASE WHEN r."conversion_date" <> '' AND NOT regexp_full_match(r."conversion_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]+)?)?)') AND try_cast(r."conversion_date" AS TIMESTAMP) IS NOT NULL THEN 'conversion_date:F' END,
        CASE WHEN r."conversion_value" <> '' AND try_cast(r."conversion_value" AS DOUBLE) IS NULL THEN 'conversion_value:T' END,
        CASE WHEN r."conversion_value" <> '' AND NOT regexp_full_match(r."conversion_value", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."conversion_value" AS DOUBLE) IS NOT NULL THEN 'conversion_value:F' END,
        CASE WHEN r."open_device" <> '' AND r."open_device" NOT IN ('Desktop', 'Mobile', 'Tablet') THEN 'open_device:V1' END,
        CASE WHEN r."open_country" <> '' AND r."open_country" NOT IN ('Argentina', 'Colombia', 'México') THEN 'open_country:V1' END,
        CASE WHEN r."failure_reason" <> '' AND r."failure_reason" NOT IN ('Invalid email address', 'SMTP error', 'User blocked sender') THEN 'failure_reason:V1' END,
        CASE WHEN r."send_cost" <> '' AND try_cast(r."send_cost" AS DOUBLE) IS NULL THEN 'send_cost:T' END,
        CASE WHEN r."send_cost" <> '' AND NOT regexp_full_match(r."send_cost", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."send_cost" AS DOUBLE) IS NOT NULL THEN 'send_cost:F' END
    ], x -> x IS NOT NULL) AS _dq_issues
    from {{ source('bronze_raw', 'campaign_sends') }} r
),
r as (
    select
        o.* REPLACE (
        CASE WHEN map_contains(c.m, 'send_id') THEN c.m['send_id'] ELSE o."send_id" END AS "send_id",
        CASE WHEN map_contains(c.m, 'send_date') THEN c.m['send_date'] ELSE o."send_date" END AS "send_date",
        CASE WHEN map_contains(c.m, 'process_date') THEN c.m['process_date'] ELSE o."process_date" END AS "process_date",
        CASE WHEN map_contains(c.m, 'campaign_id') THEN c.m['campaign_id'] ELSE o."campaign_id" END AS "campaign_id",
        CASE WHEN map_contains(c.m, 'customer_id') THEN c.m['customer_id'] ELSE o."customer_id" END AS "customer_id",
        CASE WHEN map_contains(c.m, 'send_channel') THEN c.m['send_channel'] ELSE o."send_channel" END AS "send_channel",
        CASE WHEN map_contains(c.m, 'template_used') THEN c.m['template_used'] ELSE o."template_used" END AS "template_used",
        CASE WHEN map_contains(c.m, 'subject') THEN c.m['subject'] ELSE o."subject" END AS "subject",
        CASE WHEN map_contains(c.m, 'send_status') THEN c.m['send_status'] ELSE o."send_status" END AS "send_status",
        CASE WHEN map_contains(c.m, 'was_delivered') THEN c.m['was_delivered'] ELSE o."was_delivered" END AS "was_delivered",
        CASE WHEN map_contains(c.m, 'was_opened') THEN c.m['was_opened'] ELSE o."was_opened" END AS "was_opened",
        CASE WHEN map_contains(c.m, 'open_date') THEN c.m['open_date'] ELSE o."open_date" END AS "open_date",
        CASE WHEN map_contains(c.m, 'was_clicked') THEN c.m['was_clicked'] ELSE o."was_clicked" END AS "was_clicked",
        CASE WHEN map_contains(c.m, 'click_date') THEN c.m['click_date'] ELSE o."click_date" END AS "click_date",
        CASE WHEN map_contains(c.m, 'click_count') THEN c.m['click_count'] ELSE o."click_count" END AS "click_count",
        CASE WHEN map_contains(c.m, 'had_conversion') THEN c.m['had_conversion'] ELSE o."had_conversion" END AS "had_conversion",
        CASE WHEN map_contains(c.m, 'conversion_date') THEN c.m['conversion_date'] ELSE o."conversion_date" END AS "conversion_date",
        CASE WHEN map_contains(c.m, 'conversion_value') THEN c.m['conversion_value'] ELSE o."conversion_value" END AS "conversion_value",
        CASE WHEN map_contains(c.m, 'open_device') THEN c.m['open_device'] ELSE o."open_device" END AS "open_device",
        CASE WHEN map_contains(c.m, 'open_country') THEN c.m['open_country'] ELSE o."open_country" END AS "open_country",
        CASE WHEN map_contains(c.m, 'failure_reason') THEN c.m['failure_reason'] ELSE o."failure_reason" END AS "failure_reason",
        CASE WHEN map_contains(c.m, 'send_cost') THEN c.m['send_cost'] ELSE o."send_cost" END AS "send_cost"
        ),
        coalesce(list_sort(map_keys(c.m)), []::VARCHAR[]) AS _corrected_columns
    from o
    left join c on c.source_file = o._source_file and c.record_no = o._record_no
)
select
    nullif(r."send_id", '') AS "send_id",
    try_cast(nullif(r."send_date", '') AS TIMESTAMP) AS "send_date",
    try_cast(nullif(r."process_date", '') AS DATE) AS "process_date",
    nullif(r."campaign_id", '') AS "campaign_id",
    nullif(r."customer_id", '') AS "customer_id",
    nullif(r."send_channel", '') AS "send_channel",
    nullif(r."template_used", '') AS "template_used",
    nullif(r."subject", '') AS "subject",
    nullif(r."send_status", '') AS "send_status",
    try_cast(nullif(r."was_delivered", '') AS BOOLEAN) AS "was_delivered",
    try_cast(nullif(r."was_opened", '') AS BOOLEAN) AS "was_opened",
    try_cast(nullif(r."open_date", '') AS TIMESTAMP) AS "open_date",
    try_cast(nullif(r."was_clicked", '') AS BOOLEAN) AS "was_clicked",
    try_cast(nullif(r."click_date", '') AS TIMESTAMP) AS "click_date",
    try_cast(nullif(r."click_count", '') AS DOUBLE) AS "click_count",
    try_cast(nullif(r."had_conversion", '') AS BOOLEAN) AS "had_conversion",
    try_cast(nullif(r."conversion_date", '') AS TIMESTAMP) AS "conversion_date",
    try_cast(nullif(r."conversion_value", '') AS DOUBLE) AS "conversion_value",
    nullif(r."open_device", '') AS "open_device",
    nullif(r."open_country", '') AS "open_country",
    nullif(r."failure_reason", '') AS "failure_reason",
    try_cast(nullif(r."send_cost", '') AS DOUBLE) AS "send_cost",
    cast(r._partition_date AS date) AS _partition_date,
    r._source_file,
    r._record_no,
    r._record_sha256,
    r._parse_status,
    '03905e3487fa' AS _contract_version,
    r._dq_issues,
    r._corrected_columns
from r
