-- transactions from the lossless holdout zone, typed against platform/contracts/sources/transactions.yml
-- (contract 29f103cf4547). Generated by scripts/generate_silver_from_contracts.py: do not edit, change the contract and regenerate.
-- '' and absent fields become NULL; a value that does not cast becomes NULL and is listed in _dq_issues
-- as '<column>:<code>' (see audit.dq_cell_findings). Every bronze record is kept, flagged or not.
-- Approved corrections (dq_corrections_active, four-eyes) are overlaid on the text before typing; _dq_issues
-- stays computed on the original text (what the source sent) and _corrected_columns lists what the overlay changed.
with c as (
    select source_file, record_no,
           map_from_entries(list(struct_pack(k := column_name, v := new_value) ORDER BY column_name)) AS m
    from {{ ref('dq_corrections_active') }}
    where zone = 'holdout' and table_name = 'transactions'
    group by all
),
o as (
    select r.*, list_filter([
        CASE WHEN r._parse_status <> 'ok' THEN '*:G' END,
        CASE WHEN coalesce(r."transaction_id", '') = '' THEN 'transaction_id:N' END,
        CASE WHEN r."transaction_id" <> '' AND NOT regexp_full_match(r."transaction_id", 'TRX-[0-9A-Z]{20}') THEN 'transaction_id:K' END,
        CASE WHEN coalesce(r."transaction_date", '') = '' THEN 'transaction_date:N' END,
        CASE WHEN r."transaction_date" <> '' AND try_cast(r."transaction_date" AS TIMESTAMP) IS NULL THEN 'transaction_date:T' END,
        CASE WHEN r."transaction_date" <> '' AND NOT regexp_full_match(r."transaction_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]+)?)?)') AND try_cast(r."transaction_date" AS TIMESTAMP) IS NOT NULL THEN 'transaction_date:F' END,
        CASE WHEN coalesce(r."process_date", '') = '' THEN 'process_date:N' END,
        CASE WHEN r."process_date" <> '' AND try_cast(r."process_date" AS DATE) IS NULL THEN 'process_date:T' END,
        CASE WHEN r."process_date" <> '' AND NOT regexp_full_match(r."process_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2})') AND try_cast(r."process_date" AS DATE) IS NOT NULL THEN 'process_date:F' END,
        CASE WHEN coalesce(r."product_id", '') = '' THEN 'product_id:N' END,
        CASE WHEN r."product_id" <> '' AND NOT regexp_full_match(r."product_id", 'PRD-[0-9A-Z]{12}') THEN 'product_id:K' END,
        CASE WHEN coalesce(r."customer_id", '') = '' THEN 'customer_id:N' END,
        CASE WHEN r."customer_id" <> '' AND NOT regexp_full_match(r."customer_id", 'CLI-[0-9A-Z]{12}') THEN 'customer_id:K' END,
        CASE WHEN coalesce(r."transaction_type", '') = '' THEN 'transaction_type:N' END,
        CASE WHEN r."transaction_type" <> '' AND r."transaction_type" NOT IN ('Adjustment', 'Deposit', 'Payment', 'Purchase', 'Transfer', 'Withdrawal') THEN 'transaction_type:V1' END,
        CASE WHEN r."transaction_category" <> '' AND r."transaction_category" NOT IN ('Entertainment', 'Food', 'Health', 'Other', 'Services', 'Transport') THEN 'transaction_category:V1' END,
        CASE WHEN coalesce(r."amount", '') = '' THEN 'amount:N' END,
        CASE WHEN r."amount" <> '' AND try_cast(r."amount" AS DOUBLE) IS NULL THEN 'amount:T' END,
        CASE WHEN r."amount" <> '' AND NOT regexp_full_match(r."amount", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."amount" AS DOUBLE) IS NOT NULL THEN 'amount:F' END,
        CASE WHEN coalesce(r."currency", '') = '' THEN 'currency:N' END,
        CASE WHEN r."currency" <> '' AND r."currency" NOT IN ('ARS', 'COP', 'USD') THEN 'currency:V1' END,
        CASE WHEN r."amount_usd" <> '' AND try_cast(r."amount_usd" AS DOUBLE) IS NULL THEN 'amount_usd:T' END,
        CASE WHEN r."amount_usd" <> '' AND NOT regexp_full_match(r."amount_usd", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."amount_usd" AS DOUBLE) IS NOT NULL THEN 'amount_usd:F' END,
        CASE WHEN coalesce(r."channel", '') = '' THEN 'channel:N' END,
        CASE WHEN r."channel" <> '' AND r."channel" NOT IN ('ATM', 'App', 'Branch', 'POS', 'Transfer', 'Web') THEN 'channel:V1' END,
        CASE WHEN r."branch_id" <> '' AND NOT regexp_full_match(r."branch_id", 'SUC-[0-9A-Z]{8}') THEN 'branch_id:K' END,
        CASE WHEN r."merchant_name" <> '' AND r."merchant_name" NOT IN ('Boutique Moda', 'Cable TV', 'Centro Comercial', 'Cine Premium', 'Clínica Médica', 'Conciertos Live', 'Empresa Telefónica', 'Estación de Servicio', 'Farmacia Salud', 'Ferretería', 'Gasolinera Express', 'Internet Plus', 'Laboratorio Central', 'Mercado Central', 'Restaurante El Buen Sabor', 'Servicios Públicos', 'Streaming Music', 'Super Ahorro', 'Taxi Seguro', 'Teatro Nacional', 'Tienda Don José', 'Tienda General', 'Uber', 'Óptica Visión') THEN 'merchant_name:V1' END,
        CASE WHEN r."merchant_category" <> '' AND r."merchant_category" NOT IN ('Entertainment', 'Food', 'Health', 'Other', 'Services', 'Transport') THEN 'merchant_category:V1' END,
        CASE WHEN coalesce(r."transaction_country", '') = '' THEN 'transaction_country:N' END,
        CASE WHEN r."transaction_country" <> '' AND r."transaction_country" NOT IN ('Argentina', 'Brazil', 'Colombia', 'México', 'Spain', 'USA', 'Mexico') THEN 'transaction_country:V1' END,
        CASE WHEN r."transaction_country" IN ('Mexico') THEN 'transaction_country:V2' END,
        CASE WHEN r."transaction_city" <> '' AND r."transaction_city" NOT IN ('Barcelona', 'Barranquilla', 'Bogotá', 'Brasília', 'Buenos Aires', 'Cali', 'Cartagena', 'Ciudad de México', 'Córdoba', 'Guadalajara', 'Houston', 'La Plata', 'Los Angeles', 'Madrid', 'Medellín', 'Mendoza', 'Miami', 'Monterrey', 'New York', 'Puebla', 'Querétaro', 'Rio de Janeiro', 'Rosario', 'Salvador', 'Sevilla', 'São Paulo', 'Tijuana', 'Valencia') THEN 'transaction_city:V1' END,
        CASE WHEN coalesce(r."transaction_status", '') = '' THEN 'transaction_status:N' END,
        CASE WHEN r."transaction_status" <> '' AND r."transaction_status" NOT IN ('Approved', 'Declined', 'Pending', 'Reversed') THEN 'transaction_status:V1' END,
        CASE WHEN r."response_code" <> '' AND r."response_code" NOT IN ('00', '05', '14', '51', '54') THEN 'response_code:V1' END,
        CASE WHEN coalesce(r."is_fraud", '') = '' THEN 'is_fraud:N' END,
        CASE WHEN r."is_fraud" <> '' AND try_cast(r."is_fraud" AS BOOLEAN) IS NULL THEN 'is_fraud:T' END,
        CASE WHEN r."is_fraud" <> '' AND NOT regexp_full_match(r."is_fraud", '(?i:(true|false))') AND try_cast(r."is_fraud" AS BOOLEAN) IS NOT NULL THEN 'is_fraud:F' END,
        CASE WHEN r."fraud_score" <> '' AND try_cast(r."fraud_score" AS DOUBLE) IS NULL THEN 'fraud_score:T' END,
        CASE WHEN r."fraud_score" <> '' AND NOT regexp_full_match(r."fraud_score", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."fraud_score" AS DOUBLE) IS NOT NULL THEN 'fraud_score:F' END,
        CASE WHEN r."latitude" <> '' AND try_cast(r."latitude" AS DOUBLE) IS NULL THEN 'latitude:T' END,
        CASE WHEN r."latitude" <> '' AND NOT regexp_full_match(r."latitude", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."latitude" AS DOUBLE) IS NOT NULL THEN 'latitude:F' END,
        CASE WHEN r."longitude" <> '' AND try_cast(r."longitude" AS DOUBLE) IS NULL THEN 'longitude:T' END,
        CASE WHEN r."longitude" <> '' AND NOT regexp_full_match(r."longitude", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."longitude" AS DOUBLE) IS NOT NULL THEN 'longitude:F' END
    ], x -> x IS NOT NULL) AS _dq_issues
    from {{ source('holdout_raw', 'transactions') }} r
),
r as (
    select
        o.* REPLACE (
        CASE WHEN map_contains(c.m, 'transaction_id') THEN c.m['transaction_id'] ELSE o."transaction_id" END AS "transaction_id",
        CASE WHEN map_contains(c.m, 'transaction_date') THEN c.m['transaction_date'] ELSE o."transaction_date" END AS "transaction_date",
        CASE WHEN map_contains(c.m, 'process_date') THEN c.m['process_date'] ELSE o."process_date" END AS "process_date",
        CASE WHEN map_contains(c.m, 'product_id') THEN c.m['product_id'] ELSE o."product_id" END AS "product_id",
        CASE WHEN map_contains(c.m, 'customer_id') THEN c.m['customer_id'] ELSE o."customer_id" END AS "customer_id",
        CASE WHEN map_contains(c.m, 'transaction_type') THEN c.m['transaction_type'] ELSE o."transaction_type" END AS "transaction_type",
        CASE WHEN map_contains(c.m, 'transaction_category') THEN c.m['transaction_category'] ELSE o."transaction_category" END AS "transaction_category",
        CASE WHEN map_contains(c.m, 'amount') THEN c.m['amount'] ELSE o."amount" END AS "amount",
        CASE WHEN map_contains(c.m, 'currency') THEN c.m['currency'] ELSE o."currency" END AS "currency",
        CASE WHEN map_contains(c.m, 'amount_usd') THEN c.m['amount_usd'] ELSE o."amount_usd" END AS "amount_usd",
        CASE WHEN map_contains(c.m, 'channel') THEN c.m['channel'] ELSE o."channel" END AS "channel",
        CASE WHEN map_contains(c.m, 'branch_id') THEN c.m['branch_id'] ELSE o."branch_id" END AS "branch_id",
        CASE WHEN map_contains(c.m, 'merchant_name') THEN c.m['merchant_name'] ELSE o."merchant_name" END AS "merchant_name",
        CASE WHEN map_contains(c.m, 'merchant_category') THEN c.m['merchant_category'] ELSE o."merchant_category" END AS "merchant_category",
        CASE WHEN map_contains(c.m, 'transaction_country') THEN c.m['transaction_country'] ELSE o."transaction_country" END AS "transaction_country",
        CASE WHEN map_contains(c.m, 'transaction_city') THEN c.m['transaction_city'] ELSE o."transaction_city" END AS "transaction_city",
        CASE WHEN map_contains(c.m, 'transaction_status') THEN c.m['transaction_status'] ELSE o."transaction_status" END AS "transaction_status",
        CASE WHEN map_contains(c.m, 'response_code') THEN c.m['response_code'] ELSE o."response_code" END AS "response_code",
        CASE WHEN map_contains(c.m, 'is_fraud') THEN c.m['is_fraud'] ELSE o."is_fraud" END AS "is_fraud",
        CASE WHEN map_contains(c.m, 'fraud_score') THEN c.m['fraud_score'] ELSE o."fraud_score" END AS "fraud_score",
        CASE WHEN map_contains(c.m, 'latitude') THEN c.m['latitude'] ELSE o."latitude" END AS "latitude",
        CASE WHEN map_contains(c.m, 'longitude') THEN c.m['longitude'] ELSE o."longitude" END AS "longitude"
        ),
        coalesce(list_sort(map_keys(c.m)), []::VARCHAR[]) AS _corrected_columns
    from o
    left join c on c.source_file = o._source_file and c.record_no = o._record_no
)
select
    nullif(r."transaction_id", '') AS "transaction_id",
    try_cast(nullif(r."transaction_date", '') AS TIMESTAMP) AS "transaction_date",
    try_cast(nullif(r."process_date", '') AS DATE) AS "process_date",
    nullif(r."product_id", '') AS "product_id",
    nullif(r."customer_id", '') AS "customer_id",
    nullif(r."transaction_type", '') AS "transaction_type",
    nullif(r."transaction_category", '') AS "transaction_category",
    try_cast(nullif(r."amount", '') AS DOUBLE) AS "amount",
    nullif(r."currency", '') AS "currency",
    try_cast(nullif(r."amount_usd", '') AS DOUBLE) AS "amount_usd",
    nullif(r."channel", '') AS "channel",
    nullif(r."branch_id", '') AS "branch_id",
    nullif(r."merchant_name", '') AS "merchant_name",
    nullif(r."merchant_category", '') AS "merchant_category",
    nullif(r."transaction_country", '') AS "transaction_country",
    nullif(r."transaction_city", '') AS "transaction_city",
    nullif(r."transaction_status", '') AS "transaction_status",
    nullif(r."response_code", '') AS "response_code",
    try_cast(nullif(r."is_fraud", '') AS BOOLEAN) AS "is_fraud",
    try_cast(nullif(r."fraud_score", '') AS DOUBLE) AS "fraud_score",
    try_cast(nullif(r."latitude", '') AS DOUBLE) AS "latitude",
    try_cast(nullif(r."longitude", '') AS DOUBLE) AS "longitude",
    cast(r._partition_date AS date) AS _partition_date,
    r._source_file,
    r._record_no,
    r._record_sha256,
    r._parse_status,
    '29f103cf4547' AS _contract_version,
    r._dq_issues,
    r._corrected_columns
from r
