-- service_agents from lossless bronze, typed against platform/contracts/sources/service_agents.yml
-- (contract 2a062ddb68fb). Generated by scripts/generate_silver_from_contracts.py: do not edit, change the contract and regenerate.
-- '' and absent fields become NULL; a value that does not cast becomes NULL and is listed in _dq_issues
-- as '<column>:<code>' (see audit.dq_cell_findings). Every bronze record is kept, flagged or not.
-- Approved corrections (dq_corrections_active, four-eyes) are overlaid on the text before typing; _dq_issues
-- stays computed on the original text (what the source sent) and _corrected_columns lists what the overlay changed.
with c as (
    select source_file, record_no,
           map_from_entries(list(struct_pack(k := column_name, v := new_value) ORDER BY column_name)) AS m
    from {{ ref('dq_corrections_active') }}
    where zone = 'bronze' and table_name = 'service_agents'
    group by all
),
o as (
    select r.*, list_filter([
        CASE WHEN r._parse_status <> 'ok' THEN '*:G' END,
        CASE WHEN coalesce(r."agent_id", '') = '' THEN 'agent_id:N' END,
        CASE WHEN r."agent_id" <> '' AND NOT regexp_full_match(r."agent_id", 'AGT-[0-9A-Z]{10}') THEN 'agent_id:K' END,
        CASE WHEN coalesce(r."employee_code", '') = '' THEN 'employee_code:N' END,
        CASE WHEN coalesce(r."first_name", '') = '' THEN 'first_name:N' END,
        CASE WHEN coalesce(r."last_name", '') = '' THEN 'last_name:N' END,
        CASE WHEN coalesce(r."email", '') = '' THEN 'email:N' END,
        CASE WHEN coalesce(r."native_accent", '') = '' THEN 'native_accent:N' END,
        CASE WHEN r."native_accent" <> '' AND r."native_accent" NOT IN ('argentine', 'colombian', 'mexican') THEN 'native_accent:V1' END,
        CASE WHEN coalesce(r."country_of_origin", '') = '' THEN 'country_of_origin:N' END,
        CASE WHEN r."country_of_origin" <> '' AND r."country_of_origin" NOT IN ('Argentina', 'Colombia', 'Mexico') THEN 'country_of_origin:V1' END,
        CASE WHEN r."assigned_branch_id" <> '' AND NOT regexp_full_match(r."assigned_branch_id", 'SUC-[0-9A-Z]{8}') THEN 'assigned_branch_id:K' END,
        CASE WHEN coalesce(r."agent_type", '') = '' THEN 'agent_type:N' END,
        CASE WHEN r."agent_type" <> '' AND r."agent_type" NOT IN ('Digital', 'Hybrid', 'In-Person', 'Phone') THEN 'agent_type:V1' END,
        CASE WHEN coalesce(r."experience_level", '') = '' THEN 'experience_level:N' END,
        CASE WHEN r."experience_level" <> '' AND r."experience_level" NOT IN ('Junior', 'Mid-Senior', 'Senior', 'Specialist') THEN 'experience_level:V1' END,
        CASE WHEN coalesce(r."languages", '') = '' THEN 'languages:N' END,
        CASE WHEN r."specialty" <> '' AND r."specialty" NOT IN ('Cobranza', 'Créditos', 'Fraudes', 'Inversiones', 'Quejas y Reclamos', 'Retención', 'Soporte Técnico', 'Ventas') THEN 'specialty:V1' END,
        CASE WHEN coalesce(r."hire_date", '') = '' THEN 'hire_date:N' END,
        CASE WHEN r."hire_date" <> '' AND try_cast(r."hire_date" AS DATE) IS NULL THEN 'hire_date:T' END,
        CASE WHEN r."hire_date" <> '' AND NOT regexp_full_match(r."hire_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2})') AND try_cast(r."hire_date" AS DATE) IS NOT NULL THEN 'hire_date:F' END,
        CASE WHEN r."avg_csat" <> '' AND try_cast(r."avg_csat" AS DOUBLE) IS NULL THEN 'avg_csat:T' END,
        CASE WHEN r."avg_csat" <> '' AND NOT regexp_full_match(r."avg_csat", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."avg_csat" AS DOUBLE) IS NOT NULL THEN 'avg_csat:F' END,
        CASE WHEN r."total_monthly_interactions" <> '' AND try_cast(r."total_monthly_interactions" AS DOUBLE) IS NULL THEN 'total_monthly_interactions:T' END,
        CASE WHEN r."total_monthly_interactions" <> '' AND NOT regexp_full_match(r."total_monthly_interactions", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."total_monthly_interactions" AS DOUBLE) IS NOT NULL THEN 'total_monthly_interactions:F' END,
        CASE WHEN coalesce(r."agent_status", '') = '' THEN 'agent_status:N' END,
        CASE WHEN r."agent_status" <> '' AND r."agent_status" NOT IN ('Active', 'Inactive', 'Leave', 'Vacation') THEN 'agent_status:V1' END,
        CASE WHEN coalesce(r."work_shift", '') = '' THEN 'work_shift:N' END,
        CASE WHEN r."work_shift" <> '' AND r."work_shift" NOT IN ('Afternoon', 'Morning', 'Night', 'Rotating') THEN 'work_shift:V1' END
    ], x -> x IS NOT NULL) AS _dq_issues
    from {{ source('bronze_raw', 'service_agents') }} r
),
r as (
    select
        o.* REPLACE (
        CASE WHEN map_contains(c.m, 'agent_id') THEN c.m['agent_id'] ELSE o."agent_id" END AS "agent_id",
        CASE WHEN map_contains(c.m, 'employee_code') THEN c.m['employee_code'] ELSE o."employee_code" END AS "employee_code",
        CASE WHEN map_contains(c.m, 'first_name') THEN c.m['first_name'] ELSE o."first_name" END AS "first_name",
        CASE WHEN map_contains(c.m, 'last_name') THEN c.m['last_name'] ELSE o."last_name" END AS "last_name",
        CASE WHEN map_contains(c.m, 'email') THEN c.m['email'] ELSE o."email" END AS "email",
        CASE WHEN map_contains(c.m, 'phone') THEN c.m['phone'] ELSE o."phone" END AS "phone",
        CASE WHEN map_contains(c.m, 'native_accent') THEN c.m['native_accent'] ELSE o."native_accent" END AS "native_accent",
        CASE WHEN map_contains(c.m, 'country_of_origin') THEN c.m['country_of_origin'] ELSE o."country_of_origin" END AS "country_of_origin",
        CASE WHEN map_contains(c.m, 'assigned_branch_id') THEN c.m['assigned_branch_id'] ELSE o."assigned_branch_id" END AS "assigned_branch_id",
        CASE WHEN map_contains(c.m, 'agent_type') THEN c.m['agent_type'] ELSE o."agent_type" END AS "agent_type",
        CASE WHEN map_contains(c.m, 'experience_level') THEN c.m['experience_level'] ELSE o."experience_level" END AS "experience_level",
        CASE WHEN map_contains(c.m, 'languages') THEN c.m['languages'] ELSE o."languages" END AS "languages",
        CASE WHEN map_contains(c.m, 'specialty') THEN c.m['specialty'] ELSE o."specialty" END AS "specialty",
        CASE WHEN map_contains(c.m, 'hire_date') THEN c.m['hire_date'] ELSE o."hire_date" END AS "hire_date",
        CASE WHEN map_contains(c.m, 'avg_csat') THEN c.m['avg_csat'] ELSE o."avg_csat" END AS "avg_csat",
        CASE WHEN map_contains(c.m, 'total_monthly_interactions') THEN c.m['total_monthly_interactions'] ELSE o."total_monthly_interactions" END AS "total_monthly_interactions",
        CASE WHEN map_contains(c.m, 'agent_status') THEN c.m['agent_status'] ELSE o."agent_status" END AS "agent_status",
        CASE WHEN map_contains(c.m, 'work_shift') THEN c.m['work_shift'] ELSE o."work_shift" END AS "work_shift"
        ),
        coalesce(list_sort(map_keys(c.m)), []::VARCHAR[]) AS _corrected_columns
    from o
    left join c on c.source_file = o._source_file and c.record_no = o._record_no
)
select
    nullif(r."agent_id", '') AS "agent_id",
    nullif(r."employee_code", '') AS "employee_code",
    nullif(r."first_name", '') AS "first_name",
    nullif(r."last_name", '') AS "last_name",
    nullif(r."email", '') AS "email",
    nullif(r."phone", '') AS "phone",
    nullif(r."native_accent", '') AS "native_accent",
    nullif(r."country_of_origin", '') AS "country_of_origin",
    nullif(r."assigned_branch_id", '') AS "assigned_branch_id",
    nullif(r."agent_type", '') AS "agent_type",
    nullif(r."experience_level", '') AS "experience_level",
    nullif(r."languages", '') AS "languages",
    nullif(r."specialty", '') AS "specialty",
    try_cast(nullif(r."hire_date", '') AS DATE) AS "hire_date",
    try_cast(nullif(r."avg_csat", '') AS DOUBLE) AS "avg_csat",
    try_cast(nullif(r."total_monthly_interactions", '') AS DOUBLE) AS "total_monthly_interactions",
    nullif(r."agent_status", '') AS "agent_status",
    nullif(r."work_shift", '') AS "work_shift",
    cast(r._partition_date AS date) AS _partition_date,
    r._source_file,
    r._record_no,
    r._record_sha256,
    r._parse_status,
    '2a062ddb68fb' AS _contract_version,
    r._dq_issues,
    r._corrected_columns
from r
