-- products from lossless bronze, typed against platform/contracts/sources/products.yml
-- (contract dab47679a5f2). Generated by scripts/generate_silver_from_contracts.py: do not edit, change the contract and regenerate.
-- '' and absent fields become NULL; a value that does not cast becomes NULL and is listed in _dq_issues
-- as '<column>:<code>' (see audit.dq_cell_findings). Every bronze record is kept, flagged or not.
-- Approved corrections (dq_corrections_active, four-eyes) are overlaid on the text before typing; _dq_issues
-- stays computed on the original text (what the source sent) and _corrected_columns lists what the overlay changed.
with c as (
    select source_file, record_no,
           map_from_entries(list(struct_pack(k := column_name, v := new_value) ORDER BY column_name)) AS m
    from {{ ref('dq_corrections_active') }}
    where zone = 'bronze' and table_name = 'products'
    group by all
),
o as (
    select r.*, list_filter([
        CASE WHEN r._parse_status <> 'ok' THEN '*:G' END,
        CASE WHEN coalesce(r."product_id", '') = '' THEN 'product_id:N' END,
        CASE WHEN r."product_id" <> '' AND NOT regexp_full_match(r."product_id", 'PRD-[0-9A-Z]{12}') THEN 'product_id:K' END,
        CASE WHEN coalesce(r."customer_id", '') = '' THEN 'customer_id:N' END,
        CASE WHEN r."customer_id" <> '' AND NOT regexp_full_match(r."customer_id", 'CLI-[0-9A-Z]{12}') THEN 'customer_id:K' END,
        CASE WHEN coalesce(r."product_type", '') = '' THEN 'product_type:N' END,
        CASE WHEN r."product_type" <> '' AND r."product_type" NOT IN ('Cuenta Ahorro', 'Cuenta Corriente', 'Inversión', 'Préstamo Hipotecario', 'Préstamo Personal', 'Seguro', 'Tarjeta Crédito', 'Tarjeta Débito') THEN 'product_type:V1' END,
        CASE WHEN coalesce(r."product_number", '') = '' THEN 'product_number:N' END,
        CASE WHEN coalesce(r."currency", '') = '' THEN 'currency:N' END,
        CASE WHEN r."currency" <> '' AND r."currency" NOT IN ('ARS', 'COP', 'USD') THEN 'currency:V1' END,
        CASE WHEN coalesce(r."current_balance", '') = '' THEN 'current_balance:N' END,
        CASE WHEN r."current_balance" <> '' AND try_cast(r."current_balance" AS DOUBLE) IS NULL THEN 'current_balance:T' END,
        CASE WHEN r."current_balance" <> '' AND NOT regexp_full_match(r."current_balance", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."current_balance" AS DOUBLE) IS NOT NULL THEN 'current_balance:F' END,
        CASE WHEN r."credit_limit" <> '' AND try_cast(r."credit_limit" AS DOUBLE) IS NULL THEN 'credit_limit:T' END,
        CASE WHEN r."credit_limit" <> '' AND NOT regexp_full_match(r."credit_limit", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."credit_limit" AS DOUBLE) IS NOT NULL THEN 'credit_limit:F' END,
        CASE WHEN r."interest_rate" <> '' AND try_cast(r."interest_rate" AS DOUBLE) IS NULL THEN 'interest_rate:T' END,
        CASE WHEN r."interest_rate" <> '' AND NOT regexp_full_match(r."interest_rate", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."interest_rate" AS DOUBLE) IS NOT NULL THEN 'interest_rate:F' END,
        CASE WHEN coalesce(r."opening_date", '') = '' THEN 'opening_date:N' END,
        CASE WHEN r."opening_date" <> '' AND try_cast(r."opening_date" AS DATE) IS NULL THEN 'opening_date:T' END,
        CASE WHEN r."opening_date" <> '' AND NOT regexp_full_match(r."opening_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2})') AND try_cast(r."opening_date" AS DATE) IS NOT NULL THEN 'opening_date:F' END,
        CASE WHEN r."expiration_date" <> '' AND try_cast(r."expiration_date" AS DATE) IS NULL THEN 'expiration_date:T' END,
        CASE WHEN r."expiration_date" <> '' AND NOT regexp_full_match(r."expiration_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2})') AND try_cast(r."expiration_date" AS DATE) IS NOT NULL THEN 'expiration_date:F' END,
        CASE WHEN coalesce(r."opening_branch_id", '') = '' THEN 'opening_branch_id:N' END,
        CASE WHEN r."opening_branch_id" <> '' AND NOT regexp_full_match(r."opening_branch_id", 'SUC-[0-9A-Z]{8}') THEN 'opening_branch_id:K' END,
        CASE WHEN coalesce(r."product_status", '') = '' THEN 'product_status:N' END,
        CASE WHEN r."product_status" <> '' AND r."product_status" NOT IN ('Active', 'Blocked', 'Closed', 'Suspended') THEN 'product_status:V1' END,
        CASE WHEN coalesce(r."opening_channel", '') = '' THEN 'opening_channel:N' END,
        CASE WHEN r."opening_channel" <> '' AND r."opening_channel" NOT IN ('App', 'Branch', 'Call Center', 'Web') THEN 'opening_channel:V1' END,
        CASE WHEN coalesce(r."has_linked_app", '') = '' THEN 'has_linked_app:N' END,
        CASE WHEN r."has_linked_app" <> '' AND try_cast(r."has_linked_app" AS BOOLEAN) IS NULL THEN 'has_linked_app:T' END,
        CASE WHEN r."has_linked_app" <> '' AND NOT regexp_full_match(r."has_linked_app", '(?i:(true|false))') AND try_cast(r."has_linked_app" AS BOOLEAN) IS NOT NULL THEN 'has_linked_app:F' END,
        CASE WHEN r."days_past_due" <> '' AND try_cast(r."days_past_due" AS DOUBLE) IS NULL THEN 'days_past_due:T' END,
        CASE WHEN r."days_past_due" <> '' AND NOT regexp_full_match(r."days_past_due", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."days_past_due" AS DOUBLE) IS NOT NULL THEN 'days_past_due:F' END,
        CASE WHEN r."last_transaction_date" <> '' AND try_cast(r."last_transaction_date" AS TIMESTAMP) IS NULL THEN 'last_transaction_date:T' END,
        CASE WHEN r."last_transaction_date" <> '' AND NOT regexp_full_match(r."last_transaction_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]+)?)?)') AND try_cast(r."last_transaction_date" AS TIMESTAMP) IS NOT NULL THEN 'last_transaction_date:F' END,
        CASE WHEN coalesce(r."last_updated", '') = '' THEN 'last_updated:N' END,
        CASE WHEN r."last_updated" <> '' AND try_cast(r."last_updated" AS TIMESTAMP) IS NULL THEN 'last_updated:T' END,
        CASE WHEN r."last_updated" <> '' AND NOT regexp_full_match(r."last_updated", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]+)?)?)') AND try_cast(r."last_updated" AS TIMESTAMP) IS NOT NULL THEN 'last_updated:F' END
    ], x -> x IS NOT NULL) AS _dq_issues
    from {{ source('bronze_raw', 'products') }} r
),
r as (
    select
        o.* REPLACE (
        CASE WHEN map_contains(c.m, 'product_id') THEN c.m['product_id'] ELSE o."product_id" END AS "product_id",
        CASE WHEN map_contains(c.m, 'customer_id') THEN c.m['customer_id'] ELSE o."customer_id" END AS "customer_id",
        CASE WHEN map_contains(c.m, 'product_type') THEN c.m['product_type'] ELSE o."product_type" END AS "product_type",
        CASE WHEN map_contains(c.m, 'product_number') THEN c.m['product_number'] ELSE o."product_number" END AS "product_number",
        CASE WHEN map_contains(c.m, 'currency') THEN c.m['currency'] ELSE o."currency" END AS "currency",
        CASE WHEN map_contains(c.m, 'current_balance') THEN c.m['current_balance'] ELSE o."current_balance" END AS "current_balance",
        CASE WHEN map_contains(c.m, 'credit_limit') THEN c.m['credit_limit'] ELSE o."credit_limit" END AS "credit_limit",
        CASE WHEN map_contains(c.m, 'interest_rate') THEN c.m['interest_rate'] ELSE o."interest_rate" END AS "interest_rate",
        CASE WHEN map_contains(c.m, 'opening_date') THEN c.m['opening_date'] ELSE o."opening_date" END AS "opening_date",
        CASE WHEN map_contains(c.m, 'expiration_date') THEN c.m['expiration_date'] ELSE o."expiration_date" END AS "expiration_date",
        CASE WHEN map_contains(c.m, 'opening_branch_id') THEN c.m['opening_branch_id'] ELSE o."opening_branch_id" END AS "opening_branch_id",
        CASE WHEN map_contains(c.m, 'product_status') THEN c.m['product_status'] ELSE o."product_status" END AS "product_status",
        CASE WHEN map_contains(c.m, 'opening_channel') THEN c.m['opening_channel'] ELSE o."opening_channel" END AS "opening_channel",
        CASE WHEN map_contains(c.m, 'has_linked_app') THEN c.m['has_linked_app'] ELSE o."has_linked_app" END AS "has_linked_app",
        CASE WHEN map_contains(c.m, 'days_past_due') THEN c.m['days_past_due'] ELSE o."days_past_due" END AS "days_past_due",
        CASE WHEN map_contains(c.m, 'last_transaction_date') THEN c.m['last_transaction_date'] ELSE o."last_transaction_date" END AS "last_transaction_date",
        CASE WHEN map_contains(c.m, 'last_updated') THEN c.m['last_updated'] ELSE o."last_updated" END AS "last_updated"
        ),
        coalesce(list_sort(map_keys(c.m)), []::VARCHAR[]) AS _corrected_columns
    from o
    left join c on c.source_file = o._source_file and c.record_no = o._record_no
)
select
    nullif(r."product_id", '') AS "product_id",
    nullif(r."customer_id", '') AS "customer_id",
    nullif(r."product_type", '') AS "product_type",
    nullif(r."product_number", '') AS "product_number",
    nullif(r."currency", '') AS "currency",
    try_cast(nullif(r."current_balance", '') AS DOUBLE) AS "current_balance",
    try_cast(nullif(r."credit_limit", '') AS DOUBLE) AS "credit_limit",
    try_cast(nullif(r."interest_rate", '') AS DOUBLE) AS "interest_rate",
    try_cast(nullif(r."opening_date", '') AS DATE) AS "opening_date",
    try_cast(nullif(r."expiration_date", '') AS DATE) AS "expiration_date",
    nullif(r."opening_branch_id", '') AS "opening_branch_id",
    nullif(r."product_status", '') AS "product_status",
    nullif(r."opening_channel", '') AS "opening_channel",
    try_cast(nullif(r."has_linked_app", '') AS BOOLEAN) AS "has_linked_app",
    try_cast(nullif(r."days_past_due", '') AS DOUBLE) AS "days_past_due",
    try_cast(nullif(r."last_transaction_date", '') AS TIMESTAMP) AS "last_transaction_date",
    try_cast(nullif(r."last_updated", '') AS TIMESTAMP) AS "last_updated",
    cast(r._partition_date AS date) AS _partition_date,
    r._source_file,
    r._record_no,
    r._record_sha256,
    r._parse_status,
    'dab47679a5f2' AS _contract_version,
    r._dq_issues,
    r._corrected_columns
from r
