-- digital_events from lossless bronze, typed against platform/contracts/sources/digital_events.yml
-- (contract ee4fdcf82d56). Generated by scripts/generate_silver_from_contracts.py: do not edit, change the contract and regenerate.
-- '' and absent fields become NULL; a value that does not cast becomes NULL and is listed in _dq_issues
-- as '<column>:<code>' (see audit.dq_cell_findings). Every bronze record is kept, flagged or not.
-- Approved corrections (dq_corrections_active, four-eyes) are overlaid on the text before typing; _dq_issues
-- stays computed on the original text (what the source sent) and _corrected_columns lists what the overlay changed.
with c as (
    select source_file, record_no,
           map_from_entries(list(struct_pack(k := column_name, v := new_value) ORDER BY column_name)) AS m
    from {{ ref('dq_corrections_active') }}
    where zone = 'bronze' and table_name = 'digital_events'
    group by all
),
o as (
    select r.*, list_filter([
        CASE WHEN r._parse_status <> 'ok' THEN '*:G' END,
        CASE WHEN coalesce(r."event_id", '') = '' THEN 'event_id:N' END,
        CASE WHEN r."event_id" <> '' AND NOT regexp_full_match(r."event_id", 'EVT-[0-9A-Z]{20}') THEN 'event_id:K' END,
        CASE WHEN coalesce(r."event_date", '') = '' THEN 'event_date:N' END,
        CASE WHEN r."event_date" <> '' AND try_cast(r."event_date" AS TIMESTAMP) IS NULL THEN 'event_date:T' END,
        CASE WHEN r."event_date" <> '' AND NOT regexp_full_match(r."event_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]+)?)?)') AND try_cast(r."event_date" AS TIMESTAMP) IS NOT NULL THEN 'event_date:F' END,
        CASE WHEN coalesce(r."process_date", '') = '' THEN 'process_date:N' END,
        CASE WHEN r."process_date" <> '' AND try_cast(r."process_date" AS DATE) IS NULL THEN 'process_date:T' END,
        CASE WHEN r."process_date" <> '' AND NOT regexp_full_match(r."process_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2})') AND try_cast(r."process_date" AS DATE) IS NOT NULL THEN 'process_date:F' END,
        CASE WHEN r."customer_id" <> '' AND NOT regexp_full_match(r."customer_id", 'CLI-[0-9A-Z]{12}') THEN 'customer_id:K' END,
        CASE WHEN coalesce(r."session_id", '') = '' THEN 'session_id:N' END,
        CASE WHEN r."session_id" <> '' AND NOT regexp_full_match(r."session_id", 'SES-[0-9A-Z]{28}') THEN 'session_id:K' END,
        CASE WHEN coalesce(r."event_type", '') = '' THEN 'event_type:N' END,
        CASE WHEN r."event_type" <> '' AND r."event_type" NOT IN ('Click', 'Error', 'FormSubmit', 'Login', 'Logout', 'PageView', 'Purchase') THEN 'event_type:V1' END,
        CASE WHEN coalesce(r."event_category", '') = '' THEN 'event_category:N' END,
        CASE WHEN r."event_category" <> '' AND r."event_category" NOT IN ('Authentication', 'Navigation', 'Product', 'Transaction') THEN 'event_category:V1' END,
        CASE WHEN coalesce(r."channel", '') = '' THEN 'channel:N' END,
        CASE WHEN r."channel" <> '' AND r."channel" NOT IN ('Android App', 'Desktop Web', 'Mobile Web', 'iOS App') THEN 'channel:V1' END,
        CASE WHEN r."platform" <> '' AND r."platform" NOT IN ('Android', 'Linux', 'MacOS', 'Windows', 'iOS') THEN 'platform:V1' END,
        CASE WHEN r."browser" <> '' AND r."browser" NOT IN ('Chrome', 'Edge', 'Firefox', 'Safari', 'Samsung Internet') THEN 'browser:V1' END,
        CASE WHEN regexp_matches(r."page_url", '(^|[^A-Za-z])(nan|NaN|None|null|NULL|undefined)([^A-Za-z]|$)') THEN 'page_url:P' END,
        CASE WHEN regexp_matches(r."page_url", '\{[a-z_]+\}') THEN 'page_url:S' END,
        CASE WHEN regexp_matches(r."page_title", '(^|[^A-Za-z])(nan|NaN|None|null|NULL|undefined)([^A-Za-z]|$)') THEN 'page_title:P' END,
        CASE WHEN regexp_matches(r."page_title", '\{[a-z_]+\}') THEN 'page_title:S' END,
        CASE WHEN r."action" <> '' AND r."action" NOT IN ('initiate_payment', 'initiate_transfer', 'login', 'logout', 'view_accounts', 'view_help', 'view_home', 'view_product', 'view_products', 'view_transactions') THEN 'action:V1' END,
        CASE WHEN r."element_id" <> '' AND r."element_id" NOT IN ('accounts_page', 'cc_product', 'help_page', 'home_page', 'loans_product', 'login_form', 'logout_btn', 'payment_form', 'products_page', 'savings_product', 'transactions_page', 'transfer_form') THEN 'element_id:V1' END,
        CASE WHEN r."product_id" <> '' AND NOT regexp_full_match(r."product_id", 'PRD-[0-9A-Z]{12}') THEN 'product_id:K' END,
        CASE WHEN r."event_value" <> '' AND try_cast(r."event_value" AS DOUBLE) IS NULL THEN 'event_value:T' END,
        CASE WHEN r."event_value" <> '' AND NOT regexp_full_match(r."event_value", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."event_value" AS DOUBLE) IS NOT NULL THEN 'event_value:F' END,
        CASE WHEN r."duration_seconds" <> '' AND try_cast(r."duration_seconds" AS DOUBLE) IS NULL THEN 'duration_seconds:T' END,
        CASE WHEN r."duration_seconds" <> '' AND NOT regexp_full_match(r."duration_seconds", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."duration_seconds" AS DOUBLE) IS NOT NULL THEN 'duration_seconds:F' END,
        CASE WHEN r."ip_address" <> '' AND NOT regexp_full_match(r."ip_address", '(?:([0-9]{1,3}\.){3}[0-9]{1,3})') THEN 'ip_address:F' END,
        CASE WHEN coalesce(r."ip_country", '') = '' THEN 'ip_country:N' END,
        CASE WHEN r."ip_country" <> '' AND r."ip_country" NOT IN ('Argentina', 'Colombia', 'México', 'Mexico') THEN 'ip_country:V1' END,
        CASE WHEN r."ip_country" IN ('Mexico') THEN 'ip_country:V2' END,
        CASE WHEN r."ip_city" <> '' AND r."ip_city" NOT IN ('Barranquilla', 'Bogotá', 'Buenos Aires', 'Cali', 'Cartagena', 'Ciudad de México', 'Córdoba', 'Guadalajara', 'La Plata', 'Medellín', 'Mendoza', 'Monterrey', 'Puebla', 'Querétaro', 'Rosario', 'Tijuana') THEN 'ip_city:V1' END,
        CASE WHEN coalesce(r."is_mobile", '') = '' THEN 'is_mobile:N' END,
        CASE WHEN r."is_mobile" <> '' AND try_cast(r."is_mobile" AS BOOLEAN) IS NULL THEN 'is_mobile:T' END,
        CASE WHEN r."is_mobile" <> '' AND NOT regexp_full_match(r."is_mobile", '(?i:(true|false))') AND try_cast(r."is_mobile" AS BOOLEAN) IS NOT NULL THEN 'is_mobile:F' END,
        CASE WHEN r."referrer" <> '' AND r."referrer" NOT IN ('https://email.marketing.com', 'https://www.facebook.com', 'https://www.google.com', 'https://www.instagram.com') THEN 'referrer:V1' END,
        CASE WHEN r."utm_source" <> '' AND r."utm_source" NOT IN ('direct', 'email', 'facebook', 'google') THEN 'utm_source:V1' END,
        CASE WHEN r."utm_medium" <> '' AND r."utm_medium" NOT IN ('cpc', 'email', 'organic', 'social') THEN 'utm_medium:V1' END,
        CASE WHEN r."utm_campaign" <> '' AND r."utm_campaign" NOT IN ('new_users', 'retention', 'spring_promo') THEN 'utm_campaign:V1' END
    ], x -> x IS NOT NULL) AS _dq_issues
    from {{ source('bronze_raw', 'digital_events') }} r
),
r as (
    select
        o.* REPLACE (
        CASE WHEN map_contains(c.m, 'event_id') THEN c.m['event_id'] ELSE o."event_id" END AS "event_id",
        CASE WHEN map_contains(c.m, 'event_date') THEN c.m['event_date'] ELSE o."event_date" END AS "event_date",
        CASE WHEN map_contains(c.m, 'process_date') THEN c.m['process_date'] ELSE o."process_date" END AS "process_date",
        CASE WHEN map_contains(c.m, 'customer_id') THEN c.m['customer_id'] ELSE o."customer_id" END AS "customer_id",
        CASE WHEN map_contains(c.m, 'session_id') THEN c.m['session_id'] ELSE o."session_id" END AS "session_id",
        CASE WHEN map_contains(c.m, 'event_type') THEN c.m['event_type'] ELSE o."event_type" END AS "event_type",
        CASE WHEN map_contains(c.m, 'event_category') THEN c.m['event_category'] ELSE o."event_category" END AS "event_category",
        CASE WHEN map_contains(c.m, 'channel') THEN c.m['channel'] ELSE o."channel" END AS "channel",
        CASE WHEN map_contains(c.m, 'platform') THEN c.m['platform'] ELSE o."platform" END AS "platform",
        CASE WHEN map_contains(c.m, 'browser') THEN c.m['browser'] ELSE o."browser" END AS "browser",
        CASE WHEN map_contains(c.m, 'app_version') THEN c.m['app_version'] ELSE o."app_version" END AS "app_version",
        CASE WHEN map_contains(c.m, 'page_url') THEN c.m['page_url'] ELSE o."page_url" END AS "page_url",
        CASE WHEN map_contains(c.m, 'page_title') THEN c.m['page_title'] ELSE o."page_title" END AS "page_title",
        CASE WHEN map_contains(c.m, 'action') THEN c.m['action'] ELSE o."action" END AS "action",
        CASE WHEN map_contains(c.m, 'element_id') THEN c.m['element_id'] ELSE o."element_id" END AS "element_id",
        CASE WHEN map_contains(c.m, 'product_id') THEN c.m['product_id'] ELSE o."product_id" END AS "product_id",
        CASE WHEN map_contains(c.m, 'event_value') THEN c.m['event_value'] ELSE o."event_value" END AS "event_value",
        CASE WHEN map_contains(c.m, 'duration_seconds') THEN c.m['duration_seconds'] ELSE o."duration_seconds" END AS "duration_seconds",
        CASE WHEN map_contains(c.m, 'ip_address') THEN c.m['ip_address'] ELSE o."ip_address" END AS "ip_address",
        CASE WHEN map_contains(c.m, 'ip_country') THEN c.m['ip_country'] ELSE o."ip_country" END AS "ip_country",
        CASE WHEN map_contains(c.m, 'ip_city') THEN c.m['ip_city'] ELSE o."ip_city" END AS "ip_city",
        CASE WHEN map_contains(c.m, 'is_mobile') THEN c.m['is_mobile'] ELSE o."is_mobile" END AS "is_mobile",
        CASE WHEN map_contains(c.m, 'referrer') THEN c.m['referrer'] ELSE o."referrer" END AS "referrer",
        CASE WHEN map_contains(c.m, 'utm_source') THEN c.m['utm_source'] ELSE o."utm_source" END AS "utm_source",
        CASE WHEN map_contains(c.m, 'utm_medium') THEN c.m['utm_medium'] ELSE o."utm_medium" END AS "utm_medium",
        CASE WHEN map_contains(c.m, 'utm_campaign') THEN c.m['utm_campaign'] ELSE o."utm_campaign" END AS "utm_campaign"
        ),
        coalesce(list_sort(map_keys(c.m)), []::VARCHAR[]) AS _corrected_columns
    from o
    left join c on c.source_file = o._source_file and c.record_no = o._record_no
)
select
    nullif(r."event_id", '') AS "event_id",
    try_cast(nullif(r."event_date", '') AS TIMESTAMP) AS "event_date",
    try_cast(nullif(r."process_date", '') AS DATE) AS "process_date",
    nullif(r."customer_id", '') AS "customer_id",
    nullif(r."session_id", '') AS "session_id",
    nullif(r."event_type", '') AS "event_type",
    nullif(r."event_category", '') AS "event_category",
    nullif(r."channel", '') AS "channel",
    nullif(r."platform", '') AS "platform",
    nullif(r."browser", '') AS "browser",
    nullif(r."app_version", '') AS "app_version",
    nullif(r."page_url", '') AS "page_url",
    nullif(r."page_title", '') AS "page_title",
    nullif(r."action", '') AS "action",
    nullif(r."element_id", '') AS "element_id",
    nullif(r."product_id", '') AS "product_id",
    try_cast(nullif(r."event_value", '') AS DOUBLE) AS "event_value",
    try_cast(nullif(r."duration_seconds", '') AS DOUBLE) AS "duration_seconds",
    nullif(r."ip_address", '') AS "ip_address",
    nullif(r."ip_country", '') AS "ip_country",
    nullif(r."ip_city", '') AS "ip_city",
    try_cast(nullif(r."is_mobile", '') AS BOOLEAN) AS "is_mobile",
    nullif(r."referrer", '') AS "referrer",
    nullif(r."utm_source", '') AS "utm_source",
    nullif(r."utm_medium", '') AS "utm_medium",
    nullif(r."utm_campaign", '') AS "utm_campaign",
    cast(r._partition_date AS date) AS _partition_date,
    r._source_file,
    r._record_no,
    r._record_sha256,
    r._parse_status,
    'ee4fdcf82d56' AS _contract_version,
    r._dq_issues,
    r._corrected_columns
from r
