-- marketing_campaigns from lossless bronze, typed against platform/contracts/sources/marketing_campaigns.yml
-- (contract b0601e9b9e8c). Generated by scripts/generate_silver_from_contracts.py: do not edit, change the contract and regenerate.
-- '' and absent fields become NULL; a value that does not cast becomes NULL and is listed in _dq_issues
-- as '<column>:<code>' (see audit.dq_cell_findings). Every bronze record is kept, flagged or not.
-- Approved corrections (dq_corrections_active, four-eyes) are overlaid on the text before typing; _dq_issues
-- stays computed on the original text (what the source sent) and _corrected_columns lists what the overlay changed.
with c as (
    select source_file, record_no,
           map_from_entries(list(struct_pack(k := column_name, v := new_value) ORDER BY column_name)) AS m
    from {{ ref('dq_corrections_active') }}
    where zone = 'bronze' and table_name = 'marketing_campaigns'
    group by all
),
o as (
    select r.*, list_filter([
        CASE WHEN r._parse_status <> 'ok' THEN '*:G' END,
        CASE WHEN coalesce(r."campaign_id", '') = '' THEN 'campaign_id:N' END,
        CASE WHEN r."campaign_id" <> '' AND NOT regexp_full_match(r."campaign_id", 'CMP-[0-9A-Z]{12}') THEN 'campaign_id:K' END,
        CASE WHEN coalesce(r."campaign_name", '') = '' THEN 'campaign_name:N' END,
        CASE WHEN regexp_matches(r."description", '(^|[^A-Za-z])(nan|NaN|None|null|NULL|undefined)([^A-Za-z]|$)') THEN 'description:P' END,
        CASE WHEN regexp_matches(r."description", '\{[a-z_]+\}') THEN 'description:S' END,
        CASE WHEN coalesce(r."campaign_type", '') = '' THEN 'campaign_type:N' END,
        CASE WHEN r."campaign_type" <> '' AND r."campaign_type" NOT IN ('Email', 'Mix', 'Push', 'SMS', 'Voice', 'WhatsApp') THEN 'campaign_type:V1' END,
        CASE WHEN coalesce(r."campaign_objective", '') = '' THEN 'campaign_objective:N' END,
        CASE WHEN r."campaign_objective" <> '' AND r."campaign_objective" NOT IN ('Acquisition', 'Cross-sell', 'Reactivation', 'Retention', 'Up-sell') THEN 'campaign_objective:V1' END,
        CASE WHEN r."promoted_product" <> '' AND r."promoted_product" NOT IN ('Cuenta Ahorro', 'Cuenta Corriente', 'Inversión', 'Préstamo Hipotecario', 'Préstamo Personal', 'Seguro', 'Tarjeta Crédito') THEN 'promoted_product:V1' END,
        CASE WHEN r."target_segment" <> '' AND r."target_segment" NOT IN ('Basic', 'Plus', 'Premium', 'Student') THEN 'target_segment:V1' END,
        CASE WHEN r."target_country" <> '' AND r."target_country" NOT IN ('Argentina', 'Colombia', 'Mexico') THEN 'target_country:V1' END,
        CASE WHEN coalesce(r."start_date", '') = '' THEN 'start_date:N' END,
        CASE WHEN r."start_date" <> '' AND try_cast(r."start_date" AS DATE) IS NULL THEN 'start_date:T' END,
        CASE WHEN r."start_date" <> '' AND NOT regexp_full_match(r."start_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2})') AND try_cast(r."start_date" AS DATE) IS NOT NULL THEN 'start_date:F' END,
        CASE WHEN coalesce(r."end_date", '') = '' THEN 'end_date:N' END,
        CASE WHEN r."end_date" <> '' AND try_cast(r."end_date" AS DATE) IS NULL THEN 'end_date:T' END,
        CASE WHEN r."end_date" <> '' AND NOT regexp_full_match(r."end_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2})') AND try_cast(r."end_date" AS DATE) IS NOT NULL THEN 'end_date:F' END,
        CASE WHEN r."budget" <> '' AND try_cast(r."budget" AS DOUBLE) IS NULL THEN 'budget:T' END,
        CASE WHEN r."budget" <> '' AND NOT regexp_full_match(r."budget", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."budget" AS DOUBLE) IS NOT NULL THEN 'budget:F' END,
        CASE WHEN coalesce(r."campaign_status", '') = '' THEN 'campaign_status:N' END,
        CASE WHEN r."campaign_status" <> '' AND r."campaign_status" NOT IN ('Active', 'Completed', 'Paused') THEN 'campaign_status:V1' END,
        CASE WHEN r."expected_conversion_rate" <> '' AND try_cast(r."expected_conversion_rate" AS DOUBLE) IS NULL THEN 'expected_conversion_rate:T' END,
        CASE WHEN r."expected_conversion_rate" <> '' AND NOT regexp_full_match(r."expected_conversion_rate", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."expected_conversion_rate" AS DOUBLE) IS NOT NULL THEN 'expected_conversion_rate:F' END
    ], x -> x IS NOT NULL) AS _dq_issues
    from {{ source('bronze_raw', 'marketing_campaigns') }} r
),
r as (
    select
        o.* REPLACE (
        CASE WHEN map_contains(c.m, 'campaign_id') THEN c.m['campaign_id'] ELSE o."campaign_id" END AS "campaign_id",
        CASE WHEN map_contains(c.m, 'campaign_name') THEN c.m['campaign_name'] ELSE o."campaign_name" END AS "campaign_name",
        CASE WHEN map_contains(c.m, 'description') THEN c.m['description'] ELSE o."description" END AS "description",
        CASE WHEN map_contains(c.m, 'campaign_type') THEN c.m['campaign_type'] ELSE o."campaign_type" END AS "campaign_type",
        CASE WHEN map_contains(c.m, 'campaign_objective') THEN c.m['campaign_objective'] ELSE o."campaign_objective" END AS "campaign_objective",
        CASE WHEN map_contains(c.m, 'promoted_product') THEN c.m['promoted_product'] ELSE o."promoted_product" END AS "promoted_product",
        CASE WHEN map_contains(c.m, 'target_segment') THEN c.m['target_segment'] ELSE o."target_segment" END AS "target_segment",
        CASE WHEN map_contains(c.m, 'target_country') THEN c.m['target_country'] ELSE o."target_country" END AS "target_country",
        CASE WHEN map_contains(c.m, 'start_date') THEN c.m['start_date'] ELSE o."start_date" END AS "start_date",
        CASE WHEN map_contains(c.m, 'end_date') THEN c.m['end_date'] ELSE o."end_date" END AS "end_date",
        CASE WHEN map_contains(c.m, 'budget') THEN c.m['budget'] ELSE o."budget" END AS "budget",
        CASE WHEN map_contains(c.m, 'campaign_status') THEN c.m['campaign_status'] ELSE o."campaign_status" END AS "campaign_status",
        CASE WHEN map_contains(c.m, 'expected_conversion_rate') THEN c.m['expected_conversion_rate'] ELSE o."expected_conversion_rate" END AS "expected_conversion_rate"
        ),
        coalesce(list_sort(map_keys(c.m)), []::VARCHAR[]) AS _corrected_columns
    from o
    left join c on c.source_file = o._source_file and c.record_no = o._record_no
)
select
    nullif(r."campaign_id", '') AS "campaign_id",
    nullif(r."campaign_name", '') AS "campaign_name",
    nullif(r."description", '') AS "description",
    nullif(r."campaign_type", '') AS "campaign_type",
    nullif(r."campaign_objective", '') AS "campaign_objective",
    nullif(r."promoted_product", '') AS "promoted_product",
    nullif(r."target_segment", '') AS "target_segment",
    nullif(r."target_country", '') AS "target_country",
    try_cast(nullif(r."start_date", '') AS DATE) AS "start_date",
    try_cast(nullif(r."end_date", '') AS DATE) AS "end_date",
    try_cast(nullif(r."budget", '') AS DOUBLE) AS "budget",
    nullif(r."campaign_status", '') AS "campaign_status",
    try_cast(nullif(r."expected_conversion_rate", '') AS DOUBLE) AS "expected_conversion_rate",
    cast(r._partition_date AS date) AS _partition_date,
    r._source_file,
    r._record_no,
    r._record_sha256,
    r._parse_status,
    'b0601e9b9e8c' AS _contract_version,
    r._dq_issues,
    r._corrected_columns
from r
