-- customers from lossless bronze, typed against platform/contracts/sources/customers.yml
-- (contract cc1853a83494). Generated by scripts/generate_silver_from_contracts.py: do not edit, change the contract and regenerate.
-- '' and absent fields become NULL; a value that does not cast becomes NULL and is listed in _dq_issues
-- as '<column>:<code>' (see audit.dq_cell_findings). Every bronze record is kept, flagged or not.
-- Approved corrections (dq_corrections_active, four-eyes) are overlaid on the text before typing; _dq_issues
-- stays computed on the original text (what the source sent) and _corrected_columns lists what the overlay changed.
with c as (
    select source_file, record_no,
           map_from_entries(list(struct_pack(k := column_name, v := new_value) ORDER BY column_name)) AS m
    from {{ ref('dq_corrections_active') }}
    where zone = 'bronze' and table_name = 'customers'
    group by all
),
o as (
    select r.*, list_filter([
        CASE WHEN r._parse_status <> 'ok' THEN '*:G' END,
        CASE WHEN coalesce(r."customer_id", '') = '' THEN 'customer_id:N' END,
        CASE WHEN r."customer_id" <> '' AND NOT regexp_full_match(r."customer_id", 'CLI-[0-9A-Z]{12}') THEN 'customer_id:K' END,
        CASE WHEN coalesce(r."document_number", '') = '' THEN 'document_number:N' END,
        CASE WHEN coalesce(r."document_type", '') = '' THEN 'document_type:N' END,
        CASE WHEN r."document_type" <> '' AND r."document_type" NOT IN ('CC', 'CE', 'DNI', 'Pasaporte') THEN 'document_type:V1' END,
        CASE WHEN coalesce(r."first_name", '') = '' THEN 'first_name:N' END,
        CASE WHEN coalesce(r."last_name", '') = '' THEN 'last_name:N' END,
        CASE WHEN coalesce(r."date_of_birth", '') = '' THEN 'date_of_birth:N' END,
        CASE WHEN r."date_of_birth" <> '' AND try_cast(r."date_of_birth" AS DATE) IS NULL THEN 'date_of_birth:T' END,
        CASE WHEN r."date_of_birth" <> '' AND NOT regexp_full_match(r."date_of_birth", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2})') AND try_cast(r."date_of_birth" AS DATE) IS NOT NULL THEN 'date_of_birth:F' END,
        CASE WHEN coalesce(r."gender", '') = '' THEN 'gender:N' END,
        CASE WHEN r."gender" <> '' AND r."gender" NOT IN ('F', 'M', 'O') THEN 'gender:V1' END,
        CASE WHEN coalesce(r."city", '') = '' THEN 'city:N' END,
        CASE WHEN r."city" <> '' AND r."city" NOT IN ('Barranquilla', 'Bogotá', 'Buenos Aires', 'Cali', 'Cartagena', 'Ciudad de México', 'Córdoba', 'Guadalajara', 'La Plata', 'Medellín', 'Mendoza', 'Monterrey', 'Puebla', 'Querétaro', 'Rosario', 'Tijuana') THEN 'city:V1' END,
        CASE WHEN coalesce(r."state", '') = '' THEN 'state:N' END,
        CASE WHEN r."state" <> '' AND r."state" NOT IN ('Antioquia', 'Atlántico', 'Baja California', 'Bolívar', 'Buenos Aires', 'Ciudad Autónoma de Buenos Aires', 'Ciudad de México', 'Cundinamarca', 'Córdoba', 'Jalisco', 'Mendoza', 'Nuevo León', 'Puebla', 'Querétaro', 'Santa Fe', 'Valle del Cauca') THEN 'state:V1' END,
        CASE WHEN coalesce(r."country", '') = '' THEN 'country:N' END,
        CASE WHEN r."country" <> '' AND r."country" NOT IN ('Argentina', 'Colombia', 'México') THEN 'country:V1' END,
        CASE WHEN r."detected_accent" <> '' AND r."detected_accent" NOT IN ('argentine', 'colombian', 'mexican') THEN 'detected_accent:V1' END,
        CASE WHEN coalesce(r."segment", '') = '' THEN 'segment:N' END,
        CASE WHEN r."segment" <> '' AND r."segment" NOT IN ('Basic', 'Plus', 'Premium', 'Student') THEN 'segment:V1' END,
        CASE WHEN r."credit_score" <> '' AND try_cast(r."credit_score" AS DOUBLE) IS NULL THEN 'credit_score:T' END,
        CASE WHEN r."credit_score" <> '' AND NOT regexp_full_match(r."credit_score", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."credit_score" AS DOUBLE) IS NOT NULL THEN 'credit_score:F' END,
        CASE WHEN r."estimated_monthly_income" <> '' AND try_cast(r."estimated_monthly_income" AS DOUBLE) IS NULL THEN 'estimated_monthly_income:T' END,
        CASE WHEN r."estimated_monthly_income" <> '' AND NOT regexp_full_match(r."estimated_monthly_income", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."estimated_monthly_income" AS DOUBLE) IS NOT NULL THEN 'estimated_monthly_income:F' END,
        CASE WHEN r."occupation" <> '' AND r."occupation" NOT IN ('Accountant', 'Administrative', 'Artist', 'Consultant', 'Director', 'Doctor', 'Driver', 'Employee', 'Engineer', 'Entrepreneur', 'Homemaker', 'Independent Professional', 'Lawyer', 'Manager', 'Merchant', 'Retired', 'Salesperson', 'Student', 'Teacher', 'Technician') THEN 'occupation:V1' END,
        CASE WHEN r."marital_status" <> '' AND r."marital_status" NOT IN ('Divorced', 'Married', 'Single', 'Widowed') THEN 'marital_status:V1' END,
        CASE WHEN r."education_level" <> '' AND r."education_level" NOT IN ('College Prep', 'Elementary', 'Graduate', 'High School', 'University') THEN 'education_level:V1' END,
        CASE WHEN coalesce(r."registration_date", '') = '' THEN 'registration_date:N' END,
        CASE WHEN r."registration_date" <> '' AND try_cast(r."registration_date" AS TIMESTAMP) IS NULL THEN 'registration_date:T' END,
        CASE WHEN r."registration_date" <> '' AND NOT regexp_full_match(r."registration_date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]+)?)?)') AND try_cast(r."registration_date" AS TIMESTAMP) IS NOT NULL THEN 'registration_date:F' END,
        CASE WHEN coalesce(r."registration_branch_id", '') = '' THEN 'registration_branch_id:N' END,
        CASE WHEN r."registration_branch_id" <> '' AND NOT regexp_full_match(r."registration_branch_id", 'SUC-[0-9A-Z]{8}') THEN 'registration_branch_id:K' END,
        CASE WHEN coalesce(r."customer_status", '') = '' THEN 'customer_status:N' END,
        CASE WHEN r."customer_status" <> '' AND r."customer_status" NOT IN ('Active', 'Closed', 'Inactive', 'Suspended') THEN 'customer_status:V1' END,
        CASE WHEN coalesce(r."last_updated", '') = '' THEN 'last_updated:N' END,
        CASE WHEN r."last_updated" <> '' AND try_cast(r."last_updated" AS TIMESTAMP) IS NULL THEN 'last_updated:T' END,
        CASE WHEN r."last_updated" <> '' AND NOT regexp_full_match(r."last_updated", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2} [0-9]{2}:[0-9]{2}(:[0-9]{2}(\.[0-9]+)?)?)') AND try_cast(r."last_updated" AS TIMESTAMP) IS NOT NULL THEN 'last_updated:F' END,
        CASE WHEN coalesce(r."accepts_marketing", '') = '' THEN 'accepts_marketing:N' END,
        CASE WHEN r."accepts_marketing" <> '' AND try_cast(r."accepts_marketing" AS BOOLEAN) IS NULL THEN 'accepts_marketing:T' END,
        CASE WHEN r."accepts_marketing" <> '' AND NOT regexp_full_match(r."accepts_marketing", '(?i:(true|false))') AND try_cast(r."accepts_marketing" AS BOOLEAN) IS NOT NULL THEN 'accepts_marketing:F' END
    ], x -> x IS NOT NULL) AS _dq_issues
    from {{ source('bronze_raw', 'customers') }} r
),
r as (
    select
        o.* REPLACE (
        CASE WHEN map_contains(c.m, 'customer_id') THEN c.m['customer_id'] ELSE o."customer_id" END AS "customer_id",
        CASE WHEN map_contains(c.m, 'document_number') THEN c.m['document_number'] ELSE o."document_number" END AS "document_number",
        CASE WHEN map_contains(c.m, 'document_type') THEN c.m['document_type'] ELSE o."document_type" END AS "document_type",
        CASE WHEN map_contains(c.m, 'first_name') THEN c.m['first_name'] ELSE o."first_name" END AS "first_name",
        CASE WHEN map_contains(c.m, 'last_name') THEN c.m['last_name'] ELSE o."last_name" END AS "last_name",
        CASE WHEN map_contains(c.m, 'date_of_birth') THEN c.m['date_of_birth'] ELSE o."date_of_birth" END AS "date_of_birth",
        CASE WHEN map_contains(c.m, 'gender') THEN c.m['gender'] ELSE o."gender" END AS "gender",
        CASE WHEN map_contains(c.m, 'email') THEN c.m['email'] ELSE o."email" END AS "email",
        CASE WHEN map_contains(c.m, 'mobile_phone') THEN c.m['mobile_phone'] ELSE o."mobile_phone" END AS "mobile_phone",
        CASE WHEN map_contains(c.m, 'landline_phone') THEN c.m['landline_phone'] ELSE o."landline_phone" END AS "landline_phone",
        CASE WHEN map_contains(c.m, 'address') THEN c.m['address'] ELSE o."address" END AS "address",
        CASE WHEN map_contains(c.m, 'city') THEN c.m['city'] ELSE o."city" END AS "city",
        CASE WHEN map_contains(c.m, 'state') THEN c.m['state'] ELSE o."state" END AS "state",
        CASE WHEN map_contains(c.m, 'country') THEN c.m['country'] ELSE o."country" END AS "country",
        CASE WHEN map_contains(c.m, 'postal_code') THEN c.m['postal_code'] ELSE o."postal_code" END AS "postal_code",
        CASE WHEN map_contains(c.m, 'detected_accent') THEN c.m['detected_accent'] ELSE o."detected_accent" END AS "detected_accent",
        CASE WHEN map_contains(c.m, 'segment') THEN c.m['segment'] ELSE o."segment" END AS "segment",
        CASE WHEN map_contains(c.m, 'credit_score') THEN c.m['credit_score'] ELSE o."credit_score" END AS "credit_score",
        CASE WHEN map_contains(c.m, 'estimated_monthly_income') THEN c.m['estimated_monthly_income'] ELSE o."estimated_monthly_income" END AS "estimated_monthly_income",
        CASE WHEN map_contains(c.m, 'occupation') THEN c.m['occupation'] ELSE o."occupation" END AS "occupation",
        CASE WHEN map_contains(c.m, 'marital_status') THEN c.m['marital_status'] ELSE o."marital_status" END AS "marital_status",
        CASE WHEN map_contains(c.m, 'education_level') THEN c.m['education_level'] ELSE o."education_level" END AS "education_level",
        CASE WHEN map_contains(c.m, 'registration_date') THEN c.m['registration_date'] ELSE o."registration_date" END AS "registration_date",
        CASE WHEN map_contains(c.m, 'registration_branch_id') THEN c.m['registration_branch_id'] ELSE o."registration_branch_id" END AS "registration_branch_id",
        CASE WHEN map_contains(c.m, 'customer_status') THEN c.m['customer_status'] ELSE o."customer_status" END AS "customer_status",
        CASE WHEN map_contains(c.m, 'last_updated') THEN c.m['last_updated'] ELSE o."last_updated" END AS "last_updated",
        CASE WHEN map_contains(c.m, 'accepts_marketing') THEN c.m['accepts_marketing'] ELSE o."accepts_marketing" END AS "accepts_marketing"
        ),
        coalesce(list_sort(map_keys(c.m)), []::VARCHAR[]) AS _corrected_columns
    from o
    left join c on c.source_file = o._source_file and c.record_no = o._record_no
)
select
    nullif(r."customer_id", '') AS "customer_id",
    nullif(r."document_number", '') AS "document_number",
    nullif(r."document_type", '') AS "document_type",
    nullif(r."first_name", '') AS "first_name",
    nullif(r."last_name", '') AS "last_name",
    try_cast(nullif(r."date_of_birth", '') AS DATE) AS "date_of_birth",
    nullif(r."gender", '') AS "gender",
    nullif(r."email", '') AS "email",
    nullif(r."mobile_phone", '') AS "mobile_phone",
    nullif(r."landline_phone", '') AS "landline_phone",
    nullif(r."address", '') AS "address",
    nullif(r."city", '') AS "city",
    nullif(r."state", '') AS "state",
    nullif(r."country", '') AS "country",
    nullif(r."postal_code", '') AS "postal_code",
    nullif(r."detected_accent", '') AS "detected_accent",
    nullif(r."segment", '') AS "segment",
    try_cast(nullif(r."credit_score", '') AS DOUBLE) AS "credit_score",
    try_cast(nullif(r."estimated_monthly_income", '') AS DOUBLE) AS "estimated_monthly_income",
    nullif(r."occupation", '') AS "occupation",
    nullif(r."marital_status", '') AS "marital_status",
    nullif(r."education_level", '') AS "education_level",
    try_cast(nullif(r."registration_date", '') AS TIMESTAMP) AS "registration_date",
    nullif(r."registration_branch_id", '') AS "registration_branch_id",
    nullif(r."customer_status", '') AS "customer_status",
    try_cast(nullif(r."last_updated", '') AS TIMESTAMP) AS "last_updated",
    try_cast(nullif(r."accepts_marketing", '') AS BOOLEAN) AS "accepts_marketing",
    cast(r._partition_date AS date) AS _partition_date,
    r._source_file,
    r._record_no,
    r._record_sha256,
    r._parse_status,
    'cc1853a83494' AS _contract_version,
    r._dq_issues,
    r._corrected_columns
from r
