-- daily_exchange_rates from lossless bronze, typed against platform/contracts/sources/daily_exchange_rates.yml
-- (contract bc6a5070f4a4). Generated by scripts/generate_silver_from_contracts.py: do not edit, change the contract and regenerate.
-- '' and absent fields become NULL; a value that does not cast becomes NULL and is listed in _dq_issues
-- as '<column>:<code>' (see audit.dq_cell_findings). Every bronze record is kept, flagged or not.
select
    try_cast(nullif(r."date", '') AS DATE) AS "date",
    nullif(r."source_currency", '') AS "source_currency",
    nullif(r."target_currency", '') AS "target_currency",
    try_cast(nullif(r."exchange_rate", '') AS DOUBLE) AS "exchange_rate",
    try_cast(nullif(r."buy_rate", '') AS DOUBLE) AS "buy_rate",
    try_cast(nullif(r."sell_rate", '') AS DOUBLE) AS "sell_rate",
    nullif(r."source", '') AS "source",
    cast(r._partition_date AS date) AS _partition_date,
    r._source_file,
    r._record_no,
    r._record_sha256,
    r._parse_status,
    'bc6a5070f4a4' AS _contract_version,
    list_filter([
        CASE WHEN r._parse_status <> 'ok' THEN '*:G' END,
        CASE WHEN coalesce(r."date", '') = '' THEN 'date:N' END,
        CASE WHEN r."date" <> '' AND try_cast(r."date" AS DATE) IS NULL THEN 'date:T' END,
        CASE WHEN r."date" <> '' AND NOT regexp_full_match(r."date", '(?:[0-9]{4}-[0-9]{2}-[0-9]{2})') AND try_cast(r."date" AS DATE) IS NOT NULL THEN 'date:F' END,
        CASE WHEN coalesce(r."source_currency", '') = '' THEN 'source_currency:N' END,
        CASE WHEN r."source_currency" <> '' AND r."source_currency" NOT IN ('ARS', 'COP', 'MXN', 'USD') THEN 'source_currency:V1' END,
        CASE WHEN coalesce(r."target_currency", '') = '' THEN 'target_currency:N' END,
        CASE WHEN r."target_currency" <> '' AND r."target_currency" NOT IN ('ARS', 'COP', 'MXN', 'USD') THEN 'target_currency:V1' END,
        CASE WHEN coalesce(r."exchange_rate", '') = '' THEN 'exchange_rate:N' END,
        CASE WHEN r."exchange_rate" <> '' AND try_cast(r."exchange_rate" AS DOUBLE) IS NULL THEN 'exchange_rate:T' END,
        CASE WHEN r."exchange_rate" <> '' AND NOT regexp_full_match(r."exchange_rate", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."exchange_rate" AS DOUBLE) IS NOT NULL THEN 'exchange_rate:F' END,
        CASE WHEN coalesce(r."buy_rate", '') = '' THEN 'buy_rate:N' END,
        CASE WHEN r."buy_rate" <> '' AND try_cast(r."buy_rate" AS DOUBLE) IS NULL THEN 'buy_rate:T' END,
        CASE WHEN r."buy_rate" <> '' AND NOT regexp_full_match(r."buy_rate", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."buy_rate" AS DOUBLE) IS NOT NULL THEN 'buy_rate:F' END,
        CASE WHEN coalesce(r."sell_rate", '') = '' THEN 'sell_rate:N' END,
        CASE WHEN r."sell_rate" <> '' AND try_cast(r."sell_rate" AS DOUBLE) IS NULL THEN 'sell_rate:T' END,
        CASE WHEN r."sell_rate" <> '' AND NOT regexp_full_match(r."sell_rate", '(?:[+-]?[0-9]+)|(?:[+-]?[0-9]*\.[0-9]+)|(?:[+-]?[0-9]*\.?[0-9]+[eE][+-]?[0-9]+)') AND try_cast(r."sell_rate" AS DOUBLE) IS NOT NULL THEN 'sell_rate:F' END,
        CASE WHEN coalesce(r."source", '') = '' THEN 'source:N' END,
        CASE WHEN r."source" <> '' AND r."source" NOT IN ('Bloomberg', 'Central Bank', 'Internal', 'Reuters') THEN 'source:V1' END
    ], x -> x IS NOT NULL) AS _dq_issues
from {{ source('bronze_raw', 'daily_exchange_rates') }} r
