global: {scrape_interval: 15s}
scrape_configs:
  - job_name: fraud-scorer
    static_configs: [{targets: ["fraud-scorer:9108"]}]
  - job_name: redpanda
    metrics_path: /public_metrics
    static_configs: [{targets: ["redpanda:9644"]}]
  - job_name: flink
    static_configs: [{targets: ["flink-jobmanager:9249", "flink-taskmanager:9249"]}]
