-- Generated by platform/dbt/scripts/generate_aggregates.py from eda/src/latam_eda/granularity_hour_sql/fct_channel_hour.sql (ADR-017).
-- Edit the source and regenerate.
-- Periodic snapshot, one row per market, transaction channel and UTC hour, dense over the data window: channel load
-- and capacity (ATM network, app, branches) and the channel mix within the day. Hours are placed on the transaction
-- delivery clock through dim_hour (hour_of_day 0 = 06:00 UTC).
-- grain: country_code, channel, hour_start
-- reconcile: n_tx = count(*) from {int_transactions_enriched}
-- reconcile: amount_usd = sum(coalesce(amount_usd, 0)) from {int_transactions_enriched}
-- dense: country_code from {int_customer_profile} x channel from {int_transactions_enriched} x hour_start from {dim_hour}
with t as (
    select p.country_code, t.channel, date_trunc('hour', t.transaction_ts_utc) as hour_start, count(*) as n_tx,
           count(*) filter (where t.transaction_status = 'Declined') as n_declined,
           sum(coalesce(t.amount_usd, 0)) as amount_usd,
           sum(t.amount_usd) filter (where t.is_cash and t.direction = -1 and t.transaction_status = 'Approved') as cash_out_usd
    from {{ ref('int_transactions_enriched') }} t join {{ ref('int_customer_profile') }} p using (customer_id) group by all),
grid as (select m.country_code, c.channel, h.hour_start, h.delivery_day, h.hour_of_day, h.delivery_weekday
         from (select distinct country_code from {{ ref('int_customer_profile') }}) m
         cross join (select distinct channel from {{ ref('int_transactions_enriched') }}) c cross join {{ ref('dim_hour') }} h)
select g.*, coalesce(t.n_tx, 0) as n_tx, coalesce(t.n_declined, 0) as n_declined,
       coalesce(t.amount_usd, 0) as amount_usd, coalesce(t.cash_out_usd, 0) as cash_out_usd
from grid g left join t using (country_code, channel, hour_start)
