/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AtlasRouteImport } from './routes/atlas'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as KnowledgeRouteImport } from './routes/knowledge'
import { Route as PipelinesRouteImport } from './routes/pipelines'
import { Route as QualityRouteImport } from './routes/quality'
import { Route as SpecsRouteImport } from './routes/specs'
import { Route as SupervisorRouteImport } from './routes/supervisor'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AtlasRoute = AtlasRouteImport.update({
  id: '/atlas',
  path: '/atlas',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowledgeRoute = KnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelinesRoute = PipelinesRouteImport.update({
  id: '/pipelines',
  path: '/pipelines',
  getParentRoute: () => rootRouteImport,
} as any)
const QualityRoute = QualityRouteImport.update({
  id: '/quality',
  path: '/quality',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecsRoute = SpecsRouteImport.update({
  id: '/specs',
  path: '/specs',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/chat': typeof ChatRoute
  '/desk': typeof DeskRoute
  '/knowledge': typeof KnowledgeRoute
  '/pipelines': typeof PipelinesRoute
  '/quality': typeof QualityRoute
  '/specs': typeof SpecsRoute
  '/supervisor': typeof SupervisorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/chat': typeof ChatRoute
  '/desk': typeof DeskRoute
  '/knowledge': typeof KnowledgeRoute
  '/pipelines': typeof PipelinesRoute
  '/quality': typeof QualityRoute
  '/specs': typeof SpecsRoute
  '/supervisor': typeof SupervisorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/atlas': typeof AtlasRoute
  '/chat': typeof ChatRoute
  '/desk': typeof DeskRoute
  '/knowledge': typeof KnowledgeRoute
  '/pipelines': typeof PipelinesRoute
  '/quality': typeof QualityRoute
  '/specs': typeof SpecsRoute
  '/supervisor': typeof SupervisorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/atlas'
    | '/chat'
    | '/desk'
    | '/knowledge'
    | '/pipelines'
    | '/quality'
    | '/specs'
    | '/supervisor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/atlas'
    | '/chat'
    | '/desk'
    | '/knowledge'
    | '/pipelines'
    | '/quality'
    | '/specs'
    | '/supervisor'
  id:
    | '__root__'
    | '/'
    | '/atlas'
    | '/chat'
    | '/desk'
    | '/knowledge'
    | '/pipelines'
    | '/quality'
    | '/specs'
    | '/supervisor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtlasRoute: typeof AtlasRoute
  ChatRoute: typeof ChatRoute
  DeskRoute: typeof DeskRoute
  KnowledgeRoute: typeof KnowledgeRoute
  PipelinesRoute: typeof PipelinesRoute
  QualityRoute: typeof QualityRoute
  SpecsRoute: typeof SpecsRoute
  SupervisorRoute: typeof SupervisorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atlas': {
      id: '/atlas'
      path: '/atlas'
      fullPath: '/atlas'
      preLoaderRoute: typeof AtlasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/knowledge': {
      id: '/knowledge'
      path: '/knowledge'
      fullPath: '/knowledge'
      preLoaderRoute: typeof KnowledgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipelines': {
      id: '/pipelines'
      path: '/pipelines'
      fullPath: '/pipelines'
      preLoaderRoute: typeof PipelinesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quality': {
      id: '/quality'
      path: '/quality'
      fullPath: '/quality'
      preLoaderRoute: typeof QualityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specs': {
      id: '/specs'
      path: '/specs'
      fullPath: '/specs'
      preLoaderRoute: typeof SpecsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtlasRoute: AtlasRoute,
  ChatRoute: ChatRoute,
  DeskRoute: DeskRoute,
  KnowledgeRoute: KnowledgeRoute,
  PipelinesRoute: PipelinesRoute,
  QualityRoute: QualityRoute,
  SpecsRoute: SpecsRoute,
  SupervisorRoute: SupervisorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
